1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #126
Opened 2022-09-28 12:05 UTC by Hyeon9mak

안녕하세요 규남님!
이펙티브 코틀린에 이어서 다시 한번 뵙습니다! 🙇‍♂️ 
이펙티브 코틀린에서도 유지보수 하기 쉬운 코드가 무엇인지 한참 배운 것 같은데,
DDD 에서는 얼마나 배울지... 기대가 됩니다...! 😄 

고민해본 포인트가 크게 4가지 있습니다.

---

### 1. 공통되는 외부 클라이언트 위치
비속어 검증 관련 인터페이스와 구현체는 어디에 둘지 고민이었는데요,
'진~~~~짜 common인가?', '비속어에 대한 정의가 각각 다를 수 있나?' 고민을 하며 common 모듈을 만들까 하다가
[김대성님의 멀티 모듈 프로젝트 구조와 설계](https://hyeon9mak.github.io/real-multi-module-project-structure-and-design/)가 떠올랐고, 조금의 중복 코드가 전체적인 복잡도를 낮추는데 더 좋을 것 같아서 필요한 모듈에 모두 배치하고자 했습니다.

### 2. Menu의 Product 의존성
`Menu`가 계속해서 `Product` 관련 의존성에 흔들렸는데요,
이번 미션의 진행 범위는 `Product` 인 것 같아 테스트가 통과하게 끔만 리팩터링하고 `Product` 쪽에 집중했습니다.

### 3. 중복되는 역할을 가진 객체의 이름
`Name`, `Price` 와 같이 중복되는 이름을 가진 객체들엔 prefix를 붙여주었는데요,
옛날에는 패키지를 통해서 충분히 구별되고 있기 때문에 클래스 이름이 동일해도 상관 없을 것 같다! 라고 생각했지만
요즘은 다소 루즈해보이더라도 각각의 컨텍스트 이름을 prefix로 붙이는걸 선호해서입니다.
저를 포함한 대부분의 개발자가 import 영역을 크게 신경쓰지 않는다는 점 때문에 점점 생각이 변하게 된 것 같습니다.
인텔리제이를 사용할 경우 클래스를 검색할 때도 prefix를 통해 검색하기 용이하고, 
혹시나 동일한 클래스들이 동시에 의존될 때도 패키지 경로명이 함께 포함되어 코드가 지저분해지는 일도 방지해줄 것 같습니다. 
또 'EatInOrder' 컨텍스트에서 작업하던 도중에 잠시 컨텍스트를 망각하고 '이 Order는 배달주문 관련이겠지?' 라고 헷갈리는 일을 사전에 방지해줄 것 같습니다.

### 4. `ProductService`를 순수하게..
현재 `ProductService`가 `Request`, `Response`를 인지하고 있는 상황인데요
별도로 `Product`를 감싸줄 서비스 계층을 하나 더 만들까 하다가, 지나치게 오버엔지니어링이 아닐까... 생각이 되어서 멈추었습니다.

---

리뷰 잘 부탁드립니다 🙇‍♂️

2022-09-28 13:25 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-09-28 13:25 UTC, kyucumber commented on src/main/java/kitchenpos/products/domain/Product.java
> +    public Product(String name, BigDecimal price, ProductProfanityCheckClient productProfanityCheckClient) {
Product라는 도메인 클래스가 ProductProfanityCheckClient의 참조를 가지게 되면서 결합이 발생했네요.

ProductName과 ProductProfanityCheckClient이 결합하는건 크게 문제가 될 것 같진 않아요. 다만 Product와 같은 핵심 도메인 클래스의 경우 최대한 외부와의 결합을 줄이고 응집도를 높이는게 좋다고 생각이 들어요. 중복 코드가 발생할 수 있겠지만 아래 생성자를 활용해 외부에서 제약 조건을 충족하는 ProductName을 전달받으면 어떨까요?

```java
public Product(UUID id, ProductName name, ProductPrice price) {
```

위에서 말씀드린 것 처럼 이는 트레이드 오프가 존재합니다. 어떤 것이 더 좋을지 한번 고민해보시면 좋겠네요.

2022-09-28 13:25 UTC, kyucumber commented on src/main/java/kitchenpos/products/application/ProductService.java
> -                menu.setDisplayed(false);
리팩토링 과정에서 이 코드가 삭제되었네요.

이전 미션에서 저희가 열심히 테스트를 작성했던 것은 리팩토링 전에 기존에 존재하던 기능의 동작을 보장하기 위함이었을 것 같아요.

메뉴와의 결합이 제거된 것은 좋지만 기존의 제약 조건이나 동작들을 보장하면서 리팩토링이 이루어져야 할 것 같아요.

2022-09-28 13:25 UTC, kyucumber commented on src/test/java/kitchenpos/products/application/ProductServiceTest.java
> -    @Test
> 2. Menu의 Product 의존성
```
Menu가 계속해서 Product 관련 의존성에 흔들렸는데요,
이번 미션의 진행 범위는 Product 인 것 같아 테스트가 통과하게 끔만 리팩터링하고 Product 쪽에 집중했습니다.
```

테스트가 제거되면서 통과된 것 같네요.
이전에 진행했던 "테스트를 통한 코드 보호" 미션을 생각하면 취지에 맞지 않는 것 같아요. 이번 미션은 상품의 도메인 계층과 관련된 리팩토링이기 때문에 서비스 레이어에 결합이 발생하는 부분이 있는 형태로 두시고 해당 테스트를 살리는 방향으로 진행하면 어떨까요?

2022-09-28 13:25 UTC, kyucumber commented on src/main/java/kitchenpos/products/application/ProductService.java
> -                menu.setDisplayed(false);
이번 미션에서 진행할 내용은 아니지만 이 부분을 어떻게 MenuRepository와 결합 없이 처리할 수 있을지도 고민해보시면 좋을 것 같아요.

2022-09-28 13:25 UTC, kyucumber commented on src/main/java/kitchenpos/products/application/ProductService.java
> +    public ProductResponse create(final ProductCreateRequest request) {
>  4. ProductService를 순수하게..

```
현재 ProductService가 Request, Response를 인지하고 있는 상황인데요
별도로 Product를 감싸줄 서비스 계층을 하나 더 만들까 하다가, 지나치게 오버엔지니어링이 아닐까... 생각이 되어서 멈추었습니다.
```

지금 구조에서는 Product이라는 영속성 계층, 서비스 계층에서 다루는 Product가 외부로 노출되지 않은 것만으로도 충분할 것 같아요. 👍 

Request, Response를 서비스 레이어에서 참조하면 다른 계층(웹)의 변경에 따라 서비스 계층이 영향을 받기 때문에 이상적인 구조라고 보기는 어렵지만 지금과 같은 형태라면 ProductResponse를 바로 반환하는 형태로 사용하는것이 큰 문제가 될 것 같진 않아요.

조금 덧붙이면 오버엔지니어링이라고 해주신 형태는 아래와 같은 형태가 될 것 같네요.

- ProductController(Request, Response와 같은 웹 모델)
- ProductService(Product와 같은 도메인)
- ProductRepository(ProductJpaEntity와 같은 영속성 모델)

위와 같이 매핑하는 것은 너무 많은 보일러플레이트 코드가 생긴다는 단점이 있습니다.

각각의 방법마다 트레이드 오프가 있으며 어느것이 정답이라고 보긴 어려워요. 협업하는 사람들과 장단점을 고려하고 서비스 레이어의 로직이나 상황에 맞춰 적절한 방법을 택해주시면 되겠습니다. 🙂

2022-09-28 23:45 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/application/MenuService.java
>  package kitchenpos.menus.application;
상황에 맞게 사용하면 되고, 현재 상황은 하나의 모듈 내에서 패키지만 나뉘어 있으니 꼭 중복으로 둘 필요가 없겠네요! 👍 
변경해보겠습니다.

2022-09-29 00:00 UTC, Hyeon9mak commented on src/main/java/kitchenpos/products/domain/Product.java
> +    public Product(String name, BigDecimal price, ProductProfanityCheckClient productProfanityCheckClient) {
`String`, `BigDecimal`을 사용하면서도 `Product`를 더 편리하게 생성할 수 있는 방법이 있을까 고민하다가 만들어진 생성자입니다.
다만 말씀해주신 것처럼 비속어 포함여부를 검증하는 일은 `ProductName`의 역할이지, `Product`의 역할이 아닌 것 같습니다.
게다가 `ProductProfanityCheckClient`는 사실 외부 클라이언트이므로... 가능하면 적게 의존할수록 좋을 것 같습니다.

2022-09-29 00:03 UTC, Hyeon9mak commented on src/main/java/kitchenpos/products/application/ProductService.java
> -                menu.setDisplayed(false);
README.md 의 모델링 파트만 보고 리팩터링을 진행하다보니, 자연스럽게 무시하고 지나친 것 같습니다. 꼼꼼하지 못했습니다 😢 
말씀해주신 것처럼 이벤트 발행을 염두해두고 있었습니다. "나 가격 변경되었다. 근데 이걸로 뭘 할지는 누구든지 알아서 해" 를 가장 잘 나타내는게 이벤트 방식인거 같아요! 반영해보겠습니다.

2022-09-29 00:06 UTC, Hyeon9mak commented on src/test/java/kitchenpos/products/application/ProductServiceTest.java
> -    @Test
상품 가격 변경에 따른 메뉴의 동작 검증이므로 메뉴 쪽 테스트가 올바르다고 생각했습니다.
그렇게 생각했다면 테스트를 메뉴 쪽으로 옮겨놨어야 했는데, 그냥 단순히 지워두고 끝으로 여겼네요... 🥲 🥊

2022-09-29 00:53 UTC, Hyeon9mak commented
안녕하세요 규남님! 리뷰 주신 내용 반영해보았습니다!
`purgomalum client` 를 제안주신 의견에 따라 공통되는 패키지로 이동시켰고, 
`Product`가 `purgomalum client`에 의존하지 않도록 변경했습니다.

상품 가격 변경에 따른 메뉴의 상태변화와 그 테스트에 관해서는 조금의 욕심을 부려보았는데요... 
메뉴와 상품 패키지 각각에서 서로를 온전히 모르게 만들고 싶었습니다.
때문에 상품의 가격이 변경되면 변경된 가격에 대한 이벤트를 발행하고, 메뉴 쪽에서 해당 이벤트를 핸들링 할 준비까지 해두었습니다.
호옥시 요런 방향에 대해서는 어떻게 생각하실지요... 미션이 제시하는 방향과 너무 동떨어진다면 곧장 말씀해주신 것처럼 서비스 계층에서 결합을 감안하고 다시 테스트를 살리는 형태로 바꾸도록 하겠습니다. 🙇‍♂️

2022-09-29 11:19 UTC, kyucumber approved these changes
수고 많으셨습니다.

간단한 코멘트 남기긴 했는데 중요한 부분은 아니라 머지할게요~ 시간 나면 한번 확인 부탁드립니다.

2022-09-29 11:19 UTC, kyucumber commented on src/test/java/kitchenpos/products/application/ProductServiceTest.java
> +        publisher = new FakeEventPublisher();
여기선 Fake가 아닌 Spy 형태로 만들어서 이벤트 발행 호출 여부를 검증하면 어떨까요?

2022-09-29 11:19 UTC, kyucumber commented on src/main/java/kitchenpos/Application.java
>  import org.springframework.boot.SpringApplication;
```
상품 가격 변경에 따른 메뉴의 상태변화와 그 테스트에 관해서는 조금의 욕심을 부려보았는데요...
메뉴와 상품 패키지 각각에서 서로를 온전히 모르게 만들고 싶었습니다.
때문에 상품의 가격이 변경되면 변경된 가격에 대한 이벤트를 발행하고, 메뉴 쪽에서 해당 이벤트를 핸들링 할 준비까지 해두었습니다.
호옥시 요런 방향에 대해서는 어떻게 생각하실지요... 미션이 제시하는 방향과 너무 동떨어진다면 곧장 말씀해주신 것처럼 서비스 계층에서 결합을 감안하고 다시 테스트를 살리는 형태로 바꾸도록 하겠습니다. 🙇‍♂️
```

미션에서는 도메인 부분에 대해 리팩토링을 요구하고 있습니다. 다만 이런 부분을 추가적으로 욕심내서 하시는 부분은 상관없으며 미션이 제시하는 방향과도 동떨어져있다고 생각하지 않습니다. 🙂

2022-09-29 11:20 UTC, merged

2022-10-01 01:21 UTC, Hyeon9mak commented on src/test/java/kitchenpos/products/application/ProductServiceTest.java
> +        publisher = new FakeEventPublisher();
👍