2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #142
Opened 2022-10-06 13:46 UTC by iljun

2022-10-07 13:54 UTC, hyunssooo requested changes
안녕하세요, 일준님. 
메뉴 리펙터링 미션 잘 진행해 주셨어요. 👍 
몇 가지 가벼운 코멘트 남겼습니다. 
다음 요청에는 merge 하도록 할게요.

2022-10-07 13:54 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/MenuProduct.java
> +    private Product product;
`MenuProduct` 가 `Product`를 직접 참조하고 있어도 괜찮을까요?

2022-10-07 13:54 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/MenuProducts.java
> +
일급컬렉션 💯 

```suggestion

public class MenuProducts {
    private List<MenuProduct> menuProducts;

```

2022-10-07 13:54 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/MenuPrice.java
> +
Menu에 있는 `Price`와는 어떻게 다를까요? 같은 클래스를 사용해도 괜찮지 않을까요?

2022-10-07 13:54 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/Menu.java
> +    }
인자가가 많아서 가로로 길어지고 있네요. 개인적으로 3개 이상이면 아래로 작성하고 있어요. 
```java
public Menu(
    final MenuName menuName,
    final MenuPrice menuPrice,
    final MenuGroup menuGroup,
    final boolean displayed,
    final MenuProducts menuProducts
) {
  ..
}
```

id도 생성자로 받아 보는 것은 어떨까요? 랜덤한 값은 제어하기 힘드니 외부에서 받는 것도 괜찮을 것 같아요.

2022-10-07 13:54 UTC, hyunssooo commented on src/test/java/kitchenpos/menus/domain/tobe/MenuProductsTest.java
> +    }
```java
    @Test
    @DisplayName("메뉴 상품 묶음 생성이 가능하다")
    void constructor() {
        final MenuProducts menuProducts = new MenuProducts(new MenuProduct(1L, product(), 1), new MenuProduct(2L, product(), 1));
        assertThat(menuProducts).isNotNull();
    }
```
생성자를 다양하게 만들면 사용하는 입장에서 좀 더 편하게 사용할 수 있다고 생각해요. :)

2022-10-07 13:54 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/Menu.java
> +public class Menu {
`상품`과는 다르게 jpa를 사용하지 않으셨네요. 어떤 기준으로 사용하고 안 하고를 정하셨을까요?

2022-10-08 04:57 UTC, iljun commented on src/main/java/kitchenpos/menus/domain/tobe/MenuProduct.java
> +    private Product product;
다른 context의 객체를 참조하도록 구현했군요...
변경하겠습니다

2022-10-08 04:59 UTC, iljun commented on src/main/java/kitchenpos/menus/domain/tobe/MenuPrice.java
> +
`Product`의 Price를 말씀하시는것같은데
현재 기준으로는 동일한 Code를 사용해도 전혀 문제가 없습니다
다만 Context가 다르다면 사전에 Code에서부터 분리를 하는게 어떨까라는 생각으로 구분했습니다

2022-10-08 04:59 UTC, iljun commented on src/main/java/kitchenpos/menus/domain/tobe/Menu.java
> +    }
네네 좋습니당

2022-10-08 05:01 UTC, iljun commented on src/main/java/kitchenpos/menus/domain/tobe/Menu.java
> +public class Menu {
솔직히 `상품`을 구현할때는 제가 미션의 범위를 잘 못 이해하여 JPA까지 사용해서 리팩토링을 진행했습니다
물론 JPA까지 구현하면 좋지만 이번에는 Context 리팩토링에 조금 더 초점을 맞추고 싶어 JPA는 제외하고 리팩토링을 진행해보았습니다 🙇

2022-10-08 20:59 UTC, hyunssooo approved these changes
안녕하세요.
몇 가지 코멘트 남겼습니다.
다음 step 진행하시면서 확인 부탁드릴게요.

2022-10-08 20:59 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/MenuProduct.java
> +import kitchenpos.products.domain.Product;
사용하지 않는 import는 제거하는 것이 좋습니다.

2022-10-08 20:59 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/MenuProduct.java
> +        this.price = product.getPrice().value();
`Product` 의 의존성은 여전히 존재하는 것 같은데요. 
파라미터로 필요한 값들만 받는 것은 어떨까요? 
혹은, Menu BC내에서 `Product`를 다시 정의할 수 있지 않을까요?

2022-10-08 20:59 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/MenuProducts.java
> +    }
```suggestion
    public MenuProducts(final List<MenuProduct> menuProducts) {
        if (Objects.isNull(menuProducts) || menuProducts.isEmpty()) {
            throw new IllegalArgumentException("menuProducts is required");
        }

        this.menuProducts = menuProducts;
    }

    public MenuProducts(final MenuProduct... menuProducts) {
        this(List.of(menuProducts));
    }
```

2022-10-08 20:59 UTC, merged

2022-10-08 21:07 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/domain/tobe/MenuPrice.java
> +
저는 개인적으로 Price, Name 같은 경우는 각각 따로 구현하지 않을 것 같긴해요. 
common 느낌으로 구현할 것 같습니다. 참고만 해주세요. 🙂

제가 조금 어색하게 느낀 부분은 `menu.price`는 객체로 사용하고 있는데 `MenuProduct#totalPrice` 는 `BigDecimal`을 리턴하고 있는 것이 어색하다고 느꼈어요. `MenuPrice` 라는 이름이 `Price` 로 변경된다면 `MenuProduct#totalPrice`의 리턴값이 `Price`도 괜찮을 것 같아서요.