2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #148
Opened 2022-10-09 06:05 UTC by Hyeon9mak

안녕하세요 규남님! 오랜 시간이 흘렀습니다...
menu 패키지에서 product 를 지워내보고자 씨름을 시작한게 이렇게 오래 걸릴 줄 몰랐네요 😭 

초기 리팩터링 단계에서 `Menu` 가 먼저 생성된 후 `MenuProduct` 가 생성되는게 자연스럽다고 생각했습니다.
(`MenuProduct` 라는 네이밍에서 메뉴와 상품의 연결정보라는 느낌을 받아서. `@ManyToOne` 연관관계만 맺으려 했음.)

그러나 "메뉴가 등록되는 과정"을 개발하는 단계에서 여러가지 검증을 선행하기 위해선 
`Menu`가 먼저 생성되는 것보다 `MenuProduct` 리스트가 먼저 생성되는게 훨씬 자연스럽더라구요.

거기다 `MenuProduct` 는 사실 `Menu`를 통해 조회되는게 아니면 의미가 없는 것 같아
`@ManyToOne` 연관관계를 지우고 `@OneToMany` 연관관계만 맺으려고 시도 했습니다.

그러나 "상품의 가격이 변경되면 메뉴의 전시상태가 변경된다." 라는 요구사항을 리팩터링하는 과정에서
`MenuProduct` 를 통해 `Menu` 를 탐색하는 일이 생겨났고, 결국 양방향 연관관계 매핑을 하게 되었습니다.

무언가 고민하고 시도한건 많은 것 같은데 결과물은 초라한 것 같아 아쉽네요...
리뷰 잘 부탁드립니다! 🙇‍♂️

2022-10-09 14:51 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/MenuService.java
>  public class MenuService {
```
안녕하세요 규남님! 오랜 시간이 흘렀습니다...
menu 패키지에서 product 를 지워내보고자 씨름을 시작한게 이렇게 오래 걸릴 줄 몰랐네요 😭
```

사실 이번 미션은 도메인에 대한 리팩토링만 진행하는거였는데 서비스쪽 까지 다 진행해주셔서 오래 걸릴 수 밖에 없었을 것 같아요 😭 

수고 많으셨습니다!

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/reader/ProductPriceReader.java
> +    }
이건 인터페이스를 추출하고 구현체를 따로 만들면 부패 방지 계층(Anticorruption Layer)의 역할을 할 수 있겠네요.

만약 인터페이스가 추출되고 구현체가 따로 있는 경우 Product라는 바운디드 컨텍스트가 아예 다른 레파지토리(서비스)로 분리되었을 때 이점이 있을까요?

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/menus/domain/Menu.java
> +    private MenuProducts menuProducts;
```
거기다 MenuProduct 는 사실 Menu를 통해 조회되는게 아니면 의미가 없는 것 같아
@ManyToOne 연관관계를 지우고 @OneToMany 연관관계만 맺으려고 시도 했습니다.

그러나 "상품의 가격이 변경되면 메뉴의 전시상태가 변경된다." 라는 요구사항을 리팩터링하는 과정에서
MenuProduct 를 통해 Menu 를 탐색하는 일이 생겨났고, 결국 양방향 연관관계 매핑을 하게 되었습니다.
```

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/menus/domain/Menu.java
> +    private MenuProducts menuProducts;
가급적 결합을 낮추기 위해 연관관계를 끊는게 좋겠지만

메뉴와 메뉴 상품은 같은 바운디드 컨텍스트 내에 존재하는 개념이기도 하고 JPA의 특성 상 일대 다 단방향 매핑은 성능 문제가 있습니다. 물론 MenuProduct의 개수가 엄청나게 많아지는 상황은 아닐 것 같아 큰 오버헤드는 없겠지만요

따라서 저는 양방향 매핑을 하신게 나쁜 선택은 아니라고 생각이 되네요.

아래 문서도 한번 참고해보세요.

https://homoefficio.github.io/2019/04/28/JPA-%EC%9D%BC%EB%8C%80%EB%8B%A4-%EB%8B%A8%EB%B0%A9%ED%96%A5-%EB%A7%A4%ED%95%91-%EC%9E%98%EB%AA%BB-%EC%82%AC%EC%9A%A9%ED%95%98%EB%A9%B4-%EB%B2%8C%EC%96%B4%EC%A7%80%EB%8A%94-%EC%9D%BC/

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/event/ProductPriceChangedEvent.java
>      }
이런 경우는 사실 어쩔 수 없는 것 같아요.

만약 테스트 이외에 동등성 비교가 필요없다면 publish에 대해 동등성 검증 없이 ProductPriceChangedEvent 타입으로 이벤트가 잘 발행되었는지만 체크하셔도 무방할 것 같긴 해요.

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/MenuEventHandler.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
👍

2022-10-09 14:51 UTC, kyucumber commented on src/test/java/kitchenpos/menus/domain/MenuProductsTest.java
> +class MenuProductsTest {
ValueObject나 일급 컬렉션에 대한 테스트도 잘 작성해주셨네요 👍

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/menus/exception/AlreadyEnrollMenuException.java
> +package kitchenpos.menus.exception;
custom exception을 만드는걸 선호하시는분도 계셔서 반영하지 않으셔도 괜찮은데 개인적인 의견 남깁니다.

대부분 예외 케이스에 대한 커스텀 예외를 만들어주신 것 같아요.
이 경우 도메인이 복잡해지면 커스텀 예외만 수십, 수백개가 넘어가는 경우가 생길 것 같은데 상황에 따라 아래와 같은 표준 예외를 사용하고 에러 메시지로 구분해도 괜찮지 않을까요?

- IllegalArgumentException
- IllegalStateException

표준 예외를 사용했을 때 장점은 아래와 같습니다.
- 협업 시 다른 개발자들이 어떤 예외인지 한번에 인지할 수 있다.
- 클래스의 수가 적을수록 메모리 사용량이 줄어들고 클래스 로딩 시간 또한 줄어든다.

자세한 내용은 아래 글도 한번 참고해보세요.


https://insight-bgh.tistory.com/470

2022-10-09 14:51 UTC, kyucumber commented on src/main/java/kitchenpos/menus/domain/JpaMenuProductRepository.java
> +public interface JpaMenuProductRepository extends MenuProductRepository, JpaRepository<MenuProduct, Long> {
MenuProductRepository같은 인터페이스는 도메인 패키지가 적합한 것 같은데

JpaRepository는 특정 인프라와 관련되어 있으므로 infra와 같은 패키지가 적합하다고도 볼 수 있을까요?

2022-10-10 06:49 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/Menu.java
> +    private MenuProducts menuProducts;
오! 비즈니스 로직상 `Menu` 에서 `MenuProduct` 가 변경되거나 삭제될 일이 많지 않겠지만, 그래도 혹시 모를 성능 이슈 방지용으로 적절한 선택이 된거 같네요. 🙇‍♂️

2022-10-10 07:00 UTC, Hyeon9mak commented on src/main/java/kitchenpos/reader/ProductPriceReader.java
> +    }
'인터페이스로 분리해서 부패 방지 계층을 만들었을 때의 이점이 무엇일까?' 와 같은 말씀이실까요?

`ProductPriceReader` 가 원하는 것은 BigDecimal 타입의 가격 데이터 뿐이므로,
`Product` 에 대한 의존이 최소화 할 수 있을 것 같습니다.

`Product` 에 대한 의존이 적어진다면 그만큼 내부 구현(`product.getPriceValue()` 등)이 변화하거나, 
`Product` 자체가 사라져도 `ProductPriceReader` 인터페이스는 건재하게 살아남고, 
`ProductPriceReader` 구현체를 수정 하는게 아닌, 새로운 구현체를 추가 하는 것으로 OCP 를 지키기에도 좋을 것 같습니다.

2022-10-10 07:19 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/JpaMenuProductRepository.java
> +public interface JpaMenuProductRepository extends MenuProductRepository, JpaRepository<MenuProduct, Long> {
"JPA 대신 다른 데이터베이스 프레임워크로 변경이 필요할 때 domain 패키지 내부를 살펴보아야 할까?" 라고 생각하면....
관심사가 JPA 뿐이지, 비즈니스 로직이 함께 섞여 있는 domain 은 아닐거라는 생각이 듭니다.
바로 분리해보겠습니다..!

2022-10-10 07:25 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/exception/AlreadyEnrollMenuException.java
> +package kitchenpos.menus.exception;
아, 맞습니다. 
심지어는 규남님 말씀대로 "다른 개발자들이 어떤 예외인지 바로 인지할 수 있다." 라는 장점 때문에 표준 예외 사용을 지향하고,
정말 눈에 띄어야 하는 특수한 경우에만 커스텀 예외를 만드려고 하는데요...
이번 미션을 진행하는 동안은 테스트 검증 편의 때문에 한번 만들기 시작한 후로 큰 생각 없이 관성대로 커스텀 예외를 만들고 있었던 것 같습니다... 😵 

불필요한 커스텀 예외를 걷어내고 메세지를 검증하는 방식으로 변경해보겠습니다.

2022-10-10 08:04 UTC, Hyeon9mak commented on src/main/java/kitchenpos/reader/ProductPriceReader.java
> +    }
반영커밋 https://github.com/next-step/ddd-tactical-design/pull/148/commits/338f7391d381c25fc8022152efa3c712542ac240

2022-10-10 08:05 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/exception/AlreadyEnrollMenuException.java
> +package kitchenpos.menus.exception;
반영커밋 https://github.com/next-step/ddd-tactical-design/pull/148/commits/2ac744368c187c3452adb7e7835f223874ac7f05 https://github.com/next-step/ddd-tactical-design/pull/148/commits/569c6c6e9b955782255c634c31cf4c40be39264c

2022-10-10 08:05 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/JpaMenuProductRepository.java
> +public interface JpaMenuProductRepository extends MenuProductRepository, JpaRepository<MenuProduct, Long> {
반영커밋 https://github.com/next-step/ddd-tactical-design/pull/148/commits/a717c7fb4a2aabbc33d8bc0cae6ef34446712761

2022-10-10 08:07 UTC, Hyeon9mak commented
규남님! 리뷰 주신 내용 확인 후 반영해보았습니다. 각각 코멘트에 반영한 커밋 남겨두었습니다 🙇‍♂️ 

> 만약 테스트 이외에 동등성 비교가 필요없다면 publish에 대해 동등성 검증 없이 ProductPriceChangedEvent 타입으로 이벤트가 잘 발행되었는지만 체크하셔도 무방할 것 같긴 해요.

개인적으로 이벤트는 발행한 시간, 시점, 관점에 따라서 각각 다르게 인식되어야 한다고 생각해서 동등성 부여를 피하고 싶습니다. 그래서 가능하다면 꼭 테스트를 개선해보고 싶은데요! 혹시 관련한 방법을 조금 배울 수 있을까... mockito 를 평소 활용하지 않다보니 공식문서를 참고해도 관련한 테스트 방법을 잘 모르겠더라구요... 😭

2022-10-10 11:52 UTC, kyucumber commented
```
개인적으로 이벤트는 발행한 시간, 시점, 관점에 따라서 각각 다르게 인식되어야 한다고 생각해서 동등성 부여를 피하고 싶습니다. 그래서 가능하다면 꼭 테스트를 개선해보고 싶은데요! 혹시 관련한 방법을 조금 배울 수 있을까... mockito 를 평소 활용하지 않다보니 공식문서를 참고해도 관련한 테스트 방법을 잘 모르겠더라구요... 😭
```

이부분은 "상품의 가격을 변경할 수 있다."라는 테스트에서 이벤트의 동등성 비교를 위해서 equals와 hashCode를 정의했고, 단순히 테스트에서의 동등성 비교를 위해 해당 메소드를 추가하는것이 맞는지 고민된다고 하셨던 내용이 아닌걸까요?

각각 이벤트가 발행 시간, 시점, 관점에 따라 다르게 인식되어야 한다면 equals와 hashCode를 정의해주시는게 맞을 것 같고 이에 따라 테스트 또한 아래처럼 작성해주신 형태 그대로 사용하셔도 무방할 것 같아요

```java
verify(publisher).publishEvent(new ProductPriceChangedEvent(productId, BigDecimal.valueOf(15_000)));
```

구체적으로 이벤트를 받아 처리하는 Listener와 관련된 부분의 테스트도 추가될 것이기 때문에 이벤트 발행과 관련된 부분은 위처럼 해당 타입의 이벤트가 잘 발행되었는지 까지만 검증하면 된다고 생각해요.

2022-10-11 13:15 UTC, kyucumber commented
제가 Mockito를 사용하지 않긴 하는데 아래와 같은 형태로 특정 클래스가 왔는지 검증할 수 있었던 걸로 기억합니다.

```java
verify(publisher).publishEvent(any(ProductPriceChangedEvent.class));
```

Mockito Argument Mathcer와 같은 키워드로 검색하면 자료들이 나올거라 한번 찾아본 뒤 사용해보세요.

2022-10-11 13:16 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

질문에 대한 답은 아래 코멘트에 남겨두었어요.

https://github.com/next-step/ddd-tactical-design/pull/148#issuecomment-1274671245

다음 단계 진행을 위해 머지할게요

2022-10-11 13:16 UTC, merged