🚀 2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #156
Opened 2022-10-13 11:56 UTC by wenodev

안녕하세요 재석님!!
menu도 refactoring을 했습니다!!

1단계에서 주신 피드백이 큰 도움이 되었습니다!!

2단계 리뷰도 잘 부탁드립니다!!
감사합니다🙏

2022-10-13 14:23 UTC, seok-2-o requested changes
두번째미션 잘진행해주셨어요 👍 
몇가지 고민거리 남겨드렸으니 확인 부탁드릴게요.

2022-10-13 14:23 UTC, seok-2-o commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        if (menuProduct.getSumOfPrice().compareTo(price) < 0) {
50라인과 중복으로 보이기도 하네요.

2022-10-13 14:23 UTC, seok-2-o commented on src/main/java/kitchenpos/menus/tobe/domain/Product.java
> +class Product {
상품의 가격만 가지고 있으면 될까요?
메뉴를 진열한다고 생각하면 어떤까요?

2022-10-13 14:23 UTC, seok-2-o commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +class DisplayedName {
패키지만 다르고 각 도메인에서 같은 이름을 사용하는군요.

멀티모듈을 염두하신걸까요?

2022-10-13 23:05 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/DisplayedName.java
> +class DisplayedName {
같은 이름이라도 도메인 별로 다른 역할을 할 수 있기 때문에 public을 제거 했습니다.

2022-10-13 23:12 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        if (menuProduct.getSumOfPrice().compareTo(price) < 0) {
getSumOfPrice 메서드는 getter라기 보다는 상품의 합을 가져오는 메서드 입니다.
주신 피드백처럼 getter와 혼동 할 여지가 있어 calculate와 같은 메서드 이름을 고려 했지만,
public 메서드의 이름은 수신자(이 경우엔 Menu) 입장에서 고려되야 한다고 생각했기 때문에 명시적으로 get 이라는 메서드 이름을 사용하게 되었습니다.
이 부분은 저도 고민했던 부분이라 언급해주셔서 감사합니다.
---
50라인의 메소드의 경우 예외를 던지고 있습니다.
사용자 입장에서 상품을 전시 상태로 만들고 싶을때는 가격을 변경하도록 해야합니다.
그러기 위해서는 예외를 던지는 것이 맞다고 판단했습니다.

2022-10-13 23:13 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    private void decideDisplay(final MenuProduct menuProduct, final Price price) {
생성자에서 매개변수로 받고 있는 부분이라 해당 인스턴스 (this)로 접근할 수 없는 것 같습니다.
혹시 다른 좋은 방법이 있을까요?

2022-10-13 23:15 UTC, wenodev commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +class DisplayedName {
3단계 시작전에 멀티모듈을 적용하려고 생각 중이긴 했습니다.
하지만 멀티모듈이 아니더라도 package로 도메인을 나누어 같은 이름을 사용해도 될 것 같은데, 이 부분 어떻게 생각하시나요?

2022-10-14 02:29 UTC, seok-2-o commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        if (menuProduct.getSumOfPrice().compareTo(price) < 0) {
제가 드린 피드백은 판별식을 아예 안으로 넣을 수 있지 않을까에 대한 질문입니다.

morethan 이나 lessthan 같은 함수로서요

2022-10-14 02:31 UTC, seok-2-o commented on src/main/java/kitchenpos/menus/tobe/domain/DisplayedName.java
> +class DisplayedName {
말씅하신 부분이 잘 이해가되지 않는데 자세하게 설명해주실수 있으신가요?

2022-10-14 02:33 UTC, seok-2-o commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +class DisplayedName {
개인적인 경험으로 패키지로 구분하는것도 좋지만 명시적으로 접두어를 두는것이 유지보수 측면과 특히 협업관점에서 좋다고 생각합니다.

List 인터페이스를 가끔 다른 패키지를 가져와서 나중에 문제가 생긴 경험이 있네요

2022-10-14 02:34 UTC, seok-2-o commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    private void decideDisplay(final MenuProduct menuProduct, final Price price) {
이부분은 제가 잘못본것 같네요

2022-10-17 11:19 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/DisplayedName.java
> +class DisplayedName {
https://github.com/next-step/ddd-tactical-design/pull/156#discussion_r994713963
여기 있는 부분과 겹치는 내용 같습니다!
디폴트 접근 제어자를 이용하게 되면 패키지 단위로 경계가 생긴다는 의견이였습니다.
하지만 이렇게 되면 패키지 내부에서 사용할 때 큰 불편함이 있다는 것을 저 당시에는 인지하지 못한 것 같습니다.

결과적으로는 public접근제어자를 사용하고 혼동의 여지가 있다면 접두어를 붙이면 된다는 것을 알게 되었습니다.
감사합니다.

2022-10-17 11:31 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        if (menuProduct.getSumOfPrice().compareTo(price) < 0) {
앗 네네
MenuProduct가 할 일이라는 피드백이였군요 ㅜㅜ 
좋은 리뷰 감사드립니다!!

2022-10-20 12:11 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/Product.java
> +class Product {
이 부분은 도메인끼리 의존하는 방향으로 변경하였습니다.
의존하는것이 항상 좋지는 않지만 이번 단계에서는 의존을 하고 다음 단계에서 의존 방향에 따라 리팩터링을 해보면 좋다고 생각했습니다.

2022-10-20 12:13 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/Product.java
> +class Product {
vo라는 패키지를 넣어 구분하는 방향으로 변경했습니다!

2022-10-20 12:14 UTC, wenodev commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +class DisplayedName {
좋은의견 감사드립니다!!
저도 이부부은 도메인 부분만 리팩터링 하다보니 느끼지 못했습니다!!

컨트롤러, 서비스 영역을 리팩터링하며 public으로 만들고 필요하다면 접두어를 두는게 좋다는 것을 알게 되었습니다

2022-10-20 14:35 UTC, seok-2-o approved these changes
피드백반영잘해주셨습니다.
몇가지 소소한 피드백 남겨드렸습니다. 확인 부탁드릴게요

이어서 다음 미션진행해주세요.

2022-10-20 14:35 UTC, seok-2-o commented on src/main/java/kitchenpos/common/vo/Price.java
> +    }
관례상 오버라이드함수들을 최하단에 위치시키도록 하는게 좋을것 같아요.

2022-10-20 14:35 UTC, seok-2-o commented on src/main/java/kitchenpos/eatinorders/application/OrderService.java
>              for (final OrderLineItem orderLineItem : order.getOrderLineItems()) {
기본적으로 넥스트스텝에서 모든 과정은 들여쓰기를 1번으로 제한하고 있습니다.
이번 과제에서 수정범위는 아니지만 리펙토링을 진행하신만큼 개선해보면 어떤까요?

2022-10-20 14:35 UTC, seok-2-o commented on src/main/java/kitchenpos/eatinorders/application/OrderService.java
> +                        .getPrice()
조금 어색해보이네요

2022-10-20 14:35 UTC, seok-2-o commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    }
들여쓰기는 한번만 사용할 수 있도록 리페토링할 수 있을까요?

2022-10-20 14:35 UTC, merged

2022-10-22 04:01 UTC, wenodev commented on src/main/java/kitchenpos/eatinorders/application/OrderService.java
> +                        .getPrice()
3단계에서 어색한 부분 수정해보겠습니다!!

2022-10-22 04:01 UTC, wenodev commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    }
넵!!