Step3: 매장 주문 리팩토링
next-step/ddd-tactical-design pull request #164
Opened 2022-10-17 17:16 UTC by imcool2551

안녕하세요 시훈님. 3단계 리뷰 잘 부탁드립니다!

테이블, 프로세스까지 분리가 완료된 환경이 아닌 모놀리틱 환경에서 컨텍스트를 나누려다 보니 의문사항이 생겼습니다. 혹시 컨텍스트간 요구 사항이 다를 경우 하나의 테이블을 여러 엔티티로 매핑해서 사용하기도 하나요?  

매장 주문, 포장 주문, 배송 주문이 공통 속성도 있고 물리적으로 같은 테이블을 사용하지만 각각 주문 진행 과정이 조금씩 다르다보니 여러 엔티티로 매핑하는 방향으로 결정하고 `AbstractOrder`에 공통 속성+행위를 만들고 각 컨텍스트에서 이를 상속받는 하위 엔티티를 만들었습니다.

이 외에도 아래와 같은 방법도 있을 것 같습니다. 

*  상위 엔티티 없이 별도의 엔티티로 구현하는 방법 
* 하나의 엔티티로 모든 컬럼을 매핑하고 각 컨텍스트에서 이를 래핑(컴포지션)한 POJO로 사용하는 방법

첫 번째는 중복이 심해질 것 같아서 보류했고, 두 번째는 주문 진행과정에 따라 매핑하는 enum값이 다르기도 하고 하나의 엔티티로 모든 컨텍스트의 요구 사항을 충족하지 못할 것 같아서 보류했습니다. 시훈님의 의견을 주시면 감사하겠습니다!

2022-10-19 15:15 UTC, sihoony commented
> 안녕하세요 시훈님. 3단계 리뷰 잘 부탁드립니다!
> 
> 테이블, 프로세스까지 분리가 완료된 환경이 아닌 모놀리틱 환경에서 컨텍스트를 나누려다 보니 의문사항이 생겼습니다. 혹시 컨텍스트간 요구 사항이 다를 경우 하나의 테이블을 여러 엔티티로 매핑해서 사용하기도 하나요?

강의 자료를 참고하시면 좋을 것 같아요. https://edu.nextstep.camp/s/esIIFotx/ls/BOhJqxcI
`하위 도메인마다 같은 용어라도 의미가 다르고 같은 대상이라도 지칭하는 용어가 다를 수 있기 때문에 한 개의 모델로 모든 하위 도메인을 표현하려는 시도는 올바른 방법이 아니며 표현할 수도 없다.`
추가로 컨텍스트가 다르다면 Upstream/Downstream에 따라 어느 컨텍스트에서는 오너쉽을 갖고 API를 제공하고 어느 컨텍스트는 클라이언트가 되서 제공되는 API의 사용하는 것이 좋을 것 같네요^^

- https://happycloud-lee.tistory.com/m/94

> 매장 주문, 포장 주문, 배송 주문이 공통 속성도 있고 물리적으로 같은 테이블을 사용하지만 각각 주문 진행 과정이 조금씩 다르다보니 여러 엔티티로 매핑하는 방향으로 결정하고 `AbstractOrder`에 공통 속성+행위를 만들고 각 컨텍스트에서 이를 상속받는 하위 엔티티를 만들었습니다.
> 
> 이 외에도 아래와 같은 방법도 있을 것 같습니다.
> 
> * 상위 엔티티 없이 별도의 엔티티로 구현하는 방법
> * 하나의 엔티티로 모든 컬럼을 매핑하고 각 컨텍스트에서 이를 래핑(컴포지션)한 POJO로 사용하는 방법
> 
> 첫 번째는 중복이 심해질 것 같아서 보류했고, 두 번째는 주문 진행과정에 따라 매핑하는 enum값이 다르기도 하고 하나의 엔티티로 모든 컨텍스트의 요구 사항을 충족하지 못할 것 같아서 보류했습니다. 시훈님의 의견을 주시면 감사하겠습니다!

2가지 경우 중 하나를 고르게 된다면, 2번째 방법으로 진행할 것 같습니다. 1번째 방식의 경우 변경에 대해서 취약한 엔티티로 구현될 가능성이 높아 보입니다. 2번째를 고른 이유는 관점에 따라서 다르게 해석해야하는 부분이 필요하다 생각합니다. 다만, 미션의 Order의 경우 Type에 따라서 상태변화만 다르다고 생각이 되는데, 어떻게 생각하시는 궁금하세뇽~^^

2022-10-19 15:16 UTC, sihoony requested changes
3단계 미션 잘 구현해 주셨습니다. 👍 
몇가지 코멘트와 답변을 남겼으니 확인해주세요~^^

즐거운 하루 되세요! 😄

2022-10-24 05:28 UTC, imcool2551 commented
| 미션의 Order의 경우 Type에 따라서 상태변화만 다르다고 생각이 되는데, 어떻게 생각하시는 궁금하세뇽~^^

상태 변화의 경우 DELIVERING, DELIVERED 와 같이 배송 주문에서만 사용되는 상태들은 매장 주문, 포장 주문 컨텍스트에서는 사용되지 않기 때문에 컨텍스트 각각에 맞는 상태를 별도로 매핑했습니다!

2022-10-30 14:10 UTC, sihoony approved these changes
리뷰가 늦어서 죄송합니다. 🙏 
피드백 잘 반영해주셨고, 간단한 코멘트를 남겼으니 확인해주세요.
그동안 고생 하셨습니다! 즐거운 하루 되세요! 😄

2022-10-30 14:10 UTC, sihoony commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/OrderPolicy.java
> +    private OrderLineItem findMatchingOrderLineItem(List<OrderLineItem> orderLineItems, Menu menu) {
`List<OrderLineItem>`를 일급객체로 활용한다면 조금더 보기 좋은 코드가 될 것 같네요~^^

2022-10-30 14:10 UTC, merged