1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #166
Opened 2022-10-19 17:15 UTC by chr0m3

1단계 완료했습니다.

이전에 진행했던 코드를 가져와 그곳에서부터 시작했습니다.

2022-10-19 17:17 UTC, chr0m3 commented on src/main/java/kitchenpos/common/profanitydetect/infra/ProfanityDetectService.java
> +public interface ProfanityDetectService {
도메인 입장에서는 어떻게 또는 어떤 것을 사용해 비속어를 검사하는지, 즉 구현을 알 필요가 없으므로 `PurgomalumClient`를 `ProfanityDetectService`로 변경했습니다.

2022-10-19 17:19 UTC, chr0m3 commented on src/main/java/kitchenpos/common/profanitydetect/infra/ProfanityDetectService.java
> +    boolean profanityIn(String text);
`profanityIn("some text");`와 같이 쓰면 마치 자연어인 것처럼 자연스럽게 읽을 수 있을 것 같습니다.

2022-10-19 17:22 UTC, chr0m3 commented on src/main/java/kitchenpos/common/profanity/domain/ProfanityDetectService.java
> +package kitchenpos.common.profanity.domain;
도메인이 인프라에 대한 의존성을 갖지 않도록 하기 위해 `ProfanityDetectService` 인터페이스는 도메인에 위치해야 할 것 같습니다.

2022-10-19 17:24 UTC, chr0m3 commented on src/main/java/kitchenpos/common/profanity/infra/DefaultPurgomalumClient.java
> +    private static final String PURGOMALUM_ENDPOINT = "https://www.purgomalum.com/service/containsprofanity";
상수로 분리해주었습니다

2022-10-19 17:29 UTC, chr0m3 commented on src/main/java/kitchenpos/common/name/Name.java
> +public class Name {
키친포스에서 사용되는 이름을 나타내기 위한 VO입니다.

초기 구현에서는 어떤 이름인지에 따라 비속어 포함 여부를 검사하기도 하고 검사하지 않기도 하는 등 이름에 대한 정책이 제각각이었습니다.
그러나 키친포스에서 사용되는 이름에 대해 모두 동일한 정책을 적용해도 문제가 될 여지가 없다고 판단되며(적어도 현재로서는) 오히려 그렇게 하는게 더 합당하다고 판단했습니다.
이런 이유에서 이전 미션에서는 키친포스에서 사용되는 이름에 대해 동일한 정책을 적용하도록 모델링했고, 이번 미션에서 그에 따라 구현했습니다.

2022-10-19 17:31 UTC, chr0m3 commented on src/main/java/kitchenpos/common/name/NameFactory.java
> +public class NameFactory {
`Name` VO가 `ProfanityDetectService`에 대해 의존하며 이를 사용해 비속어를 검사하게 되는 형태는 부자연스럽다고 생각했습니다.
그래서 `Name` VO를 생성하기 위한 `NameFactory`를 만들었습니다.

이름에 대한 다른 정책 - 이름은 비어있지 않아야 한다 - 은 그대로 `Name` VO의 생성자에 두어도 되었지만 이름에 대한 정책은 `NameFactory`에 모아두었을 때 더 응집성이 있다고 판단했습니다.

2022-10-19 17:39 UTC, chr0m3 commented on src/main/java/kitchenpos/product/tobe/infra/jpa/ProductEntity.java
> +class ProductEntity {
Product가 DB에 저장되는 형식을 담고 있습니다.

2022-10-19 17:41 UTC, chr0m3 commented on src/main/java/kitchenpos/product/tobe/domain/repository/ProductRepository.java
> +package kitchenpos.product.tobe.domain.repository;
마찬가지로 도메인이 인프라에 의존하지 않도록 하기 위해 이 인터페이스도 도메인에 위치합니다.
도메인은 데이터가 실제로 어떤 기술을 사용해 어떻게 처리되는지 전혀 알 필요가 없게 되므로 도메인을 순수하게 유지할 수 있습니다.

2022-10-19 17:44 UTC, chr0m3 commented on src/main/java/kitchenpos/product/tobe/infra/jpa/JpaProductDao.java
> +interface JpaProductDao extends JpaRepository<ProductEntity, UUID> {
DB 테이블과 1:1로 대응되는 DAO입니다.

2022-10-19 17:46 UTC, chr0m3 commented on src/main/java/kitchenpos/product/application/ProductService.java
> -    private final ProfanityDetectService profanityDetectService;
상품 컨텍스트는 외부의 메뉴 컨텍스트나 비속어 검사 서비스에 더이상 의존하지 않습니다.

2022-10-19 17:47 UTC, chr0m3 commented on src/main/java/kitchenpos/product/application/ProductService.java
> -        if (Objects.isNull(price) || price.compareTo(BigDecimal.ZERO) < 0) {
`Price` VO가 가격에 대한 정책을 가지고 있으므로 더이상 가격이 음수인지 검사하지 않아도 됩니다. 즉, 상품은 가격에 대한 세부 정책을 검사하는 책임을 덜게 됩니다.

2022-10-19 17:47 UTC, chr0m3 commented on src/main/java/kitchenpos/product/application/ProductService.java
> -        if (Objects.isNull(name) || profanityDetectService.profanityIn(name)) {
마찬가지로 상품은 이름 정책을 검사하는 책임도 덜게 됩니다.

2022-10-19 17:49 UTC, chr0m3 commented on src/main/java/kitchenpos/product/application/ProductService.java
> -        }
상품 서비스가 메뉴의 노출 정책에 대한 지식을 가지고, 메뉴의 노출 상태를 변경하는 책임까지 가지고 있었습니다.

2022-10-19 17:52 UTC, chr0m3 commented on src/main/java/kitchenpos/product/application/ProductService.java
> +        // TODO: 메뉴 서비스에 상품 가격이 변경되었음을 알려 메뉴의 노출 여부가 함께 업데이트될 수 있도록 한다.
메뉴 서비스에 상품 가격이 변경되었음을 알립니다. 상품 가격이 변경되었다는 이벤트를 수신한 메뉴 서비스는 자신이 알고 있는 정책에 따라 적절한 처리를 하게 될 것입니다.

2022-10-21 13:12 UTC, sah3122 requested changes
1단계 미션 구현 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요 !

2022-10-21 23:39 UTC, chr0m3 commented on src/main/java/kitchenpos/product/application/ProductService.java
> +        }
Controller에서 별도의 DTO가 아닌 `Product`를 직접 전달받기 때문에 `name`은 `String`이 아닌 `Name` 타입이고, 그렇다면 보장될 수 있지 않을까요?

2022-10-21 23:41 UTC, chr0m3 commented on src/main/java/kitchenpos/product/tobe/domain/entity/Product.java
> +public class Product {
음.. 어떤 부분일까요..?

2022-10-22 00:02 UTC, chr0m3 commented on src/main/java/kitchenpos/common/name/NameFactory.java
> +public class NameFactory {
넵 그렇게 되어야 한다고 생각합니다. 그리고 실제로 저도 모르게 무의식중에 `Name`의 생성자를 직접 사용한 부분이 있네요.

903de21de9b413f42187e71692c854108cca76f5

2022-10-22 00:35 UTC, chr0m3 commented on src/main/java/kitchenpos/common/profanity/infra/DefaultPurgomalumClient.java
> +    public boolean profanityIn(final String text) {
넵 사실 기존 네이밍이 잘못되었다고 생각하지는 않습니다. 이 부분은 개인의 선호, 또는 팀의 스타일에 따를 영역인 것 같습니다.

2022-10-22 01:00 UTC, chr0m3 commented on src/main/java/kitchenpos/common/profanity/domain/ProfanityDetectService.java
> +package kitchenpos.common.profanity.domain;
도메인 모델을 반영하기 위한 인터페이스이고, 실제로 도메인에서 사용되므로 자연스럽게 도메인에 두게 되었는데 말씀하신 것처럼 이 서비스는 application service로 볼 수 있을 것 같네요.
그러나 의존의 방향을 제한하는 것 또한 매우 중요한 부분이라고 생각해서 이 부분은 차차 고민해볼까 합니다.

2022-10-23 04:11 UTC, sah3122 commented on src/main/java/kitchenpos/product/tobe/domain/entity/Product.java
> +public class Product {
상품 가격 변경과 같은 도메인 행위가 Application Layer에 구현되어 있다는 피드백입니다 ㅎㅎ 
도메인의 행위를 도메인에서 구현하여 중요한 비즈니스 로직이 Application Layer에 노출되는 것을 막아보세요 !

2022-10-23 04:12 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
질문주신 부분에 대한 답변을 남겨두었는데 다음 미션을 진행하며 반영해보세요 !

2022-10-23 04:12 UTC, sah3122 commented on src/main/java/kitchenpos/product/application/ProductService.java
> +        }
Product를 직접 전달 받는 경우 Product 내부에 Name VO 는 Factory 를 통한 생성이 불가능해집니다.
앞서 이야기 드린것처럼 Name의 유효성 검사는 Factory 를 통해 진행하고 있기때문에 Controller 에서 전달 받는 Product는 비속어 검사를 진행할수 없어요. 🙏

2022-10-23 04:12 UTC, merged