1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #187
Opened 2023-09-10 03:24 UTC by JungTag

안녕하세요! 이번 미션을 함께 하게 된 윤영택입니다.
잘 부탁드립니다 :)

+ 강사님께서 화요일까지 메뉴 리팩토링 미션도 수행해보길 권장하셔서 step1 리뷰 진행하면서 step2도 병행해도 될 지 함께 문의드립니다!

2023-09-10 06:34 UTC, sihoony commented
step에 따른 리뷰가 달라져서 step2에 대한 미션은 진행하시고, step1이 완료되면 Pull&PR 요청을 주시면 좋을 것 같네요~!

2023-09-10 06:46 UTC, sihoony requested changes
안녕하세요. 영택님,
미션 잘 진행해주셨고, 코멘트를 남겼으니 확인해주세요. 👍 
즐거운 주말 되세요~! 😄

2023-09-10 06:46 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
도메인은 infrastructure가 외부의 어떤 요소를 사용하는지 알수 없도록 관심을 분리해야 된다고 생각하는데, 어떻게 생각하시나요~!?

- https://stylishc.tistory.com/144
- https://learn.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice

2023-09-10 06:46 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    private BigDecimal price;
원시값을 포장해보면 어떨까요~!? Value Object를 만들어 활용하면 여러가지 이점이 생깁니다.
- https://tecoble.techcourse.co.kr/post/2020-05-29-wrap-primitive-type/

2023-09-10 06:46 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    public void changePrice(final BigDecimal price, final List<Menu> menus) {
테스트 코드를 작성해보면 어떨까요~!?

2023-09-10 16:13 UTC, JungTag commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
구현의 편의성을 고려해 domain에 둬도 괜찮다고 타협(?)을 봤는데, 생각해보니 이미 ProductRepository 가 존재해서 의견주신대로 분리했습니다 ㅎㅎ

2023-09-10 16:15 UTC, JungTag commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    private BigDecimal price;
실무에서 Value Object 사용을 잘 안 해봐서 자연스럽게 원시값을 사용했네요! 의견주신대로 적용해봤는데, 부족한 부분이 많아서 의견주시면 검토해보도록 하겠습니다!

2023-09-10 18:21 UTC, sihoony requested changes
안녕하세요. 영택님,
피드백 잘 반영해 주셨고, 코멘트를 추가 했으니 확인해 주세요~! 😄 
즐거운 하루 되세요~!

2023-09-10 18:21 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Name.java
> +    }
👍 👍

2023-09-10 18:21 UTC, sihoony commented on src/test/java/kitchenpos/products/application/ProductServiceTest.java
> +            () -> assertThat(actual.getPrice()).isEqualTo(new Price(expected.getPrice()))
VO에 대한 테스트를 분리해 보면 어떨까요~!?
분리함으로써 테스트의 목적이 명확해질 것 같네요~!^^

2023-09-10 18:21 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Name.java
> +public class Name {
Name이라는 제너릭한 명칭에서 명확한 명칭으로 변경되면 좋을 것 같아요.
메뉴에도 이름, 가격이 존재하여 분리가 되면 좋겠네요~! 😄

2023-09-10 18:21 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Price.java
> +    }
VO는 불변객체이기 때문에 한번 생성 후에는 VO의 value를 유지해야 됩니다.
위와 같은 기능은 불변객체의 의미가 없기 때문에, 일급 컬렉션이나 도메인 로직으로 처리하는게 좋을 것 같아요~! 

즉, VO 생성이후에 value에 대한 새로운 value 할당이나 변경이 없어야하죠.

2023-09-10 18:21 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Price.java
> +public class Price {
Price만의 정책은 없을까요~!?
`상품의 가격은 0원 이상이어야 한다.`를 적용해보면 좋을 것 같네요.

2023-09-10 18:21 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Name.java
> +public class Name {
`상품의 이름에는 비속어가 포함될 수 없다.` 내용도 포함되면 좋을 것 같아요.

2023-09-10 23:35 UTC, JungTag commented on src/main/java/kitchenpos/products/tobe/domain/Price.java
> +public class Price {
엇 해당 로직은 생성자에 넣어두긴 했습니다!!

2023-09-11 02:46 UTC, JungTag commented on src/main/java/kitchenpos/products/tobe/domain/Name.java
> +public class Name {
`비속어가 포함됐는지 여부`를 도메인에 옮기기 위해 2번 조회를 했는데.. 좀 더 나은 방법이 있다면 공유주시면 감사하겠습니다..!!

2023-09-11 04:42 UTC, sihoony approved these changes
안녕하세요. 영택님,
피드백 잘 반영 해주셨습니다. 💯 
다음 미션을 위해서 Merge 하겠습니다.
즐거운 하루 되세요~! 😄

2023-09-11 04:42 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/ProductPrice.java
> +    }
👍 👍

2023-09-11 04:42 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/ProductName.java
> +    }
👍 👍

2023-09-11 04:42 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Price.java
> +public class Price {
제가 보는 뷰에서 잘못 노출되고 있어서 없어보였네요.ㅠㅠ 코드 확인 했습니다!

2023-09-11 04:42 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Name.java
> +public class Name {
비속어 포함 여부를 넘기는 것이 아닌, 비속어를 검사할 수 있는 Interface를 넘겨보면 어떨까요~!?
interface를 전달하고 VO에서 검사할 수 있다면, 책임을 VO에게 명확하게 넘길수 있겠네요~!

2023-09-11 04:42 UTC, merged