🚀 2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #194
Opened 2023-09-11 02:54 UTC by ryuhistory

안녕하세요.
2단계 진행 리뷰 부탁드립니다.

1단계 이후 약간의 변경사항이 있습니다.
1. ProductPrice VO->Price 로 변경
 - Menu와 Price의 가격정책이 현재는 같기에 동일한 vo로 변경 하였습니다. 물론 추후 확장성면에서 다소 단점이 존재하지만 요구사항 기반으로 보면 같은 정책으로 사용해도 무방하다고 생각했습니다.
2. Procut, Menu Name Vo 사용
 - 이것도 Price와 동일한 고민을 하였지만 현재 요구사항으로는 동일하게 사용해도 무방하다고 생각했습니다.

2단계 진행 특이사항
 - MenuProducts 일급 컬렉션 적용
 - MenuGroupValidator 도메인 서비스 추가 후, 메뉴그룹 조회 기능 추가
 - MenuProductGenerator 를 이용한 Product 조회우 MenuProduct 도메인 생성
 

--------------------------------------------

1단계 질문은 제가 내용을 이상하게 적었었네요..해당코드에 다시 질문 작상하겠습니당

2023-09-11 02:58 UTC, ryuhistory commented on src/main/java/kitchenpos/products/domain/tobe/domain/ProductPriceChange.java
>          applicationEventPublisher.publishEvent(productId);
가격만 변경하는 용도의 기능만 있어서
DomainService가 아닌 ApplicationService 개념을 차용하는게 더 맞지 않나??
라는 의구심이 들긴합니다ㅠ

2023-09-13 02:41 UTC, Hyeon9mak requested changes
안녕하세요 제형님, 리뷰가 많이 늦었습니다 🙇‍♂️ 
2단계도 잘 진행해주셨습니다. 1단계 피드백 적용해주신 것도 확인했습니다 👍 

> ProductPrice VO->Price 로 변경
> Procut, Menu Name Vo 사용
> Menu와 Price의 가격정책이 현재는 같기에 동일한 vo로 변경 하였습니다. 물론 추후 확장성면에서 다소 단점이 존재하지만 요구사항 기반으로 보면 같은 정책으로 사용해도 무방하다고 생각했습니다.

👍 넵 충분히 납득되는 이유입니다. 
다만 이번 미션을 통해 제형님께서 도메인간 경계를 명확하게 나누고, 서로 영향을 받지 않도록 하여 추후 유지보수시 타 도메인에 대한 의존을 걱정하지 않는 코드를 작성하는 경험을 얻어가셨으면 해요.
이 부분도 한번 고민해보시면 좋겠습니다 😄 

몇 가지 코멘트 남겼으니 확인해주세요.

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/MenuGroupValidator.java
> +}
클래스 명칭을 보고 기대할 수 있는 행동과 실제 행동이 조금 다른 것 같아요!

2023-09-13 02:41 UTC, Hyeon9mak commented on README.md
> +- [x] 메뉴에 속한 상품의 수량은 0 이상이어야 한다.
이 부분도 리팩터링 해주시나요? 😉

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/MenuProductGenerator.java
> +    }
"상품 존재 유무에 따른 검증을 다른 방식으로 변경해주세요." 라는 요구사항이 동료 개발자에게 전달되었을 때,
동료 개발자가 로직의 위치를 찾는 순서는

1. 패키지 트리에 존재하는 클래스 명칭 확인
2. 메서드 명칭 확인
3. 메서드 내부 로직 확인

라고 생각해요. 현재 로직은 3번에 해당되는 것 같아요.
우선 메서드 명칭으로 로직을 드러내보고, 이를 별개 클래스로도 분리해보는 건 어떨까요?
Validator 클래스가 될 수도 있겠고, 혹은 Products 에 대한 일급 컬렉션을 만들 수도 있겠네요.
그렇게 되면 검증에 대한 테스트 코드를 작성하기도 쉬워질 것 같아요.

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/Name.java
> +    }
😉 👍

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/Name.java
> +    }
단순 값 객체이므로 equals hash code override 로 동등성을 부여해줘도 좋겠네요.

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/Name.java
> +    }
취향과 관련된 질문인데, Name 과 같은 이름에 prefix 를 붙여주는 건 어떻게 생각하실까요?
`MenuName`, `ProductName`
어떤 장단점이 있는지도 고민해보면 재밌을거 같아요 😄

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/Quantity.java
> +    }
생성자와 완전히 동일해보이는데요, 생성자를 막고 정적 팩터리 메서드를 제공하는 이유가 있을까요?

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/ToBeMenu.java
> +    )
역시나 취향 질문으로, FK 설정 필수 여부에 대해 제형님 의견이 궁금합니다.

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/ToBeMenuProduct.java
> +
MenuProduct 는 Menu 의 영역에서만 사용되는 객체인데요,
직접적으로 Product 에 대한 의존을 포함하고 있는 것 같아요.
추후 Product 를 변경하고자 할 때 MenuProduct 까지 함께 신경써줘야하겠네요.
Product 를 변경하고자 할 때 Product 를 제외한 다른 패키지는 신경쓰지 않아도 될만한 방법이 있을까요?

2023-09-13 02:41 UTC, Hyeon9mak commented on src/main/java/kitchenpos/products/domain/tobe/domain/ProductPriceChange.java
>          applicationEventPublisher.publishEvent(productId);
제형님께서 생각하시는 domain service 와 application service 의 차이는 무엇일까요?

우선 저는 domain service 는 우리 비즈니스를 수행할 때 어느 한 도메인이 갖기 애매한 행동을 담당해서 도메인끼리 적절히 협력하는 행동을 나타내고자 할 때 사용한다고 생각하고
application service 는 외부 서비스사 API 를 호출한다던지 등 기술적으로 저희 애플리케이션을 지원해주는 역할이라고 생각해요.

2023-09-13 11:17 UTC, ryuhistory commented on src/main/java/kitchenpos/menus/domain/tobe/domain/Quantity.java
> +    }
자주 사용하는 vo들은 정적팩터리메서드를 사용하면
코드의 간결성과 가독성이 올라가서 별다른 로직이 없어도
주로 이렇게 사용하는 편이에요. ( 사실 가독성과 간결성이라는게 어느정도 주관이 개입되는 부분도 있긴 합니다ㅠ)

2023-09-13 11:18 UTC, ryuhistory commented on src/main/java/kitchenpos/menus/domain/tobe/domain/Name.java
> +    }
pr 요청 코멘트에도 작성하긴 했지만
중복으로 사용되는 vo를 좀 줄여볼까 하는 상황해서 Price, Name을 공용으로 사용 했었어요.
그러나 말씀 하신대로 이번 과정에서는 재사용성보다 도메인간  의존성을 줄이는 방법으로 한번 진행해보는게 좋을거 같네용!
해당부분 다시 수정할게용

2023-09-13 11:39 UTC, ryuhistory commented on src/main/java/kitchenpos/menus/domain/tobe/domain/ToBeMenu.java
> +    )
실무에서는 사실 특별한 이유가 없다면 fk 설정을 하지 않고 있습니다. 어느 시점이 되면 분명 성능 이슈가 발생을 하다보니..ㅠ

그래서 해당 부분도 이러한 고민을 조금(?) 하긴 했는데요.

애그리것으로 나눈다면 menugroup과의 물리적 관계는 끊겨야 하는게 맞다고 보는데
실용적(?)인 측면을 생각하다보니 menu,menuGroup은 어차피 강한결합성을 띄고 있는 도메인인데 굳이 나눌 필요가 있나??
라는 결론에 도달 했었어요.

그런데  아무래도 이번 과정을 생각해본다면 나눠서 다시 진행을 해봐야겠군용

2023-09-13 23:54 UTC, ryuhistory commented on src/main/java/kitchenpos/menus/domain/tobe/domain/ToBeMenuProduct.java
> +
이부분도 추가 수정 했습니당

2023-09-13 23:56 UTC, ryuhistory commented on README.md
> +- [x] 메뉴에 속한 상품의 수량은 0 이상이어야 한다.
이번에 기존에 모델링 항목 변경을 안해줘서 추가 수정했고
요구사항도 tobe구조에 맞게 부분 수정 했습니당!

2023-09-13 23:59 UTC, ryuhistory commented
안녕하세요. 리뷰 다시 요청 드립니다.
많은(?) 코드 수정이 있어서 간략히 큰 변경내용 말씀드립니다.



추가 변경 사항
1. menuGroup 을 별도 애그리것으로 취급하여 , menu에서 MenuGroupId만 참조 하도록 수정
2. MenuProduct에서 Product 참조 하던 부부을, Product의 id와, price만 참조하는 menuProduct 신규 생성
3. 기존에 price change에 대한 publishing 로직만 있던 부분을 menu 리스너 등록 후, menu에서 menuProduct price 가격 변경 및 hide 로직 추가

2023-09-14 13:36 UTC, Hyeon9mak approved these changes
안녕하세요 제형님, 피드백 반영 고생하셨습니다.
다음 단계로 넘어가시면서 다시 확인해주시면 좋을 부분들 코멘트 남겼습니다.
확인해주신 후 3단계 리팩터링과 함께 고민해주세요.

2023-09-14 13:36 UTC, Hyeon9mak commented on README.md
> +- [x] 메뉴에 속한 상품의 수량은 0 이상이어야 한다.
👍 👍

2023-09-14 13:36 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/ToBeMenuProducts.java
> +
메뉴를 등록하고자 할 때 `MenuProduct` 를 무조건 만들 것이고,
상품 존재 유무에 따른 검증 방식을 확인하기 위해서는 `MenuProducts` 를 사용할 수 밖에 없겠네요.
생성자에 검증로직을 포함시켜주신 덕분에 자연스럽게 검증로직을 확인하게 될 것 같아요 👍

2023-09-14 13:36 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/ToBeMenuProducts.java
> +
테스트 코드 작성도 엄청 쉬워졌네요! 하나만 추가해주시면..? 😉 👍

2023-09-14 13:36 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/MenuName.java
> +    }
👍 👍 개인적으로 요즘 느끼는 장점으로는 import 를 할 때 실수를 줄이기도 좋고,
IDE 에서 클래스명을 이용한 탐색(단축키 Cmd + O)을 자주하곤 하는데
이럴 때 prefix 가 있으면 큰 도움이 되는 것 같아요.

2023-09-14 13:36 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/MenuName.java
> +    }
> 자주 사용하는 vo들은 정적팩터리메서드를 사용하면
> 코드의 간결성과 가독성이 올라가서 별다른 로직이 없어도
> 주로 이렇게 사용하는 편이에요. ( 사실 가독성과 간결성이라는게 어느정도 주관이 개입되는 부분도 있긴 합니다ㅠ)

넵넵! 충분히 납득되는 이유입니다. 👍 
제형님께서 어떤 규칙을 갖고 사용하시는 것 같은데, 정확한 의도가 궁금했어요 ㅎㅎ

2023-09-14 13:36 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/ToBeMenu.java
> +
> 실무에서는 사실 특별한 이유가 없다면 fk 설정을 하지 않고 있습니다. 어느 시점이 되면 분명 성능 이슈가 발생을 하다보니..ㅠ
>
> 그래서 해당 부분도 이러한 고민을 조금(?) 하긴 했는데요.
>
> 애그리것으로 나눈다면 menugroup과의 물리적 관계는 끊겨야 하는게 맞다고 보는데
> 실용적(?)인 측면을 생각하다보니 menu,menuGroup은 어차피 강한결합성을 띄고 있는 도메인인데 굳이 나눌 필요가 있나??
> 라는 결론에 도달 했었어요.

오... 👍 👍 👍 👍 실용적인 측면을 생각하셨다는 부분이 너무 멋진거 같습니다.
말씀대로 MenuGroup 은 개별적으로 대단한 복잡도를 띄고있지 않고, Menu 와 굉장히 강한 연관성을 가지고 있죠!!
분명히 생명주기가 다른 두 도메인이지만, Menu 가 항상 MenuGroup 을 필요로 하는..
이런 경우엔 Menu 와 MenuGroup 이 서로에 대한 의존을 가져도 좋은 것 같아요.

2023-09-14 13:36 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/MenuPrice.java
> +import kitchenpos.products.domain.tobe.domain.Currency;
menu 도메인 내부에 product 의 의존이 아직 남아있네요! 요것까지만 해결이 되면 좋겠어요 👍

2023-09-14 13:36 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/domain/tobe/domain/MenuDisplayListener.java
> +    }
`ProductPriceChangeEvent` 에서 상품 ID 에 대한 원시값과, 변경된 가격에 대한 원시값만 알게되면 menu 에서 product 에 대한 의존이 최소화 될 수 있겠어요.

사실 저는 이벤트로 데이터를 주고받을 땐 이벤트 시점의 변경된 값(가격)을 함께 전달하기보다 이벤트 대상을 식별할 수 있는 ID 만 전달해주고, 이벤트 처리기에서 해당 ID 로 정보를 조회하여 다음 행동을 결정하는게 가장 이상적이라고 생각하는데요, 그렇게 하기 위해선 현재 menu 에서 product 를 의존할 수 밖에 없게 되는 것 같아요.

이 문제 상황을 타파하기 위한 방법으로 [부패 방지 계층](https://junhyunny.github.io/architecture/pattern/anti-corruption-layer-pattern/)을 두는 방법도 있겠는데, 이 부분은 다음 미션을 진행하실 때 고민해보셔도 좋겠어요 😄

2023-09-14 13:37 UTC, merged