🚀 3단계 - 리팩터링(매장 식사 주문)
next-step/ddd-tactical-design pull request #202
Opened 2023-09-12 08:35 UTC by parkjun5

안녕하세요! 리펙터링 3단계 매장 식사 주문 리펙토링하고 리뷰 신청합니다.

매장 식사 주문을 리펙토링하면서 아예 배달, 포장컨텍스트와 분리하고 진행한다는 생각으로 진행하였습니다.

그리고 2단계에서 마지막에 리뷰받은 interface를 넘겨받는 것과 강결합 부분도 수정해보았습니다!

리뷰 잘 부탁드립니다!

2023-09-13 23:31 UTC, serverwizard requested changes
매장식사 주문 리팩토링 잘해주셨네요 👍 

몇 가지 고민해 볼 만한 코멘트 남겨뒀는데, 확인 부탁드릴게요!

그럼 오늘 하루도 좋은 하루되세요 :)

2023-09-13 23:31 UTC, serverwizard commented on src/main/java/kitchenpos/apply/order/eatinorders/tobe/domain/OrderLineItems.java
> +public class OrderLineItems extends ValueObject {
일급 컬렉션 👍

2023-09-13 23:31 UTC, serverwizard commented on src/main/java/kitchenpos/apply/menus/tobe/domain/MenuName.java
> +        if (!StringUtils.hasText(name) || purgomalumClient.containsProfanity(name)) {
👍

2023-09-13 23:31 UTC, serverwizard commented on src/main/java/kitchenpos/apply/menus/tobe/application/DefaultMenuPriceChecker.java
> +public class DefaultMenuPriceChecker implements MenuPriceChecker {
도메인 정책(로직)을 가진 서비스로 보이는데, `application 서비스`가 아닌 `domain 서비스`라고 볼 수는 없을까요?
필요한 도메인을 사전에 `application 서비스`에서 조회한 다음 인자로 전달 받으면, 상태도 안가지게 할 수도 있을 것 같아서요

2023-09-14 23:53 UTC, parkjun5 commented on src/main/java/kitchenpos/apply/order/deliveryorders/infra/KitchenridersClient.java
> +package kitchenpos.apply.order.deliveryorders.infra;
아하 배달 주문쪽을 확인하지 못하였네요!

도메인에 있는 것이 자연스러운 것 같습니다

2023-09-15 01:10 UTC, parkjun5 commented on src/main/java/kitchenpos/apply/menus/tobe/application/DefaultMenuPriceChecker.java
> +public class DefaultMenuPriceChecker implements MenuPriceChecker {
속성을 안가지고 코틀린의 오브젝트처럼 사용할 수 도 있겠네요

그리고 계산하는 부분 검증하는 부분을 클래스로 나누면 좀더 좋을 것 같아요

2023-09-15 14:14 UTC, serverwizard approved these changes
피드백 반영해서 매장 식사 주문 리팩토링 잘해주셨네요 💯  
그만 머지하도록 하겠습니다.

그럼 마지막까지 화이팅하세요 👍

2023-09-15 14:14 UTC, serverwizard commented on src/main/java/kitchenpos/support/domain/ValueObject.java
> +public abstract class ValueObject {
VO를 위한 equals and hashCode 👍

2023-09-15 14:14 UTC, serverwizard commented on src/main/java/kitchenpos/apply/order/eatinorders/tobe/application/OrderTableService.java
> +        orderTable.clear();
객체에게 메시지 전달하여 작업 위임 👍

2023-09-15 14:14 UTC, merged