refactor: Package Product refactoring
next-step/ddd-tactical-design pull request #205
Opened 2023-09-12 14:02 UTC by jaejeong1

Product 패키지를 tobe 아래에 리팩토링하고, 테스트 코드를 작성하였습니다.

2023-09-13 09:06 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 참고 부탁드립니다.

2023-09-13 09:06 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/domain/Price.java
> +public class Price {
Embeddable로 Value Object를 잘 추출해주셨네요.  👍

2023-09-13 09:06 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +                .orElseThrow(NoSuchElementException::new);
NoSuchElementException이 발생하면 어떤 에러 응답이 나가게 될까요?

이와 관련해서 RestControllerAdvice 등으로 처리해줄 필요는 없을까요?

2023-09-13 09:06 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +        this.name = new DisplayedName(name, purgomalumClient);
Product 엔티티가 PurgomalumClient의 참조를 가지게 되었는데요.

DisplayedName이 purgomalumClient를 받아서 검증하는 역할을 수행하므로 Product 엔티티는 DisplayedName만 전달받으면 되지 않을까요?

2023-09-13 09:06 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/ui/ProductRestController.java
> +    }
컨트롤러 레이어의 요청, 응답에 엔티티가 노출되지 않도록 잘 해주셨네요 👍

2023-09-13 09:06 UTC, kyucumber commented on src/test/java/kitchenpos/products/tobe/application/InMemoryProductRepository.java
> +public class InMemoryProductRepository implements ProductRepository {
Fake와 InMemory 두가지 용어를 사용해주셨는데요. 두 테스트 목적을 위한 클래스는 모두 동일하게 단순화하여 구현한 객체로 보이는데 Fake로 용어를 통일하면 어떨까요?

2023-09-13 09:06 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    private final MenuRepository menuRepository;
상품 컨텍스트 내부에서 메뉴와 관련된 참조가 사용되고 있네요. 

컨텍스트 간 참조가 발생하는 부분에 대해 어떻게 생각하시나요? 그리고 혹시 메뉴 컨텍스트가 이후에 다른 레파지토리로 분리되거나 다른 팀으로 역할이 넘겨질수도 있을까요? 그 경우 코드의 변경이 발생하면 유연하게 대처할 수 있을까요? 

이렇게 다른 컨텍스트의 참조를 가지는 경우 외부 컨텍스트로부터 도메인을 보호하기 위해서 anticorruption layer를 두곤 합니다. 이번 미션에서 꼭 해당 레이어를 둘 필요는 없지만 관련해서도 한번 고민 및 학습을 해보시면 좋겠네요.

2023-09-13 12:34 UTC, jaejeong1 commented
@kyucumber 와우... 너무 좋은 퀄리티의 리뷰네요. 감사합니다! 하나씩 꼼꼼히 읽어보고 보완해보겠습니다!!

2023-09-15 15:41 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +            }
넵! Setter 대신 ApplicationEvent를 발행하도록 변경하였습니다.

2023-09-16 04:37 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +public interface JpaProductRepository extends ProductRepository, JpaRepository<Product, UUID> {
RDB에 의존하고 있기 때문에, infra로 빼주는게 맞는것같군요... 분리진행했습니다!

2023-09-16 05:46 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +            throw new IllegalArgumentException();
네, 운영 모니터링 시 더 직관적이고 빠르게 원인 파악할 수 있도록 커스텀 예외로 적절하게 표현해보았습니다!

2023-09-16 06:45 UTC, jaejeong1 commented on src/test/java/kitchenpos/products/tobe/application/InMemoryProductRepository.java
> +public class InMemoryProductRepository implements ProductRepository {
네! 말씀대로 둘다 FakeObject 목적이 맞습니다. Fake로 용어 통일해보겠습니다~!

2023-09-16 07:02 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +        this.name = new DisplayedName(name, purgomalumClient);
맞네요... 굳이 Product에서 DisplayedName을 생성하는 방법에 대해선 몰라도 되겠군요...
감사합니다. 수정하였습니다!

2023-09-16 07:05 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +                .orElseThrow(NoSuchElementException::new);
Service 단에서 발생하는 에외이기 때문에 AdviceController로 예외에 대한 관리가 필요하겠군요!
해당 건은 다음 메뉴 리팩토링때 한번에 적용해도 괜찮을까요??

2023-09-16 07:07 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    private final MenuRepository menuRepository;
기존 구현 시 서비스 레이어에서 서로 다른 레퍼지토리를 합성 패턴으로 참조해서 사용하곤 했었습니다.

다만, 말씀주신대로 메뉴 레퍼지토리가 분리되거나, 변경될 시 유연하게 대처할 수 있느냐에 대답은 No 인것 같습니다.
딱히, 기술적으로 어떻게 대응하면 좋을지 모르고있었기 때문에 관습처럼 사용하고 있었는데, 이번주 수업에서 배운 안티커럽션 레이어로 대처해볼 수 있을 것 같습니다. 

해당 건 관련해서도 학습 및 구현해보도록 하겠습니다.
양질의 리뷰 감사합니다 :)

2023-09-16 07:09 UTC, jaejeong1 reviewed
피드백 반영하였습니다.

2023-09-17 10:57 UTC, kyucumber requested changes
안녕하세요

의도와 다르게 반영된 부분이 있어 몇가지 추가 코멘트 남겨두었으니 참고 부탁드립니다. 다시 요청해주시면 머지하도록 할게요.

2023-09-17 10:57 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedNameValidateException.java
> +public class DisplayedNameValidateException extends IllegalArgumentException {
커스텀 예외를 만들어주셨는데요. 이렇게 케이스별로 커스텀 예외를 다 만들게 되면 너무 많은 커스텀 예외를 만들어야 합니다.

가급적 직접 정의하기 보다는 최대한 표준 라이브러리에 존재하는 오류를 사용하는 것이 좋을 것 같습니다. 표준 라이브러리의 예외는 많은 개발자가 알고 있으므로 널리 알려진 요소를 재사용하면 다른 사람들이 API를 더 쉽게 배우고 이해할 수 있습니다.

예외가 이미 구현된 예외 처리 구문과 겹쳐 예외를 구분해야 하거나 하는 경우가 아니라면 표준 예외(IllegalArgumentException, IllegalStateException 등 RuntimeException을 상속하는 예외)를 사용하는건 어떨까요?

2023-09-17 10:57 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +        menus.forEach(menu -> menu.changePrice(request.getPrice()));
> 넵! Setter 대신 ApplicationEvent를 발행하도록 변경하였습니다.

리팩터링 잘 해주셨는데요, 의도와 조금 다른 부분이 있는 것 같아 추가 코멘트 남깁니다. 현재는 ProductRepository를 이용해 데이터를 조회하고 menu 도메인의 메서드를 호출해 처리하고 있는데요.

ApplicationEventPublisher를 이용해 이벤트를 발행하는 형태로 처리해보시라는 의도로 코멘트를 남겼습니다. 참고 부탁드립니다.

https://velog.io/@jeongmin78/Spring-Boot-ApplicationEventPublisher%EB%A5%BC-%ED%86%B5%ED%95%9C-Event-%EC%B2%98%EB%A6%AC

2023-09-17 10:57 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
Product 도메인 클래스가 RDB 레이어와 연결된 엔티티 역할을 같이 수행하고 있네요. 아래처럼 도메인 클래스를 별도로 두고 사용하는 경우도 많습니다.

- Product(Domain class)
- ProductEntity
- JpaProductRepository<ProductEntity, Long>

변환 등의 보일러플레이트가 많이 생기겠지만 RDB 영역과 도메인을 분리할 수 있다는 장점이 있으니 참고 부탁드려요.

2023-09-17 10:58 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
이 부분은 꼭 반영하실 필요는 없으며 Jpa쪽과 도메인 클래스의 결합을 낮추기 위해 이렇게도 설계할 수 있다. 라고 인지하고 넘어가주셔도 무방할 것 같습니다.

2023-09-17 13:37 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedNameValidateException.java
> +public class DisplayedNameValidateException extends IllegalArgumentException {
네, 이해했습니다. 다시 생각해보니 커스텀 예외로 모두 두면 엄청 많이 만들어야하고, 표준 예외를 최대한 활용하는 방안으로도 가독성을 향상시킬수 있겠군요. 감사합니다!

2023-09-17 14:14 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +        menus.forEach(menu -> menu.changePrice(request.getPrice()));
스프링 애플리케이션 단에서 사용하는 내부 이벤트이군요? kafka같은 외부 이벤트만 알고 사용했었는데, 요런게 있었군요! 감사합니다.

각기 다른 pod에서 동작하거나, 서로 다른 서버 간 이벤트 전달이 필요한 상황이라 외부 이벤트만 사용해왔었는데, 이 경우 
ApplicationEvent 외부 이벤트 대비 어떤 장점이 있을까요?

2023-09-17 14:15 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
현재 Menu를 따로 떼어놓고 Product만 리팩터링 하려니 이상해서, 다음미션에서 요 부분 적용 시도해보고 리뷰받아보겠습니다. 

이 부분에 대해서도 고민이 항상 있었는데, 명쾌한 리뷰네요. 감사합니다!!

2023-09-17 14:16 UTC, jaejeong1 commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
이 경우 Product 도메인을 POJO 클래스로 작성한 후, ProductEntity에서는 이를 상속받아 구현하는 방식이 되는걸까요?

2023-09-17 14:18 UTC, jaejeong1 reviewed
피드백 반영완료하였습니다 :) 
양질의 리뷰 감사합니다!!

2023-09-18 11:57 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +        menus.forEach(menu -> menu.changePrice(request.getPrice()));
> 각기 다른 pod에서 동작하거나, 서로 다른 서버 간 이벤트 전달이 필요한 상황이라 외부 이벤트만 사용해왔었는데, 이 경우
ApplicationEvent 외부 이벤트 대비 어떤 장점이 있을까요?

남겨두신 부분 중에 각기 다른 Pod에 대한 말씀을 해주셨는데요. 구성에 따라 다르겠지만 다른 Pod에서 동작하더라도 실제 바라보는 RDB는 동일할테니 메뉴를 변경하는 부분에는 아무 문제가 없어 ApplicationEvent를 사용해도 문제가 없을 것 같아요.

외부 이벤트 대비 내부 이벤트가 가지는 장점은 불필요하게 카프카와 같은 메시지 브로커를 사용할 필요가 없어 복잡도가 낮다는 장점이 있겠네요.

그리고 이벤트를 사용하는 것과 기존처럼 레파지토리를 사용하는 부분과의 차이를 말씀드리면, 기존처럼 다른 컨텍스트의 레파지토리를 사용하게 되면 product에서 다른 컨텍스트(menu)의 참조를 가지게 되며 컨텍스트간 침범이 발생하게 됩니다. Spring의 ApplicationEvent를 사용하면 이 부분의 결합도를 낮춰 이후 변경에 유연하게 대처할 수 있습니다.

2023-09-18 11:58 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
> 이 경우 Product 도메인을 POJO 클래스로 작성한 후, ProductEntity에서는 이를 상속받아 구현하는 방식이 되는걸까요?

네 말씀하신 형태로도 사용할 수 있을 것 같고, 불필요한 중복 코드가 다소 생기긴 하겠지만 두개가 아예 연관이 없도록 중복 코드를 가지게 만들 수 있을 것 같습니다.

2023-09-18 11:59 UTC, kyucumber commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
엔티티가 변환 등에서 도메인의 참조를 가지는 것은 괜찮지만 상속받으면 결국 결합이 생기기 때문에 유연하게 대처하기 힘들어 상속하거나 하는 형태를 선호하진 않습니다.

2023-09-18 12:00 UTC, kyucumber approved these changes
상품 리팩터링 잘 해주셨습니다.

남겨두신 질문에 답변 남겨두었으니 확인 부탁드려요~

https://github.com/next-step/ddd-tactical-design/pull/205#discussion_r1328614773
https://github.com/next-step/ddd-tactical-design/pull/205#discussion_r1328616411
https://github.com/next-step/ddd-tactical-design/pull/205#discussion_r1328617080

다음 단계 진행을 위해 머지하겠습니다.

2023-09-18 12:00 UTC, merged