Step1: 상품 리팩터링
next-step/ddd-tactical-design pull request #209
Opened 2023-09-14 03:41 UTC by yuhwanwoo

최대한 빠르게 하고 싶었는데,

역시 어렵네요...

이게 맞을까? 라고 생각하는 것들이 많은 것 같아요!

일단 걸리는 부분 중 하나가 
![image](https://github.com/next-step/ddd-tactical-design/assets/22831002/ba45c394-ddca-431f-8cd3-520ea47906ef)
에서 메뉴부분인데 이 부분은 어떤식으로 처리하는게 맞을까요?

항상 리뷰 감사드립니다! 🙇

2023-09-14 17:19 UTC, wlroh commented
환우님 안녕하세요 :)

> 메뉴부분인데 이 부분은 어떤식으로 처리하는게 맞을까요?

이부분은 코멘트 달아두었어요~ 확인부탁드리고 궁금하시거나 고민있으시면 DM 주셔도 돼요!

> 그리고 크게 소리내어 모델링 하기의 경우 merge가 되어 끝난것 같은데 첫번째 주처럼 종료가 되지 않은 것 같은데 확인 부탁드려도 될까요?

조금만 더 기다리시면 첫번째 주처럼 종료되면서 리뷰어 피드백 요청가실거에요 😄

2023-09-14 17:20 UTC, wlroh requested changes
환우님 안녕하세요 :)
이번 미션을 함께할 노웅래입니다.
미션 고생하셨습니다 👍 👍 
코멘트 달았는데요, 확인부탁드려요!

2023-09-14 17:20 UTC, wlroh commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        validateMenuPrice(menus);
이부분이 코멘트 주신 부분이군요!

우선 두가지 이슈가 있어요.
- 상품 컨텍스트에서 관심사 밖인 메뉴가 포함되어 있는 이슈
- 메뉴 컨텍스트에서도 상품컨텍스트를 의존하고 상품컨텍스트에서 메뉴 컨텍스트를 의존하며 양방향 의존하는 이슈

해결 방안으로는 이벤트를 활용하는 방법이 있고,
인터페이스를 이용하는 방법이 있어요.

인터페이스를 활용하는 방안은 아래 링크를 참고하면 좋을 것 같아요 😄 
https://www.youtube.com/watch?v=dJ5C4qRqAgA

추가로, 물리적 결합을 단방향 혹은 끊을 수 있지만 논리적 결합도 같이 고려가 필요해요
논리적 결합도 같이 고민해보시면 좋을 것 같아요

2023-09-14 17:20 UTC, wlroh commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    private ProductName name;
Embedded 👍 👍

2023-09-14 17:20 UTC, wlroh commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    protected Product() {
접근제어자 👍 👍

2023-09-14 17:20 UTC, wlroh commented on src/main/java/kitchenpos/products/tobe/domain/ProductName.java
> +    }
생성자끼리 위치를 묶어주는 것은 어떤가요?

2023-09-14 17:20 UTC, wlroh commented on src/main/java/kitchenpos/products/tobe/domain/ProductPrice.java
> +    }
여기도 같이 확인부탁드려요

2023-09-14 17:20 UTC, wlroh commented on src/main/java/kitchenpos/shared/util/ConvertUtil.java
> +    private static final ObjectMapper objectMapper = new ObjectMapper();
컨버팅하는 Util 성 클래스를 만드렸군요! 👍 👍 
다만, objectMapper 또한 리플렉션을 이용하기때문에 성능이 더 좋은 매핑해주는 Mapstruct 도 있어요 😄 
수정하실 필요는 없고, 보다가 성능 고려하면 Mapstruct 도 추천드리고 싶어서 이야기드려요

2023-09-15 00:20 UTC, hwanwooyu commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        validateMenuPrice(menus);
말씀하신 논리적 결합은 어떤걸 말씀하시는걸까요???

2023-09-15 00:21 UTC, yuhwanwoo commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        validateMenuPrice(menus);
말씀하신 논리적 결합은 어떤걸 말씀하시는걸까요???

2023-09-15 07:42 UTC, yuhwanwoo commented
제이슨께서 첫 강의 때 추천해 주신 강의여서 봐야지 봐야지 했다가 까먹고있었는데
보내주셔서 드디어 영상을 보았습니다...
일단 말씀해주신 방향대로 진행을 해보았는데, 제가 맞게 했는지 확신이 들지 않네요!

피드백 부탁드립니다! 감사합니다! 🙇

2023-09-16 07:46 UTC, wlroh commented
> 그리고 이게 도메인 서비스의 개념일까요?

도메인 서비스라기 보다는 컨텍스트간의 강결합을 줄여주는 것으로 보시면 좋을 것 같아요.
컨텍스트간의 결합을 피할 수는 없다고 생각해요. 그렇지만, 양방향으로 의존하는 것을 단방향으로 의존하도록 바꿔주는 것이 중요하다고 생각하고요.

컨텍스트간의 결합을 낮추기 위해 인터페이스 혹은 이벤트를 활용해볼수도 있을 것 같고요 😄

2023-09-16 07:48 UTC, wlroh approved these changes
환우님 안녕하세요 :)
피드백 잘 반영해주셨습니다 👍 👍 
코멘트 추가한 내용이 있는데요, 다음 미션 진행하시면서 확인부탁드려요!
다음 미션도 화이팅입니다 🔥

2023-09-16 07:48 UTC, wlroh commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        productMenuService.validateMenuPrice(productId);
인터페이스를 통해 단방향으로 의존하도록 잘 반영해주셨네요 👍 👍 
논리적 결합이라는 것은 현재 `메뉴가격 검증` 이라는 메서드명으로 상품컨텍스트에서 자신의 관심사가 아닌 메뉴 대한 내용이 포함되어 있는 것을 이야기하고 싶었어요 
이와 같이 이벤트 방식으로 진행하게 되면 강결합에서 약결합으로 바뀌는데 이벤트의 네이밍에 따라 논리적으로도 강결합이 생길 수 있기때문에,
논리적 결합도 고려가 필요하다는 이야기였습니다 😄

2023-09-16 07:48 UTC, wlroh commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        validateMenuPrice(menus);
논리적 결합 관련해서는 아래 코멘트에 추가해두었습니다 😄

2023-09-16 07:48 UTC, merged