2단계 : 메뉴 리팩토링
next-step/ddd-tactical-design pull request #215
Opened 2023-09-15 13:03 UTC by qotjsry

안녕하세요 리뷰어님
메뉴리팩토링 진행하였습니다.

코멘트 부탁드립니다.

감사합니다.

2023-09-16 01:29 UTC, Hyeon9mak requested changes
안녕하세요 선교님, 메뉴 리팩토링 고생하셨어요.
커밋이 잘못 꼬여서인지 테스트 코드가 전부 삭제된 걸로 보이네요 😱 
다시 테스트를 작성해주시면 확인 후 더 자세히 코드리뷰 진행하겠습니다.

2023-09-16 01:29 UTC, Hyeon9mak commented on src/main/java/kitchenpos/eatinorders/application/OrderService.java
> +//            }
👀 주석으로 변경된 이유가 있을까요?
만약 불필요해진 코드라면 주석을 남겨놓기보다 아예 제거하는 편이 더 좋을 것 같아요.
'이 부분은 왜 주석이지?' 동료 개발자가 고민이 생길거같아요!

2023-09-16 01:29 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/application/MenuGroupService.java
> +        MenuGroup menuGroup = MenuGroup.of(new MenuGroupName(request.getName()));
검증로직이 생성자 내부로 옮겨가면서 간결해졌네요 👍

2023-09-16 01:29 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/application/MenuService.java
>          }
check 라는 명칭을 사용하고 있지만, 반환타입은 boolean 인 것 같아요.
menuProducts.checkEqualsSize 내부에서 throw 를 던져주는 방식은 어떨까요?
또, 적절한 메세지를 남겨서 다음 행동을 결정할 수 있게 해주는 것도 좋겠네요.

2023-09-16 01:29 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    }
꼼꼼한 ID 동등성 부여 👍

2023-09-16 01:29 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/tobe/domain/MenuProduct.java
> +//        }
👀

2023-09-16 01:29 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/tobe/domain/MenuProductQuantity.java
> +    private long quantity;
동등성 부여가 빠진 곳들이 몇 곳 보이는 것 같아요!
각각의 VO 에 동등성 부여가 잘 이루어졌는지 테스트 코드가 추가된다면
혹시나 빠뜨렸는지 바로바로 확인이 가능하겠네요~

2023-09-20 13:42 UTC, qotjsry commented
해당 소스에서 MenuService에 있는 checkMenuPrice 메소드를 ProductPrice를 변경할때 확인을 해서 메뉴를 비 활성화 시켜야 하는데 ProductService에 해당 메소드를 추가 하게 되면 menuService에 대한 의존성이 생기는데 어떻게 풀어야 할까요?

2023-09-22 00:08 UTC, Hyeon9mak approved these changes
안녕하세요 선교님! 메뉴 리팩터링 잘 진행해주셨습니다. 👍 
몇 가지 코멘트 남겼으니 다음 단계를 진행하면서 함께 확인해주세요.

2023-09-22 00:08 UTC, Hyeon9mak commented on src/test/java/kitchenpos/menus/application/MenuServiceTest.java
> +        assertThat(changedMenu.getPrice()).isEqualTo(BigDecimal.valueOf(50_000));
👍 👍 꼼꼼한 테스트 코드 작성

2023-09-22 00:08 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/application/MenuService.java
> +        final List<Menu> menus = menuRepository.findAllByProductId(event.getProductId());
`@TransactionalEventListener` 에 대해서도 알아보면 좋을거 같아요!

2023-09-22 00:08 UTC, Hyeon9mak commented on src/main/java/kitchenpos/menus/application/MenuService.java
> +        final List<Menu> menus = menuRepository.findAllByProductId(event.getProductId());
(개별질문) 만약 이벤트에 따른 동작을 수행하던 중 에러가 발생하면 어떻게 해결할 수 있을까요?

2023-09-22 00:08 UTC, Hyeon9mak commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +        registerEvent(new ProductPriceChangedEvent(id, price));
도메인 계층에서 이벤트 발행 👍 👍 
상품 가격 변경시 이벤트 발행을 실수로 누락하는 일이 없겠네요 👍 
처음 상품 코드를 볼 때도 '상품 가격을 변경하면 무언가 이벤트가 발생하는구나' 이해할 수도 있겠어요 👍

2023-09-22 00:08 UTC, Hyeon9mak commented on src/test/java/kitchenpos/products/application/ProductServiceTest.java
> +        assertThat(events.stream(ProductPriceChangedEvent.class).count()).isEqualTo(1);
이벤트 발행 테스트 👍 
`@DisplayName` 에 무엇을 테스트 하고 싶은건지 더 명확히 드러내줘도 좋겠어요!

2023-09-22 00:09 UTC, merged

2023-09-22 00:22 UTC, qotjsry commented on src/main/java/kitchenpos/menus/application/MenuService.java
> +        final List<Menu> menus = menuRepository.findAllByProductId(event.getProductId());
에러가 발생하고 더이상 동작이 진행되지 않아야 한다면 @EventListner로 작성하고 별개의 트랜잭션으로 동작시키려면 @TransactionalEventListener로 작성해서 진행 시키는거 아닌가요?