1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #216
Opened 2023-09-15 14:44 UTC by HackSung

안녕하세요~
처음으로 이번 미션 PR 올려드립니다.
잘 부탁드리겠습니다. 😄

2023-09-16 18:40 UTC, kyucumber requested changes
상품 리팩터링 잘 해주셨네요.

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-09-16 18:40 UTC, kyucumber commented on src/main/java/kitchenpos/products/domain/Product.java
> +    @Embedded
현재는 엔티티의 역할과 도메인 클래스의 역할을 Product에서 모두 수행하는 것 같은데요. 최근에는 아래처럼 도메인 클래스를 별도로 두고 사용하는 경우도 많습니다.

- Product(Domain class)
- ProductEntity
- JpaOrderRepository<ProductEntity, UUID>

불필요하게 변환하거나 작성해야하는 코드가 많아지긴 하지만 도메인 클래스가 RDB와 관련된 부분과 결합되지 않는다는점에서 장점이 있을 수 있습니다. 참고 부탁드려요.

2023-09-16 18:40 UTC, kyucumber commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        applicationEventPublisher.publishEvent(new ProductEvent(productId));
Product와 Menu의 참조를 이벤트를 이용해 잘 끊여주셨습니다.

이번엔 변경과 관련된 부분이어 이벤트를 통해 처리가 가능했으나, 조회 등이 필요한 경우라면 컨텍스트 간 참조가 발생할 수 있을 것 같습니다. 그 경우 코드의 변경이 발생하면 유연하게 대처할 수 있을까요? 이렇게 다른 컨텍스트의 참조를 가지는 경우 외부 컨텍스트로부터 도메인을 보호하기 위해서 anticorruption layer를 두곤 합니다. 이번 미션에서 꼭 해당 레이어를 둘 필요는 없지만 관련해서도 한번 고민 및 학습을 해보시면 좋겠네요.

2023-09-16 18:40 UTC, kyucumber commented on src/main/java/kitchenpos/products/domain/ProductPrice.java
> +public class ProductPrice {
Value Object에 대한 테스트도 작성해주시면 어떨까요?

2023-09-16 18:40 UTC, merged

2023-09-16 18:43 UTC, kyucumber commented on src/main/java/kitchenpos/products/application/ProductService.java
>              .orElseThrow(NoSuchElementException::new);
NoSuchElementException이 발생하면 어떤 에러 응답이 나가게 될까요?

이와 관련해서 RestControllerAdvice 등으로 처리해줄 필요는 없을까요?

2023-09-17 13:55 UTC, HackSung commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        applicationEventPublisher.publishEvent(new ProductEvent(productId));
말씀하신대로 구체적인 이름으로 Product 이벤트의 명확한 의도를 밝히는게 맞는 것 같습니다.
step2에 반영하겠습니다 😄

2023-09-17 14:13 UTC, HackSung commented on src/main/java/kitchenpos/products/domain/Product.java
> +    @Embedded
그렇지 않아도 얼마전에 읽은 **만들면서 배우는 클릭 아키텍처**라는 책에서 말씀하신 내용을 아래 그림으로 표현하더라구요 
<img width="470" alt="image" src="https://github.com/next-step/ddd-tactical-design/assets/22284112/98704442-89b1-48c2-af2c-cdc242bd1d24">
도메인 엔티티와 JPA엔티티를 분리해야 ORM매핑 애너테이션이 없는, 
영속성 관심사로 오염되지 않은 깨끗한 도메인 모델, 
즉 단일 책임 원칙을 만족할수 있다는 저자의 얘기에 동의는 하면서도 
실용적인 측면에서는 경험상 DB 접근 구현체를 다른 것으로 변경할 일이 없었고
엔티티를 분리해도 거의 비슷한 모델로 개발하게 되지 않을까 하는 생각이 들었습니다.
정답이 있는 건 아니고 양쪽 다 트레이드오프가 있는 것이라 구현하기전에 
상황을 보면서 어느쪽이 맞을지 항상 고민하겠습니다. 😄

2023-09-17 14:19 UTC, HackSung commented on src/main/java/kitchenpos/products/application/ProductService.java
> +        applicationEventPublisher.publishEvent(new ProductEvent(productId));
anticorruption layer라 함은 중간에 인터페이스를 정의하여 단방향으로 참조하게 하는 방식일까요?
가이드 주신대로 해당 부분을 찾아 학습해보겠습니다. 😄

2023-09-17 14:21 UTC, HackSung commented on src/main/java/kitchenpos/products/domain/ProductPrice.java
> +public class ProductPrice {
앗.. legacy 첫 미션에서는 VO테스트 코드 작성을 했었는데 이번 미션에서는 깜빡하고 넘어 갔네요 
step2에 반영하겠습니다. 😄

2023-09-17 14:23 UTC, HackSung commented on src/main/java/kitchenpos/products/application/ProductService.java
>              .orElseThrow(NoSuchElementException::new);
그러고 보니 NoSuchElementException뿐만아니라 IllegalArgumentException등 
Exception의미에 매핑된 http status코드로 변환해서 돌려줘야 할 것 같습니다.
step2에 적용하겠습니다.