2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #218
Opened 2023-09-16 06:39 UTC by koola97620

안녕하세요 리뷰어님. 
이번 미션은 좀 오래걸렸습니다... 커밋단위를 끊으려다 실패해서 한번에 커밋된 것들이 양이 많습니다. 죄송합니다...
변경에 대한 영향이 끝없이 발생해 커밋 단위가 너무 커졌습니다. 

처음부터 레포지토리도 새로 만들어서 진행했으면 커밋단위를 잘 끊었을 수도 있을것 같은데 그렇게 하지 못했습니다.
그래서 진행하다가 다른 패키지에 영향을 주는 객체는 이름에 New를 붙여서 새로 만들어 진행했습니다.
다음 미션땐 처음부터 커밋단위를 잘 신경써서 끊어보겠습니다. 

이번 미션은 커밋단위 때문에 어려웠고, 이전 미션에서 궁금한것들을 잘 답변해주셔서 아직은 더 궁금한것이 없습니다.
피드백 부탁드립니다!
감사합니다!

2023-09-16 15:48 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 확인 부탁 드려요. 🙂

2023-09-16 15:48 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/application/MenuService.java
>      }
보통 application service에서 도메인 객체를 바로 리턴하시나요?

2023-09-16 15:48 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/ui/MenuGroupRestController.java
>      }
보통 응답으로 도메인 모델을 그대로 사용하시나요?

2023-09-16 15:48 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/infra/NewJpaMenuRepository.java
> +}
새로 테이블이 나왔을까요? NewMenu 를 보니 menu 테이블을 그대로 사용하고 있는 것 같아서요. 
https://hudi.blog/dallog-flyway/
https://nextstep-members.slack.com/archives/C05MEQV4695/p1694092291271229
두 링크를 참고해 보시면 좋을 것 같습니다.

2023-09-16 17:27 UTC, koola97620 commented on src/main/java/kitchenpos/menus/application/MenuCreateRequest.java
> +    }
DTO 는 데이터를 전송하는  Object 라 생각합니다~ 
상황에 따라 이러한 기능이 DTO 들어갈 수도 있겠지만... 지금은 DTO 에 없어도 되는 기능 같아요!
밖으로 빼도록 하겠습니다!

2023-09-17 02:36 UTC, koola97620 commented on src/main/java/kitchenpos/menus/application/MenuService.java
> +    }
ProductBC 의존성을 없앴는데 menu.tobe.domain 패키지에서 application.dto 패키지를 의존하고 있네요...ㅠㅠ
dto 패키지를 이동하거나 domain용 dto 를 새로 만들어 application layer 에서 변환 작업을 해주어야 할 것 같은데
일단 dto 패키지를 domain 으로 옮겨봤습니다.   의존성의 방향을 생각하면 그래도 될것 같아서요.
ui 패키지에서 domain 패키지의 dto를 의존하는건 어떻게 생각하시나요?

2023-09-17 02:38 UTC, koola97620 commented on src/main/java/kitchenpos/menus/tobe/domain/MenuProducts.java
> +    }
domain 이 application 패키지를 의존하면 의존 방향이 양방향이 되어 버리네요. 수정했습니다. 위에 댓글과 함께 봐주시면 됩니다.

2023-09-17 02:42 UTC, koola97620 commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenu.java
> +    private NewMenuGroup newMenuGroup;
같은 라이프사이클을 공유하는게 아니라 다른 애그리거트라 생각합니다. 수정하겠습니다!

2023-09-17 03:08 UTC, koola97620 commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenu.java
> +    private NewMenuGroup newMenuGroup;
다시 생각을 좀 해봤습니다...

MenuGroup은 Menu 와 다른 라이프사이클을 지니지만 Menu 가 존재하려면 MenuGroup 이 필요합니다. 
라이프사이클은 다르지만 외래키로 인해 관계를 가지고 있으니 같은 애그리거트라고 봐도 되지 않을까요?? 
같은 애그리거트지만 라이프사이클은 다른...? 혹시 Cascade 를 통해 함께 생성되고 함께 삭제 되는 것만이 같은 애그리거트라고 할 수 있을까요?

Cascade 가 없이 기존 코드처럼 ManyToOne, JoinColumn 을 써서 관계는 가져도 되지 않을까 하는 생각이 갑자기 드네요. 
일단 @JoinColumn 으로 변경했는데 아래와 같은 에러가 나서... @Column 으로 변경해놨습니다.
`Table [menu] contains physical column name [menu_group_id] referred to by multiple logical column names`

2023-09-17 03:28 UTC, koola97620 commented on src/main/java/kitchenpos/menus/application/MenuService.java
>      }
아뇨. 응답 객체를 만들어 반환하는데...
1. 뭘 반환해야 하는지 정해진게 없어서
2. 미션의 범위가 아니지 않을까?  

이런 이유로 리팩터링 안했었던것 같아요 :)  응답 객체 만들어 반환하도록 변경해볼게요!

2023-09-17 03:58 UTC, koola97620 commented on src/main/java/kitchenpos/menus/infra/NewJpaMenuRepository.java
> +}
새로운 테이블 아닙니다 ㅎ 엔티티 이름이 같다고 에러가 나서...  tobe 에 있는 엔티티 이름을 변경한 것 입니다.
Order 에서 기존 Menu 엔티티에 대한 의존성을 가지고 있어서 삭제가 어려우니
일단 새로운 엔티티에 New 를 붙여서 리팩터링 했습니다!

나중에 기존 Menu 엔티티를 삭제할 수 있게 되면 그때 다시 엔티티 이름을 Menu 로 변경하려고 합니다.

2023-09-17 05:55 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenu.java
> +    private NewMenuGroup newMenuGroup;
그렇다면 root entity는 어떤 클래스일까요??

2023-09-17 06:08 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/application/MenuService.java
> +    }
지금은 조금 어색한 것 같아요. request 객체는 보통 http request에 사용 되는데요. 이 부분이 domain의 관심사일까요?

2023-09-17 06:09 UTC, koola97620 commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenu.java
> +    private NewMenuGroup newMenuGroup;
아!. 현재 코드에서 애그리거트 루트는 NewMenu 인데...  NewMenuGroup 도 외부에서 직접 접근이 가능하고 생성이 가능하니 애그리거트 루트가 되는군요.

그러면 다른 애그리거트가 맞겠네요! ㅎ 루트로 생각을 하니 알겠네요 ㅎㅎ 
감사합니다!

2023-09-17 10:48 UTC, koola97620 commented on src/main/java/kitchenpos/menus/application/MenuService.java
> +    }
reqeust에 Menu 를 생성하기 위해 필요한 데이터가 있는 것이니 domain 영역에 있어도 된다고 생각했던것 같아요. 말씀하신대로 http 요청시에도 사용되는 객체이니 domain 과 상관없는 영향이 생길 수도 있겠네요.  domain 영역에 위치 시키는건 올바르지 못한 것 같아요. 메뉴를 생성하는 객체를 새로 생성했는데 이름이 마땅히 떠오르는게 없어서... MenuCreateDto 라고 했습니다ㅠㅠ

2023-09-18 12:35 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 확인 부탁드려요. 🙂

2023-09-18 12:35 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenu.java
> +    }
이 메서드는 꽤나 복잡하지 않나요? `MenuProducts`, `MenuProduct` 에 대한 생성을 분리해 보는 것은 어떨까요? 
`MenuProduct` 의 생성은 `상품`과 `상품 수량` 에 대한 검증을 할 수 있을 것 같아요.
`MenuProducts`는 `MenuProduct`들이 비어 있는지에 대한 검증을 할 수 있을 것 같아요. 
`Menu` 는 `Menu.price` 에 대한 검증과 `Menu.price`과 `MenuProducts` 의 가격에 대한 비교를 검증할 수 있을 것 같아요. 

그리고 검증이 주 생성자에 존재해야 하고 각 팩터리 메서드들은 주 생성자를 사용해야 할 것 같아요. 
해당 메서드 말고 다른 생성에 대한 메서드와 생성자는 별도의 검증이 없네요. 
테스트로 작성해 보면 좋을 것 같습니다.

2023-09-18 12:35 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/application/ProductQueryService.java
> +}
이 메서드 때문에 많이 복잡해 지는 것 같은데요. 
Product를 Menu내에서 정의해 보는 것은 어떨까요? 
해당 메서드만 보고 Map의 Key는 Product.id임을 유추할 수 있나요? Value는 price임을 유추할 수 있을까요?

2023-09-18 12:35 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/tobe/domain/dto/MenuCreateCommand.java
> +    private BigDecimal price;
이 DTO까지 필요할까요? 별도의 다른 이유가 있을까요? 
필요하다면 Menu의 생성 파라미터를 줄여줘야 하는데 여전히 Menu 생성에 대한 파라미터는 많습니다. 
MenuCreateRequest내부에서 getter를 통해서 Price, DisplayedName, MenuProducts 을 만들고 Menu를 생성해 보는 것은 어떨까요? 

검증은 조금 생략 되었지만 이 방법으로 충분하지 않을까요?
지금 코드는 꽤나 복잡하다고 느껴져요. 🥲

```java
@Transactional
public MenuInfoResponse create(final MenuCreateRequest request) {
  new NewMenu(
      UUID.randomUUID(),
      DisplayedName.of(request.getName(), displayNameChecker),
      Price.of(request.getPrice()),
      request.getMenuGroupId(),
      request.isDisplayed(),
      new MenuProducts(
          //...
      )
  );
}
```

2023-09-19 23:32 UTC, koola97620 commented on src/main/java/kitchenpos/menus/tobe/domain/dto/MenuCreateCommand.java
> +    private BigDecimal price;
DisplayName, Price 를 메뉴를 생성하면서 만들어야 할까, 미리 만들고 팩토리 메서드로 넘겨줄까 고민을 하다가 메뉴 생성에 관한 로직은 모두 메뉴의 팩토리 메서드에 넣자는 생각을 했어요 ㅎㅎ...  오히려 처음에는 VO 는 외부에서 만들고 넘겨줬었던 것 같아요 ㅎ  MenuProducts 도 마찬가지로 생성 위치를 고민하다가 Menu 의 팩토리 메서드로 넣게 됐습니다 ㅎ MenuProduct 는 Menu 가 생성될 때 같이 생성되어야 하니까 Menu 안에 생성로직을 넣자는 생각을 하게 됐어요!  바꿔보겠습니다.

MenuCreateCommand 가 등장하게 된 것은 
MenuCreateRequest 가 domain 영역까지 가게 하는건 안되고, 팩토리 메서드에 너무 많은 인자를 넘기기 싫어서 MenuCreateCommand 에 담아서 한번에 넘기자는 생각을 하게 됐었어요.  그런데 어차피 Command 를 넘겨도 인자가 많은건 똑같기 때문에 ㅎ 바꿔보겠습니다!

2023-09-20 01:26 UTC, koola97620 commented
Menu 의 팩터리 메서드 또는 생성자에 어느 기능까지 위임해야 하는지가 최대 고민이었습니다. 그러다보니 굉장히 복잡하게 생긴(?) 로직이 작성되어 버렸네요 ㅠㅠ

DisplayName, Price 를 메뉴를 생성하면서 만들어야 할까, 미리 만들고 팩토리 메서드로 넘겨줄까 고민을 하다가 메뉴 생성에 관한 로직은 모두 메뉴의 팩토리 메서드에 넣자는 생각을 했어요 ㅎㅎ... 오히려 처음에는 VO 는 외부에서 만들고 넘겨줬었던 것 같아요 ㅎ MenuProducts 도 마찬가지로 생성 위치를 고민하다가 Menu 의 팩토리 메서드로 넣게 됐습니다 ㅎ MenuProduct 는 Menu 가 생성될 때 같이 생성되어야 하니까 Menu 안에 생성로직을 넣자는 생각을 하게 됐어요! 바꿔보겠습니다.

MenuCreateCommand 가 등장하게 된 것은
MenuCreateRequest 가 domain 영역까지 가게 하는건 안되고, 팩토리 메서드에 너무 많은 인자를 넘기기 싫어서 MenuCreateCommand 에 담아서 한번에 넘기자는 생각을 하게 됐었어요. 그런데 어차피 Command 를 넘겨도 인자가 많은건 똑같기 때문에 ㅎ 바꿔보겠습니다!

피드백 반영해서 바꾸니 훨씬 보기 좋아졌네요 :)
빠르고 상세한 피드백 감사합니다!

2023-09-21 06:04 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다.
확인 부탁드려요.

2023-09-21 06:04 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/application/MenuGroupService.java
> +        return savedMenuGroupList.stream()
`List` 자료구조명을 명시하면 set으로 변경되면 의존하고 있는 부분은 모두 변경이 필요합니다. 
그리고 관심사가 `List`보다는 `MenuGroup`이기 때문에 복수형을 사용해도 좋을 것 같아요. 🙂

2023-09-21 06:04 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenu.java
> +    }
테스트가 없네요. ㅠㅠ 도메인 객체의 테스트는 작성 부탁드립니다.

2023-09-21 12:55 UTC, koola97620 commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenuProduct.java
> +    private UUID productId;
현재의 도메인 문제(Product 의 price 와 MenuProduct 의 quantity 를 사용하는 유효성 검증 로직)를 해결하기 위해선 객체를 참조해도 될 것 같은데,  단순하게 애그리거트가 다르니까 객체를 직접 참조하는 것 보다는  ID 를 이용해 간접참조를 해야겠다는 생각을 했어요. 그리고 MenuProduct 에서 Product  엔티티를 참조함으로 인해 Product의 상태를 변경할 가능성이 생길 수도 있다고 생각하여 객체의 오용을 방지하기 위해 ID 참조 방식을 사용했어요 :)

2023-09-21 13:26 UTC, koola97620 commented on src/main/java/kitchenpos/common/domain/Price.java
> +    }
깜빡하고 수정하지 못했네요 ㅠ 변경하겠습니다.

2023-09-21 13:51 UTC, koola97620 commented on src/main/java/kitchenpos/menus/application/MenuService.java
>      }
MenuProduct에서 Product 를  간접참조할때 가격 검증 로직을 어디에 두어야 하나 고민을 하다 Service 에 두었네요. 도메인 로직이니 다시 도메인 영역으로 이동시켰습니다.

2023-09-23 01:54 UTC, koola97620 commented
안녕하세요 리뷰어님!
피드백 반영했습니다! 
확인 부탁드립니다~! 감사합니다! :)

2023-09-24 11:27 UTC, hyunssooo approved these changes
안녕하세요. 
메뉴 리팩터링 하신다고 고생 많으셨습니다.
다음 step 진행 부탁드려요. 
확인이 너무 늦어 죄송합니다. 🙇‍♂️

2023-09-24 11:27 UTC, hyunssooo commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenuProduct.java
> +            columnDefinition = "binary(16)",
이건 어떤 의미일까요??

2023-09-24 11:28 UTC, merged

2023-09-24 11:34 UTC, koola97620 commented on src/main/java/kitchenpos/menus/tobe/domain/NewMenuProduct.java
> +            columnDefinition = "binary(16)",
처음에 에러나서 당황해서..  잠깐 메모해놓는다는것을 지우지 못했네요 ㅠ