2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #236
Opened 2023-09-22 08:05 UTC by HackSung

안녕하세요. step2 리팩토링은 예상보다 휠씬 많은 시간이 소요되네요. 후아~ ^^;; 

일단 저번에 실수로 step1을 바로 머지해 주신거는 피드백에 리플도 달고 이번 PR에 같이 반영했습니다.
- [step1 PR](https://github.com/next-step/ddd-tactical-design/pull/216) 

이번 step2 리팩토링을 진행하면서 ProductClient인터페이스를 사용하여 menu BC안에 있는 Product 도메인모델을 
들어내는데 주안점을 두었습니다. 

그럼 이번에도 기탄없는 리뷰 기대합니다. 😄 
좋은 하루 보내세요~

2023-09-23 03:39 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/menu/MenuService.java
> +                .collect(Collectors.toList());
대부분 제약 조건 검증 등을 도메인으로 옮겨주셨는데요. 이부분도 MenuProducts라는 일급 컬렉션이 존재한다면 해당 부분으로 책임을 옮겨볼 수 있지 않을까 하는 생각이 드네요~

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/menu/MenuService.java
> +        }
저수준 예외인 경우라면 다시 예외를 캐치해서 다른 타입으로 변경해 던지는 경우도 있지만 지금은 IllegalArgumentException -> IllegalStateExceptionf로의 변경은 없어도 되지 않을까 하는 생각이 듭니다.

이런 경우라면 validateMenuPrice에서 의도한 예외를 던지는게 낫지 않을까요?

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/menu/MenuService.java
> +            }
예외를 이용해 로직을 구현하는것은 좋지 못한 코드 작성 방식으로 보여요.

예외는 예외 상황에 사용할 용도로 설계되었기 때문에 JVM 등에서 적용하는 최적화 범위가 제한되거나 할 수 있습니다. 예외는 정말 예외 상황에 사용해야지, 정상적인 흐름에서 예외를 잡아 동작을 진행시키는 것은 좋지 않습니다.

isValidateMenuPrice 등으로 변경하고 boolean 타입을 받아 처리하거나 혹은 다른 방식으로 구현하는게 좋아보여요.

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/menus/domain/menu/ProductClient.java
> +public interface ProductClient {
부패 방지 계층의 역할을 잘 수행하고 있네요 👍

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/menus/domain/menu/MenuPrice.java
> +public class MenuPrice {
ProductPrice랑 어떤 부분이 다를까요? ProductPrice의 이름을 변경하고 다른 컨텍스트에서도 사용할 수 있는 공통 도메인 클래스로 사용할 순 없을까요?

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/menus/domain/menu/MenuName.java
> +public class MenuName {
ProductName과 어떤 부분이 다를까요? 다른 컨텍스트에서도 사용할 수 있는 공통 도메인 클래스로 사용할 순 없을까요?

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/support/GlobalRestControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body(e.getMessage());
406은 거의 잘 사용되지 않는 응답 코드입니다. 헤더와 관련된 내용이 포함된 응답 코드로 기억하는데요. 
IllegalStateException와 같은 표준 예외는 라이브러리 단에서 던지는 경우도 있을텐데 406과 같은 특징이 있는 응답 코드를 사용하는게 좋을지 고민이 필요해보여요.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

2023-09-23 03:39 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/listener/ProductEventListener.java
> +    @TransactionalEventListener
TransactionalEventListener를 사용하신 이유가 무엇인가요?

상품 가격 변경에 따라 메뉴를 숨기는 부분이 반영 안되면 문제가 될 것 같은데, 그냥 EventListener를 사용해 트랜잭션을 묶는게 나은 선택이 될 수 있지 않을까요?

2023-09-23 17:16 UTC, HackSung commented on src/main/java/kitchenpos/menus/application/menu/MenuService.java
> +                .collect(Collectors.toList());
훌륭한 제안이십니다. 👍 
일급 컬렉션을 생성하여 도메인으로 조건 검증을 옮기니 응집성이 더 좋아진 것 같습니다.

2023-09-23 17:30 UTC, HackSung commented on src/main/java/kitchenpos/menus/application/menu/MenuService.java
> +        }
메뉴생성, 가격변경, 메뉴노출 세가지 기능이 메뉴가격에 대해 동일한 검증을 하고 있어 
해당 로직을 validateMenuPrice() 공통 메서드로 도출하고 검증실패시 IllegalArgumentException을 던졌으나
리팩토링 전 소스에서 메뉴노출기능의 경우만 검증실패 시 IllegalStateException을 throw하는 것으로 작성되어 있고 
테스트코드도 마찬가지이다 보니 해당 Exception을 그대로 맞춰주려다 이런 사태가 발생하였습니다.
해당 검증 공통메서드를 도메인 모델로 이동시키고 기능별 의도한 예외를 던지도록 개선하였습니다.

2023-09-23 17:35 UTC, HackSung commented on src/main/java/kitchenpos/menus/application/menu/MenuService.java
> +            }
네 제안주신대로 boolean타입을 받아 처리하도록 구현했습니다.
관련하여 질문이 한가지 있는데요,
하나의 메서드에서 에러 케이스별 사용자 정의 예외(Applicaiton Exception)를 throw하고
밖에서 Exception별로 후속 처리를 분기하는 패턴을 종종쓰는데 이것도 안티패턴일까요?
여러가지 에러 케이스별 후속 분기 처리가 필요한 경우 어떤 방법을 쓰시는지 궁금합니다.

2023-09-23 17:36 UTC, HackSung commented on src/main/java/kitchenpos/menus/domain/menu/MenuPrice.java
> +public class MenuPrice {
ProductPrice와 다른 부분이 없어 제안 주신대로 공통 VO 클래스로 재정의 하였습니다.

2023-09-23 17:46 UTC, HackSung commented on src/main/java/kitchenpos/menus/domain/menu/MenuName.java
> +public class MenuName {
ProductName과 다른 부분이 없어 제안 주신대로 공통 VO 클래스로 재구현 하였습니다.
Name의 경우 비속어 검사 도메인 인터페이스를 의존하고 있어 해당 도메인도 같이 공통으로 옮기긴 했는데요
초창기 미션때 BC가 다르다면 VO는 몰라도 도메인 모델은 다른 부분이 없어도 BC별로 정의하는게 좋다라는 다른 리뷰어님의 의견이 있었습니다. common은 양날의 검과 같아서 보수적으로 접근한다고 하시면서요.
그렇다면 유형별로 주문 BC가 세가지로 정의되었는데 다른 부분없는 OrderLineItem 도메인 모델의 경우도 
일단 공통으로 빼는게 좋을지 
아니면 후에 서버분리나 팀분리가 발생하면 그때 BC별로 정의하는게 좋을지 아직도 확신을 갖지 못하는데
리뷰어님의 의견은 어떠신지 듣고 싶습니다. 😄

2023-09-23 17:55 UTC, HackSung commented on src/main/java/kitchenpos/support/GlobalRestControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body(e.getMessage());
지난 리뷰때 가이드 주신 NoSuchElementException에 대한 에러응답을 status 404으로 처리하면서
IllegalArgumentException은 status 400으로 매핑하였고
IllegalStateException은 어떤 status 코드로 매핑 할까 고민하다가 어떤 글에서
**406 Not Acceptable(받아들일 수 없음) : 요청은 정상이나 서버에서 받아들일 수 없는 요청일시 사용하는 코드이다.** 를 보고
왠지 500보다는 의미가 더 맞을 것 같다는 생각에 그렇게 한 것 같습니다.
IllegalStateException은 메뉴노출기능에서 메뉴가격검증 후 실패시 던져지고 있는데요
다시 500 internal server error로 응답하게 수정은 했는데
리뷰어님은 어떤 응답코드가 적절하다고 생각하시는지요

2023-09-23 18:10 UTC, HackSung commented on src/main/java/kitchenpos/menus/application/listener/ProductEventListener.java
> +    @TransactionalEventListener
지난번 Product리팩토링때는 그냥 EventListener를 사용하긴 했는데
지난주 제이슨님이 이벤트처리에 대해 라이브코딩을 하면서 TransactionalEventListener를 사용하시더라구요.
그래서 @EventListener와 @TransactionalEventListener의 차이가 뭔가 살펴봤는데
상품가격변경이 변경되어 이벤트를 받고 메뉴를 숨겼는데 상품가격 변경 후 Exception이 발생하여 커밋이 실패한 경우에도
여전히 메뉴가 숨김상태로 되어버리니
@TransactionalEventListener를 사용해야 트랙잭션이 묶이면서 이벤트 리스너처리와 싱크가 맞게 되는 것으로 이해했습니다.

- https://hides.kr/1084

2023-09-23 18:10 UTC, HackSung commented
꼼꼼한 리뷰에 다시금 구현을 되돌아 보게 되면서 많은 도움이 된것 같습니다.
감사합니다. 😄

2023-09-24 13:26 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/menu/MenuService.java
> +            }
> 밖에서 Exception별로 후속 처리를 분기하는 패턴을 종종쓰는데 이것도 안티패턴일까요?
여러가지 에러 케이스별 후속 분기 처리가 필요한 경우 어떤 방법을 쓰시는지 궁금합니다.

후속 분기가 단순 에러 로그를 남기는 부분 등이면 문제가 되지 않을 것 같습니다. 다만 지금과 같이 비즈니스 로직이 포함된 경우라면 최대한 지양할 것 같아요. 저라면 사용자 정의 예외에 에러 코드 등을 담고 그에 따른 분기를 하거나 할 것 같습니다.

2023-09-24 13:29 UTC, kyucumber commented on src/main/java/kitchenpos/menus/domain/menu/MenuName.java
> +public class MenuName {
> 초창기 미션때 BC가 다르다면 VO는 몰라도 도메인 모델은 다른 부분이 없어도 BC별로 정의하는게 좋다라는 다른 리뷰어님의 의견이 있었습니다. common은 양날의 검과 같아서 보수적으로 접근한다고 하시면서요.

이건 상황에 따라 다를 것 같습니다. 만약 레파지토리가 분리되고 각각의 바운디드 컨텍스트를 관리하는 별도의 팀이 있다면 말씀하신 것 처럼 별도의 모델로 정의하는게 좋다고 생각합니다.

하지만 지금처럼 한 레파지토리 안에서 아예 똑같은 코드를 패키지별로 나누어 관리한다면 오히려 특정 컨텍스트의 도메인 모델에 반영된 로직이 빠지거나 하는 리스크가 더 클 것 같아요.

정리하면, 지금과 같이 같은 레파지토리 안에서 동일한 로직을 가지는 경우 오히려 로직이 누락되어 버그 등이 발생하기 쉬우므로 하나로 관리하고 컨텍스트별 다른 로직이 필요하거나 바운디드 컨텍스트의 관리 책임이 한 팀이 아닌 경우 그때 분리를 고려해도 괜찮을것 같아요.

2023-09-24 13:31 UTC, kyucumber commented on src/main/java/kitchenpos/support/GlobalRestControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body(e.getMessage());
요건 서비스마다 사용하는 케이스가 다를 수 있어서 정답은 없을 것 같아요. 다만 이전에 살펴보았을 땐 IllegalStateException를 500 응답으로 주는 케이스가 많았던 것 같습니다.

2023-09-24 13:32 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/listener/ProductEventListener.java
> +    @TransactionalEventListener
아이고 죄송합니다. 졸린 상태로 리뷰를 했는지 반대로 보았네요. 헷갈리게 해서 죄송합니다.

2023-09-24 13:34 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다. 남겨두신 코멘트에 답변 남겨두었으니 확인 부탁드려요.

https://github.com/next-step/ddd-tactical-design/pull/236#discussion_r1335178781
https://github.com/next-step/ddd-tactical-design/pull/236#discussion_r1335178573
https://github.com/next-step/ddd-tactical-design/pull/236#discussion_r1335178142
https://github.com/next-step/ddd-tactical-design/pull/236#discussion_r1335178392

다음 단계 진행을 위해 머지하겠습니다.

2023-09-24 13:34 UTC, merged

2023-09-24 14:05 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/listener/ProductEventListener.java
> +    @TransactionalEventListener
아 요거 남기신 부분 중에 정정할 내용이 있는데요.

> @TransactionalEventListener를 사용해야 트랙잭션이 묶이면서 이벤트 리스너처리와 싱크가 맞게 되는 것으로 이해했습니다.

위의 예제는 이메일 발송이기 때문에 외부 시스템으로 전송을 하는거라 롤백이 되지 않는것이고 트랜잭션을 실제로 묶으려면 그냥 `@EventListener`를 사용하시면 됩니다. `@TransactionalEventListener`는 커밋 전 후와 같은 특정 시점에 이벤트가 동작하게 만들기 위해 사용하는 것입니다.

이메일 발송과 같은건 트랜잭션 롤백이 된 시점에 발송되면 안되므로 `@TransactionalEventListener`를 쓰는게 맞으나 상품 가격 변경과 메뉴 숨김을 같은 트랜잭션에 묶고 싶은거라면 `@EventListener`를 쓰는게 맞습니다. 

`@Async`를 쓰면 또 이야기가 달라지긴 하지만 Async가 없는 상황에서 서비스 레이어의 트랜잭션이 이어지게 하려면 위에 말씀드린것처럼 `@EventListener`를 써야 합니다.

2023-09-24 14:22 UTC, kyucumber commented on src/main/java/kitchenpos/menus/application/listener/ProductEventListener.java
> +    @TransactionalEventListener
상품 가격 변경이 정상적으로 되었음에도 불구하고 메뉴 숨김이 안되면 해당 컨텍스트에서 정한 도메인 규칙이 깨진 상태로 유지되는 것이기 때문에 차라리 상품 가격 변경 자체도 실패하도록 묶어버리는게 낫지 않을까 하는 생각이 들어서 말씀드렸어요.

> 상품 가격 변경 -> 이벤트 발생 -> 메뉴 숨김 -> (일시적인 DB오류로) 가격 변경 커밋 실패 -> 메뉴 숨김 롤백

의도하신게 위와 같다면 지금 구현하신 것 그대로 아래처럼 하시면 됩니다.

```java
@TransactionalEventListener
@Transactional(propagation = Propagation.REQUIRES_NEW)
```

2023-09-24 14:48 UTC, HackSung commented on src/main/java/kitchenpos/menus/application/listener/ProductEventListener.java
> +    @TransactionalEventListener
제가 @TransactionalEventListener에 대해 잠시 잘못 이해하고 있었습니다.
@TransactionalEventListener를 쓰면 메뉴 숨김 커밋 실패시 상품 가격변경은 롤백되지 않아 싱크가 안 맞는 경우가 발생할 수 있으나
@EventListener를 쓰면 가격변경과 메뉴숨김이 같은 트랜잭션에 묶여 싱크가 안맞는 경우는 없으므로
위와 같은 상황에서는 리뷰어님이 최초에 그냥 EventListener를 쓰라고 하신게 정답이었습니다. 👍