1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #248
Opened 2024-05-21 16:38 UTC by pawoo0211

안녕하세요, 이번 미션 참여하게 된 박상권이라고 합니다.

이번 미션에서 도메인 영역까지 구현하는 범위가 어디까지인지 정확히 가늠이 안되어 현재까지 진행한 것으로 PR 생성드립니다.

감사합니다.

2024-05-22 12:22 UTC, hyunssooo requested changes
안녕하세요. 🙂
이번 미션 함께 진행할 정현수입니다.
몇 가지 코멘트 남겼어요. 확인 부탁드립니다!
함께 고민해 보고 싶은 부분은 코멘트나 DM 으로 남겨주세요!

2024-05-22 12:22 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/ProductDomainService.java
> +public class ProductDomainService {
도메인 서비스로 만들어 주셨네요 :) 
다만 `도메인 서비스` 라는 이름 보다 도메인에 가까운 용어를 사용해 보는 것은 어떨까요?

2024-05-22 12:22 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
기본 생성자가 필요하지 않나요?

2024-05-22 12:22 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    }
가격 변경에 대한 요구 사항도 있지 않았나요?

2024-05-22 12:22 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +public class DisplayedName {
기본 생성자가 필요하지 않나요?

2024-05-22 12:22 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +
final 키워드가 사용될 수 있나요?

2024-05-22 12:22 UTC, hyunssooo commented on src/test/java/kitchenpos/products/domain/ProductTest.java
> +    }
가짜 객체를 이용한 테스트 👍

2024-05-22 15:42 UTC, pawoo0211 commented on src/main/java/kitchenpos/products/tobe/domain/ProductDomainService.java
> +public class ProductDomainService {
피드백 감사합니다.

말씀하신 것처럼 도메인에 가까운 용어로 도메인 서비스를 정의할 경우 하나의 도메인에서 여러 개의 도메인 서비스가 생성될 것으로 예측되는데 이처럼 하나의 도메인에 여러 개의 도메인 서비스가 존재할 수 있는지 궁금합니다.

2024-05-22 15:55 UTC, pawoo0211 commented on src/main/java/kitchenpos/products/tobe/domain/DisplayedName.java
> +
JPA를 많이 사용하지 않다보니 기본적인 실수를 범했네요..

피드백 감사합니다.

2024-05-23 11:23 UTC, hyunssooo approved these changes
안녕하세요. 
상품 리팩터링 잘 진행해 주셨습니다. 
다음 step진행 부탁 드릴게요!

2024-05-23 11:23 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/Price.java
> +public class Price {
Price, DisplayedName은 각각 단위 테스트가 작성되어도 좋을 것 같아요. :)

2024-05-23 11:23 UTC, hyunssooo commented on src/test/java/kitchenpos/products/domain/ProductTest.java
> +
`@Nested` 통해서 depth로 테스트를 표현해 보는 것은 어떨까요?

2024-05-23 11:23 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    }
테스트에서만 사용하는 메서드이네요. 
테스트를 위한 코드가 프로덕션 코드에 존재해도 괜찮을까요?

2024-05-23 11:23 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    }
```suggestion
    public Product(
        UUID id,
        String name,
        BigDecimal price,
        ProductNameValidationService productNameValidationService
    ) {
        this(
            id,
            name,
            new Price(price),
            productNameValidationService
        );
    }
```

부 생성자는 주 생성자를 사용하는 것이 어떨까요?

2024-05-23 11:23 UTC, merged

2024-05-23 13:17 UTC, hyunssooo commented on src/main/java/kitchenpos/products/tobe/domain/ProductDomainService.java
> +public class ProductDomainService {
넵, 저는 여러 개의 도메인 서비스가 생길 수 있다고 생각합니다. :)