1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #262
Opened 2024-05-26 08:58 UTC by wooddy-kim

### 작업 내용
- 상품 도메인 리팩터링

### 궁금한 점
- 리팩터링 범위에 대해 확신이 없어서 DM 을 보냈습니다! 
  - domain 패키지만 구성하면 되는걸까요? 관련된 application 패키지도 포함일까요?

2024-05-26 22:18 UTC, sihoony commented
> ### 작업 내용
> * 상품 도메인 리팩터링
> 
> ### 궁금한 점
> * 리팩터링 범위에 대해 확신이 없어서 DM 을 보냈습니다!
>   
>   * domain 패키지만 구성하면 되는걸까요? 관련된 application 패키지도 포함일까요?

안녕하세요~! 재우님,
이번 미션은 tobe.domain 패키지를 만들어서 리팩터링을 시작한다고 보시면 됩니다. 다만 연관성 있는 도메인도 있을 수 있으니, 범위는 한정하면서 영향도 있는 Domain은 영향 범위까지(호출하는 메소드명 변경)보시면 될 것 같네요~!
현재 상품외에 메뉴도 리펙터링을 진행하신 것 같습니다.
미션에 따라서 리뷰를 진행할께요. 이점 양해 부탁드려요~!

2024-05-26 23:23 UTC, sihoony requested changes
안녕하세요~! 재우님,
이번 미션을 잘 진행해주셨네요~! 👍 
간단한 코멘트를 남겼으니 확인해주세요.
즐거운 하루 되세요~! 😄

2024-05-26 23:23 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
JPA 구현 기술이 Domain에 있어야하는지 고민이 되는 부분이네요.
JPA가 가져다 주는 편리함이지만 컴파일시 기존 기능을 제공하는 Infrastructure 영역으로 봐야할지 상당한 고민이 드는데,
재우님은 어떻게 생각하시나요?

2024-05-26 23:23 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/Product.kt
> +        require(nameValidator.validate(name.value)) { "상품 이름에 비속어가 포함되어 있습니다." }
ProductNameValidator는 이름 그대로 ProductName에서 체크해보면 어떨까요~!?
역할이 명확하게 구분되어 질 것 같네요~!

2024-05-26 23:23 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/ProductPrice.kt
> +value class ProductPrice(val value: BigDecimal) {
👍 👍

2024-05-27 06:54 UTC, wooddy-kim commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
@sihoony 
도메인에서는 구현 기술에 의존하지 않는 순수한 ProductRepository만 참조하는 것이 좋을 것 같습니다. 추후 변경할 때 JpaProductRepository만 변경하면 되니까요.

그런 의미에서 domain 패키지 대신 infra 영역에 위치시켜보았습니다.

제가 JPA를 실무에서 사용해보지 않아서 궁금한데요, 리뷰어님께서는 실무에서 어떤 패턴으로 Repository를 구성하고 계신가요? 현재 프로젝트처럼 ProductRepository와 JpaProductRepository로 분리하는 형태를 사용하시나요?

2024-05-27 12:01 UTC, sihoony commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
저는 JPA와 외부 요청등 Output에 해당하는 영역은 ProductRepository와 분리하여 사용합니다.

> 1. Test Code를 작성할때 ProductRepository에 대한 FakeObject 생성이 용이하다.
> 2. 외부 요소( DB Access / API 요청 )을 직접 검증하지 않고, 관련 로직만 검증 및 격리 시킬 수 있다.

2가지 관점에서 분리하여 사용하고 있습니다.

2024-05-27 12:03 UTC, sihoony approved these changes
안녕하세요. 재우님,
피드백 잘 반영해 주셨네요~! 💯 
간단한 코멘트를 남겼으며, 다음 미션을 위해서 Merge하겠습니다.
즐거운 하루 되세요. 😄

2024-05-27 12:03 UTC, sihoony commented on src/test/java/kitchenpos/products/tobe/application/InMemoryProductRepository.java
> +public class InMemoryProductRepository implements ProductRepository {
다음 미션 수행시 어느 영역으로 이동하면 좋을지 고민해보면 좋을 것 같습니다.

2024-05-27 12:04 UTC, merged