🚀 1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #270
Opened 2024-05-27 02:43 UTC by xxxx-jeung

안녕하세요 리뷰어님

잘 부탁드리겠습니다.

Product 영역을 건드리니 Menu price 영역도 같이 영향이 갈 것 같아 딱 Product 부분만 처리했습니다

2024-05-27 13:00 UTC, HackSung requested changes
안녕하세요 이번 미션을 같이 하게 된 이학성입니다. 😄 
리팩터링 미션의 첫 발을 내딛게 되신 것을 축하드립니다. 👏 
같이 고민해 보고 싶은 코멘트를 남겨드렸으니 확인 부탁드립니다. 🙏

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +}
새로 추가하신 파일들의 끝에 개행 문자가 붙지 않은 것 같은데 아래글 참고하셔서 조치하면 좋을 것 같아요

> https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/infra/PurgomalumClient.java
> +package kitchenpos.products.tobe.infra;
`PurgomalumClient`인터페이스는 외부 시스템과의 통신을 추상화하여 정의했지만
어떤 기술을 사용하여 외부 시스템과 통신하는지, 그 통신이 어떻게 이루어지는지에 대한 
기술적인 세부사항은 명시되지 않았는데 infra계층에 그대로 두는게 맞을까요?
제웅님이 생각하시는 인프라스트럭쳐 계층에 대한 정의와 역할이 궁금합니다. 🤔

참고로 제가 생각하는 인프라스트럭처 계층은 
특정 데이터베이스 연동, 네트워크 통신, 파일 시스템 접근 방법 같은 기술적인 세부사항과 관련된 코드를 포함하는 계층이고
이 때 도메인 계층이나 애플리케이션 계층이 기술적인 세부 사항을 의존하지 않도록 하기 위해
`PurgomalumClient` 인터페이스가 그 역할을 담당할 수 있을 것 같습니다.
바로 클린 아키텍쳐에서 강조하는 도메인을 향한 의존성 역전 원칙(DIP)이 되겠습니다.

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
`JpaProductRepository` 인터페이스는 JpaRepository를 상속받아 JPA라는 특정 기술에 의존하고 있는데 도메인 계층에 위치하는게 맞을까요? 🤔

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/ProductPrice.java
> +public class ProductPrice {
값 객체 활용 좋습니다! 👍 💯 
추가로 값 객체 동등성 비교를 위한 equals & hash code 메서드도 재정의 해보면 어떨까요?

> https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/ProductPrice.java
> +            throw new IllegalArgumentException();
에러 원인을 쉽게 파악할 수 있는 메세지도 Exception에 추가하면 더욱 좋을 것 같습니다.

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public Product create(final String name, final BigDecimal price) {
엔티티 모델이 Controller까지 그대로 외부로 노출되고 있는데요,
엔티티 대신 DTO로 변환하여 반환하는게 좋을 것 같은데 어떻게 생각하세요?
교육용 미션이기는 하지만 완성도를 위해 실무와 같은 레벨로 훈련해 보면 좋을 것 같습니다.

> https://cobi-98.tistory.com/60#google_vignette

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    private String name;
`Product`의 name도 `ProductPrice`처럼 비속어를 포함하지 않는 값 객체로 정의해 보면 어떨까요?

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    public void setChangePrice(final BigDecimal price) {
메서드명에서 set과 Change 모두 동사이니 set은 빼도 되지 않을까요? 🤔

2024-05-27 13:00 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +import kitchenpos.menus.domain.MenuRepository;
import 패키지문에서 드러나듯 현재 Product도메인이 Menu도메인을 직접 의존하고 있는 상황인데요
이제 Product와 Menu 도메인 간의 의존성을 분리하는 방법을 고민해야 하는 단계에 오셨습니다. 😄 

아마 이번주 수업에서 배우시게 되지 않을까 싶은데
의존성을 분리하는 방법 중 하나는 이벤트 기반의 접근 방식을 사용하는 것이고 
이 방식은 Product가 가격 변경 이벤트를 발행하고 Menu도메인은 이 이벤트를 구독하게 하는 것입니다. 
이렇게 하면 Product도메인은 Menu도메인에 대해 알 필요가 없게 됩니다. 
또 다른 방법은 인터페이스를 사용하여 약결합을 만드는 것입니다.
이 방식은 Product가 Menu의 구체적인 구현에 의존하는 대신 Menu가 구현해야 하는 인터페이스에 의존하게 합니다. 
이렇게 하면 Menu 도메인의 구현이 변경되더라도 Product에는 영향을 미치지 않게 됩니다.

이번 Step에서 당장 적용이 힘드시다면 좀 더 고민해 보시고 다음 Step에서 적용해 보시면 좋을 것 같습니다. 😄

2024-05-27 14:05 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public Product create(final String name, final BigDecimal price) {
피드백 감사합니다!
여기서 한가지 고민이 되는 부분이 있는데요
DTO로 변환할 때 어느 클래스에 변환하는 작업을 넣어주는게 좋을까요?

예를 들어 
```java
public class ProductCreationResponseDto {
    private final UUID id;
    private final String name;
    private final ProductPrice price;

    public ProductCreationResponseDto(UUID id, String name, ProductPrice price) {
        this.id = id;
        this.name = name;
        this.price = price;
    }

    public static ProductCreationResponseDto of(Product product) { // 첫번째
        return new ProductCreationResponseDto(product.getId(), product.getName(), product.getPrice());
    }

    public static ProductCreationResponseDto of(UUID id, String name, ProductPrice price) { // 두번째
        return new ProductCreationResponseDto(id, name, price);
    }
}

```

세번째는 Entity에서 ProductCreationResponseDto 해당 클래스를 만들어 주는 방식인데..
첫번째 방식은 ProductCreationResponseDto 해당 클래스가 Product를 알고있으면서 의존해야 한다는 점, 두번째는 매변수를 나열해서 집어 넣는거라면 Service 단에서 new ProductCreationResponseDto() 로 생성해서 사용하면 된다는 점, 세번째는 Entity가 ProductCreationResponseDto이 클래스를 알아야 한다는 점.. 

각자 장단점이 존재하니 무얼 기준으로 객체를 만들어서 사용해야 좋은건가 헷갈립니다..!

@HackSung

2024-05-27 14:13 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/infra/PurgomalumClient.java
> +package kitchenpos.products.tobe.infra;
음 제가 답변해주신 부분에 대해 잘 이해가 안됩니다만..

내용을 이해해봤을 때 infra 패키지 구조가 kitchenpos 바로 밑으로 되어있어야 된단 말씀이신걸까요??
만약 이 말이 맞다면, 저 또한 해당 인프라 스트럭쳐는 최상위 디렉토리 아래에 두는게 낫다고 생각합니다. 

과제를 급하게 하다보니 tobe 디렉토리 아래 다 둬야 한다는 생각밖에 없었네요..

2024-05-27 14:22 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
음.. 질문에 대한 의도를 파악하기 어렵습니다..ㅠ

일단 이해한바로 도메인 패키지와 JPARepository 패키지가 같은 영역에 있다는 것에 의문인 것일까요?!
음, repository 패키지를 따로 만들어 관리하는게 더 깔끔해 보일 것 같습니다!

@HackSung

2024-05-27 14:52 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    public String getName() {
한가지 궁금한게 있습니다!

값 객체로 정의하고 나면, 해당 값 객체를 service 영역에서 값을 조회할 때 get을 사용하는데
직접 값 객체에 접근해 get을 하는게 나을까요? 아니면 애그리거트 루트에서 get을 한 것을 반환하는게 둘 중 어느 방향이 더 괜찮을까요?

일단 제가 생각하기엔 값 객체가 바깥으로 노출되지 않도록 하는게 나을 것 같다고 생각했는데
방금 다시 생각 해보니 Vo를 만들어놓고 활용하지 않으면 무슨 소용일까 라는 생각도 듭니다.. 
바깥으로 내보내도 불변 객체이니 상관 없고, Vo 명을 보고 이게 어떤 객체이고 어떤 의미를 갖고있는지 금방 알 수 있다라는 장점이 있겠네요

2024-05-28 01:50 UTC, xxxx-jeung commented
@HackSung 

추가로 또 질문이 있습니다!
같은 바운더리 컨텍스트에 두 개 엔티티가 있을 때는 서로 종속적이어도 상관 없을까요?
그래도 나중을 생각했을 때 인터페이스를 둬서 약결합으로 둬야 할까요??

2024-05-28 13:22 UTC, HackSung commented
> 추가로 또 질문이 있습니다!
> 같은 바운더리 컨텍스트에 두 개 엔티티가 있을 때는 서로 종속적이어도 상관 없을까요?
> 그래도 나중을 생각했을 때 인터페이스를 둬서 약결합으로 둬야 할까요??

같은 바운디드 컨텍스트 내의 엔티티들은 동일 도메인을 처리하기 위해 동일한 비즈니스 규칙과 로직을 공유하게 되므로
엔티티간의 종속성이 발생하는 것은 일반적이고 자연스러워 보이는데 종속성이 왜 마음에 걸리셨을까요?

2024-05-28 14:05 UTC, xxxx-jeung commented
> > 추가로 또 질문이 있습니다!
> > 같은 바운더리 컨텍스트에 두 개 엔티티가 있을 때는 서로 종속적이어도 상관 없을까요?
> > 그래도 나중을 생각했을 때 인터페이스를 둬서 약결합으로 둬야 할까요??
> 
> 같은 바운디드 컨텍스트 내의 엔티티들은 동일 도메인을 처리하기 위해 동일한 비즈니스 규칙과 로직을 공유하게 되므로 엔티티간의 종속성이 발생하는 것은 일반적이고 자연스러워 보이는데 종속성이 마음에 걸리신 이유가 궁금합니다.

동일 도메인을 처리하지만, 코드로 봤을 때 순전히 서로가 다른 엔티티라고 생각이 들어서 마음에 걸렸나 봅니다..!

2024-05-28 14:11 UTC, HackSung requested changes
안녕하세요. 제웅님 😄 
주신 질문에 대한 답변과 피드백을 남겨 드렸으니 확인 부탁드립니다. 🙏

2024-05-28 14:11 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    public String getName() {
서비스에서 값 객체를 직접 조회하는 방법과 애그리거트 루트를 통해 간접 조회하는 방법 모두 
개발 요건에 따라 사용 가능한 방법이지만
저는 다음의 요인을 고려해 볼 때 애그리커트 루트를 통해 조회하는 방법을 먼저 검토해 볼 것 같습니다.
서비스의 여러 곳에서 값 객체에 직접 접근하게 되면 값 객체의 구조 변경이 발생하는 경우
값 객체를 사용하는 여러 곳에서 수정이 발생하게 될 것입니다.
반면에 애그리거트 루트를 통해 값 객체의 세부 정보를 반환하면
값 객체의 구조가 변경되더라도 애그리거트 루트에서만 처리하면 되니 캡슐화 측면에서 좀 더 나을 것 같습니다.
물론 요건이 단순하다면 직접 접근이 더 빠르고 개발이 편할 수 있지만, 
장기적인 유지보수와 확장성 관점에서는 애그리거트 루트를 통한 접근이 유리할 것 같습니다.

2024-05-28 14:11 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
>          }
비속어 정책을 이번에 만드신 ProductName 값객체 안에 넣어보시는 건 어떨까요?

2024-05-28 14:11 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    public void setPrice(final BigDecimal price) {
메서드명을 고치시는 김에 이왕이면 setter 기본명보다 행위를 잘 설명하는 의미 있는 메서드명으로 작명하는 훈련을 해보면 어떨까요?
setPrice보다는 changePrice 같은 메서드 명이 더 직관적일 수 있습니다. 😄

2024-05-28 14:11 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/infra/PurgomalumClient.java
> +package kitchenpos.products.tobe.infra;
제가 드린 질문의 의도는 패키지 구조를 말한게 아니라 PurgomalumClient 인터페이스가 
Infra패키지 내에 위치하는 게 적절한가 였습니다.
Infra계층에 기술 구현체가 위치하고 도메인계층에 기술 구현체를 추상화한 인터페이스가 위치하고 있어야 
도메인이 infra를 의존하지 않고 역으로 Infra가 도메인을 의존하도록 할 수 있다는 관점(DIP)에서 드린 질문이였습니다.

2024-05-28 14:11 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, UUID> {}
기존 domain에 있던 ProductRepository를 그대로 가져 오지 않고 변형 하신 이유가 있으실까요?
```suggestion
public interface ProductRepository {
    Product save(Product product);

    Optional<Product> findById(UUID id);

    List<Product> findAll();

    List<Product> findAllByIdIn(List<UUID> ids);
}
```

2024-05-28 14:11 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
JpaProductRepository는 JPA 기술을 확장한 인터페이스니 domain이 아닌 infra패키지에 위치하는게 적절 할 것 같다는 생각에 드린 질문이였습니다.

2024-05-28 14:11 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public Product create(final String name, final BigDecimal price) {
일단 DTO에서 도메인 모델을 의존하는 것은 문제가 없으나 도메인 모델이 DTO를 의존하게 되면 
외부요건에 의해 도메인 모델의 순수성이 훼손될 수 있다고 생각합니다.
저는 파라미터 개수가 늘어 날 수록 가독성이 떨어지는 두번째 방법보다는 첫번째 방법을 선호하는 편입니다.
다른 방법으로 별도의 변환 객체(매퍼)를 정의하여 DTO를 생성하기도 합니다.

2024-05-28 14:11 UTC, HackSung commented on src/test/java/kitchenpos/products/tobe/application/ProductServiceTest.java
> +import kitchenpos.products.tobe.infra.PurgomalumClient;
리팩토링 작업 후에 테스트 코드가 성공하고 있는지 확인해 보셨을까요? 🤔

2024-05-28 14:56 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, UUID> {}
옮기는 과정에 무언가 착오가 있던 모양이었나봅니다..!!

2024-05-28 15:24 UTC, xxxx-jeung commented
피드백 주신 부분들 모두 확인하고 올렸습니다!
오늘 수업을 듣고 학성님이 남겨주신 내용을 다시 읽어봤을 때 확실히 이해가 됐습니다!
피드백 주셔서 감사합니다!

2024-05-29 13:43 UTC, HackSung requested changes
보완이 필요할 것 같은 부분에 대해 피드백을 남겨드렸어요. 😄
확인하시고 피드백 반영 부탁드립니다. 🙏

2024-05-29 13:43 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/infra/ProductRepository.java
> +package kitchenpos.products.tobe.infra;
ProductRepository인터페이스는 DB연동에 필요한 기능들을 추상화한 인터페이스이므로 고수준 모듈에 해당합니다.
따라서 인프라계층이 아닌 도메인 계층으로 넘어와야 도메인계층이 인프라계층을 더이상 의지하지 않을 수 있습니다.
마찬가지로 PurgomalumClient 인터페이스도 도메인 계층으로 넘어와야 합니다.
아래 다이어그램을 참조해 주세요. 😄 
<img width="440" alt="image" src="https://github.com/next-step/ddd-tactical-design/assets/22284112/a291cdb9-4f86-4bcd-be60-d5c308f66214">

2024-05-29 13:43 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public ProductCreationResponseDto create(final String name, final BigDecimal price) {
create 메서드를 호출하고 있는데가 현재 테스트코드 밖에 없는데
ui패키지에 있는 ProductRestController에서 tobe의 서비스를 호출하게 리팩토링 해 보시는게 좋을 것 같습니다.
리팩토링하시는 김에 request dto도 적용하구요.

2024-05-29 13:43 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public List<Product> findAll() {
여기도 도메인 모델을 외부로 노출하고 있네요? DTO를 적용해 보시는 게 좋을 것 같습니다.
```suggestion
    public List<ProductResponse> findAll() {
```

2024-05-29 13:43 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public Product changePrice(final UUID productId, final BigDecimal price) {
도메인 모델 반환 대신 DTO를 반환하게 수정하시면 좋을 것 같습니다. 😄 
```suggestion
    public ProductResponse changePrice(final ProductRequest request) {
```

2024-05-29 13:43 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +    protected Product() {
아무나 도메인클래스를 생성못하게 protected로 캡슐화 지키기 좋아 보이네요! 👍

2024-05-29 13:43 UTC, HackSung commented on src/test/java/kitchenpos/products/tobe/application/ProductServiceTest.java
> +class ProductServiceTest {
tobe를 위한 서비스테스트 케이스가 현재 하나 밖에 없는데 
기존 ProductServiceTest에서 테스트 가능한 케이스들은 모두 가져와 테스트 해보시는 건 어떠세요?

2024-05-29 14:01 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/infra/ProductRepository.java
> +package kitchenpos.products.tobe.infra;
@HackSung 
아...! 제가 또 잘못 이해하고 있었네요 
이 글과 그림을 보고 학성님이 올려주신 글을 다시 읽어봤는데, 
도메인 패키지에 레파지토리와 PurgomalumClient 인터페이스가 infra 영역에 있는게 맞는지에 대한 질문을 infra 영역에 있어야 한다는 글로 이해했습니다.. 

그럼 여기서 도메인 계층을 완전히 분리시켜도 컴파일 되게끔 하는게 최종 목적이 되겠군요!

2024-05-29 14:23 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public List<Product> findAll() {
@HackSung 
궁금한 부분이 있습니다
저는 실제 업무할 때 ProductResponse 라는건 포괄적인 느낌이 커서
클라이언트에게 응답데이터를 내려줄 때, '어떤 응답 데이터가 들어있어' 라고 의미를 내포해서 전달하고 있는데
학성님은 ResponseDto 내려줄 때 클래스 명을 어떻게 사용하고 계실까요?

2024-05-29 15:21 UTC, xxxx-jeung commented
menu 도메인과 연관된 테스트 영역도 존재해서 주석처리 했습니다..!
step2에서 진행하도록 하겠습니다!

2024-05-30 12:34 UTC, HackSung commented
2단계 미션에서 중점적으로 진행해야할 사항으로 
상품도메인에서 의존하고 있는 메뉴 기능을 분리시켜 본다. (Event나 Interface 사용)

리팩토링이 끝나면 이전 클래스를 삭제하여 스프링이 정상 기동하는지 확인한다.

2024-05-30 12:40 UTC, HackSung commented
리팩터링이 어느 정도 마무리되면 기존 클래스를 삭제하거나 대체하여 스프링이 정상 기동되는지도 확인 부탁드릴께요~

2024-05-30 12:41 UTC, HackSung approved these changes
연일 이어지는 미션진행에 고생 많으셨습니다. 🙏 
미션 진행의 속도를 위해 1단계는 여기서 승인하도록 하겠습니다.
주신 질문에 대한 답변을 확인해 주시고 
1단계에서 마무리 못한 부분은 다음단계에서 계속 진행하는 걸로 할게요!

2024-05-30 12:41 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
JpaProductRepository를 infra패키지로 옮기지 않은 이유가 있으실까요? 🤔

2024-05-30 12:41 UTC, HackSung commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +    public List<Product> findAll() {
네 저도 제웅님 의견에 동의합니다!
네이밍을 할 때 가장 중요한 부분은 의도를 명확하게 나타낼 수 있도록 가능한 구체적인 이름을 붙이는 것이라고 생각합니다.
질문 주신 DTO 클래스명은 
저의 경우 먼저 팀원간 합의된 컨벤션을 지켜 일관된 형식의 이름을 사용하고 있습니다.
프로젝트에서 사용하는 DTO 이름의 구성 형식은 다음과 같습니다.

> `처리대상` + `조작행위` + `[복수]` + `[조건]` + `요청/응답구분`

위 형식에 따라 아래와 같은 DTO클래스명이 도출 되게 됩니다.
- 요청 DTO
  -  상품 단건 조회 : ProductSearchRequest
  -  상품 복수 조회 : ProductSearchAllRequest
  - 상품 저장 : ProductSaveRequest
  - 상품 수정 : ProductUpdateRequest
  - 상품 삭제 : ProductDeleteRequest
- 응답 DTO
  - 상품 단건 조회 : ProductSearchResponse
  - 상품 복수 조회 : ProductSearchAllResponse 
  - 상품 조건 조회 : ProductSearchAllByNameResponse
  - 상품 저장 : ProductSaveResponse
  - 상품 수정 : ProductUpdateResponse
  - 상품 삭제 : ProductDeleteResponse
 
참고가 되셨으면 합니다. 😄

2024-05-30 12:41 UTC, merged

2024-06-02 12:45 UTC, xxxx-jeung commented on src/main/java/kitchenpos/products/tobe/domain/JpaProductRepository.java
> +package kitchenpos.products.tobe.domain;
> JpaProductRepository를 infra패키지로 옮기지 않은 이유가 있으실까요? 🤔

ProductRepository가 domain 패키지에 있어서 JpaProductRepository도 같이 있어야 생각했나봅니다.
질문 주신 부분을 확인하고 JpaProductRepository를 다시 봤을 때 Jpa라이브러리를 import 하는 부분들 확인했습니다.

domain 패키지 영역은 외부 라이브러리를 import 하지 않는 영역으로 만들기 위해선 
JpaProductRepository해당 파일을 다른곳으로 이동시켜야 하는것을 알았습니다.

왜 이동시켜야 할까? 라고 생각해봤을 때 Jpa를 사용하지 않고 Mybatis를 사용하려고 할 때는 JpaProductRepository가 필요 없겠다 라는 생각이 들었습니다.

@HackSung