🚀 3단계 - 리팩터링(매장 식사 주문)
next-step/ddd-tactical-design pull request #294
Opened 2024-06-02 13:49 UTC by mj950425

안녕하세요 리뷰어님.

이번에도 잘부탁드립니다!

2024-06-04 14:51 UTC, kyucumber requested changes
매장 식사 주문 리팩터링 잘 구현해주셨습니다.

DM 주신 부분과 관련해 몇가지 코멘트 남겨두었어요. 나머지 부분은 잘 구현해주셔서 남길만한 부분이 많진 않네요!

내용 확인하고 다시 요청 주시면 머지하도록 하겠습니다.

2024-06-04 14:51 UTC, kyucumber commented on src/main/kotlin/kitchenpos/tobe/eatinorder/domain/entity/OrderTableV2.kt
> +        ): OrderTableV2 {
중요한 부분은 아니지만, 저번에 정적 팩터리 네이밍 관련 코멘트를 남겨드린 것 같은데 계속 섞어서 사용하시는 것 같네요.

from은 한개, of는 여러개의 매개변수를 받는 부분이 혼란스러우시다면 차라리 of만 쓰거나 create 등의 이름을 지으시는건 어떨까요?

2024-06-04 14:51 UTC, kyucumber commented on src/main/kotlin/kitchenpos/tobe/eatinorder/domain/EatInOrderCompleteService.kt
> +class EatInOrderCompleteService(
중요한 부분은 아니지만 응용 서비스와 구분을 위해 아래와 같이 하기도 해요.

```suggestion
class EatInOrderCompleteDomainService(
```

2024-06-04 14:51 UTC, kyucumber commented on src/main/kotlin/kitchenpos/tobe/eatinorder/domain/EatInOrderCompleteService.kt
> +        return eatInOrder.id
주문이 완료되지 않았는데 테이블 초기화 요청이 온 경우는 정상적인 상황은 아닐 것 같은데요.

예외 처리 등을 하지 않아도 괜찮을까요?

지금은 아무 예외 없이 clear만 호출되지 않을 것 같아요.

2024-06-04 14:51 UTC, kyucumber commented on src/main/kotlin/kitchenpos/tobe/eatinorder/application/dto/response/GetOrderResponse.kt
> +    val orderStatus: EatInOrderStatus,
DM으로 질문 주셨었는데 지금은 컨트롤러 응답 객체에 도메인에 존재하는 enum을 참조하도록 구성해주셨네요.

방법은 여러가지 일 것 같아요.

1. 모듈이 나뉘진 않았기 때문에 도메인에 둔 뒤 컨트롤러에서 enum을 참조한다.
2. 컨트롤러쪽 패키지에 별도의 enum을 둔 뒤 한번 더 변환해서 사용한다.
3. 도메인에 필수적인 enum이라면 도메인 관련 모듈(패키지)를 만들어 enum을 넣어두고 import 하거나(모듈인 경우) 의존해서 사용한다.


현재 1번 방법으로 해주셨는데 enum은 언제든 뜯어내거나 하기 어렵지 않아서 모듈이 나뉘기 전이라면 저도 1번 방법을 사용할 것 같습니다.

모듈이 나뉘면 상황에 따라 2, 3번을 선택해주시면 될 것 같아요.

2024-06-04 14:51 UTC, kyucumber commented on src/main/kotlin/kitchenpos/tobe/eatinorder/infra/MenuClientImpl.kt
> +class MenuClientImpl(
eatinorder 패키지에 두셨네요. 질문 주신 부분에 대해 추가로 여기 코멘트를 남기면

만약에 menu 도메인이 별도의 MSA로 구성되어 있다고 보면 menu쪽에 구현체가 있으면 참조하거나 사용할 수 없습니다.
따라서 eatinorder 패키지의 infra에 menu를 조회하기 위한 구현체가 있어야 합니다.

2024-06-05 15:04 UTC, mj950425 commented on src/main/kotlin/kitchenpos/tobe/eatinorder/domain/entity/OrderTableV2.kt
> +        ): OrderTableV2 {
아하~ 리뷰어님의 코멘트를 반대로 이해했네요 😅

평소에는 create로 생성하는데, 이번에는 학습이 목적인 미션이니깐 from, of로 알맞게 수정해보겠습니다.

2024-06-05 15:05 UTC, mj950425 commented on src/main/kotlin/kitchenpos/tobe/eatinorder/domain/EatInOrderCompleteService.kt
> +class EatInOrderCompleteService(
서비스 이름부터 명시적으로 도메인과 관련되어있음을 나타내는것이군요~ 수정해두겠습니다.

2024-06-05 15:05 UTC, mj950425 commented on src/main/kotlin/kitchenpos/tobe/eatinorder/domain/EatInOrderCompleteService.kt
> +        return eatInOrder.id
놓쳤네요. 수정해둘게요~

2024-06-05 15:51 UTC, kyucumber approved these changes
마지막 리팩터링까지 잘 마무리해주셨습니다. 수고 많으셨어요. 🙇

2024-06-05 15:51 UTC, merged