🚀 1단계 - 리팩터링(상품)
next-step/ddd-tactical-design pull request #300
Opened 2024-06-04 09:13 UTC by hoa0217

안녕하세요 리뷰어님.
상품 리팩토링 완료하여 PR 올립니다.
tobe 패키지를 만들어서 Product를 수정한 후 Create,Update Request까지 생성하여 ui, application 계층까지 수정완료하였습니다.
> 메뉴는 아직 수정할 때가 아닌거같아 관련된 메뉴로직은 최대한 수정하지 않는 방향으로 작성했습니다.

그리고 미션을 진행하며 아래와 같은 고민이 생겨 질문드립니다.

감사합니다.

### 질문사항
- Product의 Price를 업데이트할 경우 Domain계층의 불변객체인 Price클래스를 사용할까싶다가 Domain이 표현계층까지 사용되는것은 옳지 않은방향같아서 Request를 따로 생성했습니다. 불변객체의 경우 표현계층까지 사용해도 괜찮을까요?
- Name validation의 경우 PurgomalumClient(도메인 서비스)가 필요하여 이를 생성자에 주입받도록 구현하였습니다. 사실 생성자에 프로퍼티를 제외한 값을 주입해본적이 처음인데 맞는 방향일지 궁금합니다.

2024-06-05 11:04 UTC, liquidjoo requested changes
안녕하세요 정화님 :)
1단계 미션 잘해주셨어요 👍 
몇 가지 코멘트 남겼습니다~
확인하고 다시 요청 주세요 🙇

2024-06-05 11:04 UTC, liquidjoo commented on src/main/java/kitchenpos/products/domain/tobe/Name.java
> +    }
기본 생성자는 접근제어자로 제어해보면 좋을 것 같아요 :)

2024-06-05 11:04 UTC, liquidjoo commented on src/main/java/kitchenpos/products/domain/tobe/Name.java
> +    }
주입 받는 것은 문제 되지 않을 것 같습니다만 서비스에서 부터 도메인까지 파라미터를 계속 가져가야하는 부분은 조금 신경쓰일 수 있을 것 같아요 :)
저는 이럴 땐 서비스 영역에서 처리하고 도메인엔 영향을 최소화 하려고 합니다!

2024-06-05 11:04 UTC, liquidjoo commented on src/main/java/kitchenpos/products/domain/tobe/Product.java
> +    }
기본 생성자는 접근제어자를 통해 제어해보아요~

2024-06-05 11:04 UTC, liquidjoo commented on src/main/java/kitchenpos/products/ui/dto/PriceUpdateRequest.java
> +public class PriceUpdateRequest {
불변 객체로 표현하신다면 도메인에서 사용해도 상관은 없다고 생각은 하고 있습니다!
> https://curiousjinan.tistory.com/entry/spring-data-transfer-vo-dto

2024-06-05 11:04 UTC, liquidjoo commented on src/main/java/kitchenpos/products/ui/dto/PriceUpdateRequest.java
> +    private BigDecimal price;
불변객체를 활용한다면 final 키워드를 사용해보면 좋을 것 같아요~

2024-06-05 11:04 UTC, liquidjoo commented on src/main/java/kitchenpos/products/ui/dto/ProductCreateRequest.java
> +    private BigDecimal price;
불변 객체를 활용하면 좋습니다 :)
다만 좀 더 확실하게 final 키워드를 사용해 보시면 좋을 것 같네요

2024-06-05 11:04 UTC, liquidjoo commented on src/main/java/kitchenpos/products/ui/dto/ProductCreateRequest.java
> +    }
생성자와 팩토리메서드 패턴을 같이 사용하는 것을 지양하고 있는데요~ 어떤 이유가 있을까요?

2024-06-05 11:04 UTC, liquidjoo commented on src/test/java/kitchenpos/products/domain/tobe/ProductTest.java
> +class ProductTest {
꼼꼼한 테스트 케이스 👍

2024-06-06 02:46 UTC, hoa0217 commented on src/main/java/kitchenpos/products/domain/tobe/Name.java
> +    }
네 맞습니다 서비스에서 주입받은 클라이언트를 도메인까지 가져가야하는게 찝찝하더라구요~ 답변 감사합니다!

2024-06-06 02:47 UTC, hoa0217 commented on src/main/java/kitchenpos/products/ui/dto/PriceUpdateRequest.java
> +    private BigDecimal price;
final !! 감사합니다

2024-06-06 02:56 UTC, hoa0217 commented on src/main/java/kitchenpos/products/ui/dto/ProductCreateRequest.java
> +    }
dto -> entity 변환 시 getter를 통해 데이터를 꺼내어 직접 생성자를 호출하는 것 보다, dto 내부에서 값을 활용해 엔티티로 변환하는게 더 편하다 생각하여 코드를 작성하였습니다~ 혹시 생성자와 팩토리메서드 패턴을 같이 사용하면 안되는 이유가 있을까요? 참고할만한 문서있다면 읽어보겠습니다!!!

2024-06-06 02:57 UTC, hoa0217 commented on src/main/java/kitchenpos/products/ui/dto/PriceUpdateRequest.java
> +public class PriceUpdateRequest {
그럼 해당 Update Request는 삭제하도록하겠습니다!! 감사합니다

2024-06-06 03:27 UTC, hoa0217 commented
### 변경 사항
- [x] 기본생성자 접근제어자(`protected`)설정
- [x] `Name` 생성 시 `purgomalumClient` 주입 제거
- [x] `PriceUpdateRequest` 클래스 삭제 및 `Price` 클래스 사용하도록 변경
- [x] `ProductCreateRequest` 프로퍼티 불변객체로 변경
- [x] `ProductCreateRequest` 에게 `Name` Validation 로직 위임
- [x] `PurgomalumClient` -> `ProfanityValidator`로 클래스명 변경 (구현에 의존적이지 않은 이름)
- [x] `Name` -> `ProductName`, `Price` -> `ProductPrice`로 클래스명 변경 (모델링 관점 이름)
- [x] 모델링 클래스 다이어그램 수정

2024-06-06 18:39 UTC, liquidjoo commented on src/main/java/kitchenpos/products/ui/dto/ProductCreateRequest.java
> +    }
팩토리메서드 패턴을 사용하는 경우는 생성자를 제어하는 경우가 많이 있습니다 :)
생성자를 제어함에 있어서 유효성을 검증해야하는 경우도 있는데요
이럴 때 유효성을 검증하는 메서드패턴을 사용하는 경우와 생성자만 사용했을 경우 차이가 있기 때문에
둘 중 하나를 사용하지 않는 것이 일반적이긴 합니다

2024-06-06 18:40 UTC, liquidjoo approved these changes
안녕하세요 정화님 :)
피드백 반영 잘해주셨어요 👍 
질문 주신 내용 코멘트로 남겼습니다~
다음 단계 진행해 주세요 🙇

2024-06-06 18:40 UTC, merged

2024-06-06 18:58 UTC, liquidjoo commented on src/main/java/kitchenpos/products/ui/dto/ProductCreateRequest.java
> +    }
앗 이부분은 제가 실수한 것 같네요! 같은 생성자 인줄 알았습니다 😭