🚀 3단계 - 리팩터링(매장 식사 주문)
next-step/ddd-tactical-design pull request #309
Opened 2024-06-09 05:08 UTC by kkt219a

안녕하세요 성주님 :) 마지막 미션 잘부탁드립니다.
이번 미션에서는 다음 고민을 했습니다.

### 주문 등록에만 필요한 경우
실제 존재하는 메뉴와 테이블인지 확인하기 위해 주문을 등록하는 과정이 복잡해서 주문의 생성만 담당하는 책임을
주문생성자에게 분담했습니다. 제가 생각했을 땐, 메뉴의 가격과 테이블이 사용중인지 등은 등록하는 과정에서만
필요한 것이고 이후 주문의 상태를 관리하는 레벨에서는 필요하지 않다고 생각되어 별도로 매장식사 주문 애그리거트와
관계를 맺지않았는데요. 이 부분에 대해 어떻게 생각하실지 궁금합니다!

2024-06-10 03:32 UTC, liquidjoo requested changes
안녕하세요 규태님 :)
3단계 미션 잘해주셨어요~
몇 가지 코멘트 남겼습니다
확인하고 다시 요청해 주세요 🙇

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
> +  private final OrderTableReader orderTableReader;
테스트에 구현체를 두는 것도 좋지만! 실질적으로 구현체가 있으면 더욱 좋을 것 같아요 :)

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
> +    List<OrderLineItemCreateCommand> orderLineItemList = command.getOrderLineItems();
변수명에 List 보단 복수를 사용하는 것이 좋습니다 :)

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
> +  }
책임을 조금 더 나누어 보면 어떨까요?
> 유효성 검증, 데이터 조회/생성을 더 세분화 하여 나누어 보면 좋을 것 같아요

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderLineItemQuantity.java
> +public class EatInOrderLineItemQuantity {
```suggestion

@Embeddable
public class EatInOrderLineItemQuantity {
```

해당 어노테이션이 있으면 더욱 좋지 않을까요?

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/create_support/OrderedMenu.java
> +public class OrderedMenu {
자바에선 패키지 이름에 _(언더바) 를 사용을 지양하고 있습니다 :)
create_support 보단 다른 이름을 지어보면 어떨까요?

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/dto/OrderCreateCommand.java
> +public class OrderCreateCommand {
create_support 패키지 내에 있는 객체와 혼용이 되기 쉬울 것 같아요
하나로 만들어 네이밍을 통해 명확히 분리해보면 어떨까요?

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/event/OrderCompletionEvent.java
> +  }
이벤트를 발생 후 리스너를 만들어 별도로 처리해줘야할 것 같은데요
해당 로직도 구현이 되어있을까요?
> 찾기가 어렵네요!
> 이벤트를 사용하는 것은 좋으나 이벤트에 대한 정의를 따로 문서화 시켜주는 것도 중요합니다 
> 이벤트 발행과 수행에 있어 코드의 흐름이 일관적이지 않기에 오히려 복잡하게 만드는 경우가 많이 있습니다

2024-06-10 03:32 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order_table/OrderTable.java
> +package kitchenpos.eatinorders.tobe.domain.order_table;
패키지 명은 변경해주세요 :)

2024-06-10 03:32 UTC, liquidjoo commented on src/test/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreatorTest.java
> +class EatInOrderCreatorTest {
매장주문이 있으면 배달주문, 포장주문 또한 도메인으로 나올 수 있지 않을까요?

2024-06-11 08:34 UTC, kkt219a commented
다른 부분들은 반영했습니다!
이벤트리스너는 도메인 안에서만 의존성 처리가 가능할 것 같아 도메인 레이어에서 바로 뺐습니다!
createsupporter 부분은 합치려 해보았으나 한쪽에서는 실제 존재하는 걸 조회해서 검증하는 부고
한쪽은 주문 생성에 필수적인 부분들이라 합치는 게 어려운 것 같습니다 ㅠㅠ 그래서 createsupporter쪽
객체를 이름을 통해 좀 더 명시적으로 나타냈습니다

2024-06-13 00:10 UTC, liquidjoo approved these changes
안녕하세요 규태님 :)
3단계 피드백 잘 반영해주셨어요 👍 
저와 함께 했던 리뷰들이 도움이 되었길 빌며 마무리하겠습니다
수고하셨습니다 🙇

2024-06-13 00:10 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
> +import kitchenpos.eatinorders.tobe.domain.order.createsupporter.RegisteredMenuReader;
피드백 반영 좋습니다 :)

2024-06-13 00:10 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
> +  private final RegisteredOrderTableReader registeredOrderTableReader;
직관적인 이름이라 코드를 이해하기 더욱 편한 것 같아요 👍

2024-06-13 00:10 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
> +  }
메서드 분리 👍

2024-06-13 00:10 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
>    }
후에 검증할 것이 많아지면 도메인 서비스를 활용해 보아도 좋을 것 같아요!

2024-06-13 00:10 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderLineItemQuantity.java
> +@Embeddable
👍

2024-06-13 00:10 UTC, liquidjoo commented on src/main/java/kitchenpos/eatinorders/tobe/infra/RegisteredOrderTablePackageReader.java
> +    kitchenpos.eatinorders.domain.OrderTable orderTable = orderTableOptional.get();
패키지를 임포트해서 코드의 가시성을 높이면 좋을 것 같아요~

2024-06-13 00:10 UTC, merged

2024-06-13 12:32 UTC, kkt219a commented on src/main/java/kitchenpos/eatinorders/tobe/domain/order/EatInOrderCreator.java
>    }
맞아요 ㅠㅠ creator쪽에 책임이 좀 많은데 검증할 내용이 더 많아지면 validator 분리가 필요할 거라고 느꼇습니다!🤔🫠😊