🚀 2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #323
Opened 2024-06-26 06:00 UTC by gutenLEE

### 구현 내용
- `MenuService` 도메인 로직을 도메인 엔티티로 이동
- `ProductService`의 `Menu` 의존성 부분을 인터페이스를 통해 요청하도록 변경

### 질문
- MenuProduct, Product 의 BC 간 협력 방식을 결정하는게 어려웠습니다. 저는 아래 그림처럼 패키지간 양방향 참조가 발생했습니다...
안티패턴이 맞을까요? 그렇게 생각한 이유는 실무에서 이렇게 구현하면 구현체를 막 가져다 쓰게되서 결국 클래스간 순환참조가 발생했습니다.. 
아직 4주차 강의를 듣지 않고 구현해봤는데 듣고 다시 구현해보겠습니다!

![image](https://github.com/next-step/ddd-tactical-design/assets/61870748/880c1bb3-4514-4914-8665-ce2b6155b6ff)

2024-06-29 09:05 UTC, sah3122 requested changes
메뉴 리팩터링 잘해주셨습니다 👍 
몇가지 고민거리를 남겨두었는데 확인 부탁드려요 🙏

2024-06-29 09:05 UTC, sah3122 commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        }
MenuProducts.of 에서 모델링을 만족하게 구현해주셨네요 👍 
해당 catch 구문이 필요한 이유가 있을까요?

2024-06-29 09:05 UTC, sah3122 commented on src/main/java/kitchenpos/menus/tobe/application/DefaultMenuDisplayService.java
> +public class DefaultMenuDisplayService implements MenuDisplayService {
MenuDisplayService 는 Product Context에 정의하고 Menu Context에 구현체가 존재하여 양방향 의존 구조가 생겼다고 볼수 있을것 같습니다 😄 
개인적으로 이러한 구조에서는 도메인 서비스를 필요로 하는 컨텍스트에 구현체를 두는 방법으로 구현하곤 합니다. 
약한 결합을 유지하기 위한 이벤트를 발행하는것도 하나의 선택지가 될수 있을것 같아요 😄

2024-06-29 09:05 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/application/DefaultProductPriceService.java
> +public class DefaultProductPriceService implements ProductPriceService {
다른 코멘트를 참고 해주세요 😄

2024-06-29 09:05 UTC, sah3122 commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    public void display(ProductPrices productPrices) {
display를 호출하는 경우 매번 ProductPrices에 대한 검증이 필요할지 고민해보세요 😄

2024-06-29 09:05 UTC, sah3122 commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        MenuProducts.of(menuProducts, toPrice, productPrices);
마찬가지로 매번 ProductPrices 가 필요할지 고민해보면 좋을것 같아요. 
ProductPrices가 필요한 경우는 Product의 가격이 변경됨에 따라 모델링을 만족하는지 판단하기 위함이라고 볼수 있습니다. 
Menu 가격이 변경됨에 따라 매번 ProductPrices 가 필요한 상황은 아니라고 생각해요 😄

2024-06-29 09:05 UTC, sah3122 commented on src/main/java/kitchenpos/menus/tobe/domain/MenuProduct.java
> +    private UUID productId;
Product와의 약한 결합 유지 👍

2024-06-30 14:26 UTC, gutenLEE commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        }
`MenuProduct` 에서 던지는 예외와 `Menu` 에서 던지는 예외가 달라서 
예외 치환?하기 의도였는데 통일하였습니다!

2024-06-30 15:08 UTC, gutenLEE commented
피드백 주신대로 `Menu` 컨텍스트에서 `ProductPrices` 가 필요한지 다시 고민해보고
`MenuProduct` 에 `price` 필드를 추가만 했는데 패키지간 결합도가 제거되는 효과를 경험했습니다..

구현에 매몰되지 않고 도메인 모델링을 잘 고민하고 준수해야 되겠다는 것을 느꼈습니다!

2024-07-04 00:36 UTC, sah3122 approved these changes
리뷰 확인이 늦어 피드백이 오래 걸렸습니다 🙏 
몇가지 코멘트 남겨두었는데 다음 미션을 진행하며 반영 부탁드려요 😄

2024-07-04 00:36 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/application/ProductService.java
> +import kitchenpos.menus.tobe.application.MenuDisplayPolicy;
MenuDisplayPolicy 의 위치가 menu 패키지에 선언되어 있는데, 개인적으로는 도메인 서비스는 호출하는 package. context에 위치하는것을 선호합니다. 
잘 분리된 context는 하나의 마이크로서비스로 독립할수 있어야한다고 생각하며, 마이크로 서비스로 분리되는 경우 도메인 서비스가 다른 패키지에 있다면 구조 변경이 일어나야 합니다. 
도메인 서비스의 위치에 관해 고민해보세요 😄

2024-07-04 00:36 UTC, sah3122 commented on src/main/java/kitchenpos/menus/tobe/domain/MenuProduct.java
> +import kitchenpos.products.tobe.Money;
Money라는 ValueObject를 컨텍스트별로 별도로 선언하거나 공유 터널과 같이 공유할수 있는 통로를 만드는것도 좋을것 같아요 😄

2024-07-04 00:36 UTC, sah3122 commented on src/main/java/kitchenpos/menus/tobe/domain/MenuProduct.java
> +    private Money productPrice;
ProductPrice를 MenuProduct에서 선언하였기 때문에 Product의 가격 변경시 MenuProduct의 가격도 변경되어야 하는 구조가 되었습니다. 
Product 가격 변경시 MenuProduct도 변경이 될수 있게 코드를 추가해야할것 같아요!

2024-07-04 00:36 UTC, merged