Step1 리팩토링(상품)
next-step/ddd-tactical-design pull request #78
Opened 2022-04-02 05:13 UTC by bactoria

상품 리팩토링 하였습니다.
- 도메인엔티티와 JPA엔티티를 분리하여 미션을 진행해보고자 합니다.
- 도메인이벤트는 다음 미션에서 진행하면 좋을 것 같아 별도로 생성하지 않았습니다.

2022-04-02 05:16 UTC, bactoria commented on src/main/java/kitchenpos/products/tobe/domain/ForbiddenWordCheckPolicy.java
> +public interface ForbiddenWordCheckPolicy {
`도메인서비스`라고 생각하여 만들어보았어요. 
이 정책은 `ProductName` 에서 사용하게되는데, 어색한 부분이 있다면 말씀주세요!

2022-04-02 05:16 UTC, bactoria commented on README.md
> +  - 상품의 이름은 비워 둘 수 없다.
메뉴에는 이름을 비워둘 수 없는 요구사항이 있던데, 
상품에도 이름을 비워둘 수 없으면 좋을 것 같아 추가해보았습니다.

2022-04-03 10:31 UTC, sah3122 requested changes
안녕하세요. 첫번째 미션 리뷰를 맡게된 이동철 입니다 😄 
상품 리팩토링 너무 잘해주셨네요 👍 
간단한 생각거리들 몇가지 남겨두었는데 확인부탁드려요. 🙏

2022-04-03 10:31 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/domain/ForbiddenWordCheckPolicy.java
> +public interface ForbiddenWordCheckPolicy {
도메인 서비스라고 정의해주신 이유가 있을까요 ?

2022-04-03 10:31 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/domain/ProductName.java
> +	public ProductName(String name, ForbiddenWordCheckPolicy forbiddenWordCheckPolicy) {
생성자 호출시 Policy를 전달하는 방법 좋네요 ㅎㅎ
저도 선호하는 방법입니다 😄

2022-04-03 10:31 UTC, sah3122 commented on README.md
> +  - 상품의 이름은 비워 둘 수 없다.
추가 요구사항 너무 좋네요 👍

2022-04-03 10:31 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
JPA를 활용해주실거라고 하셨는데, 실제로 JPA 문법에 맞추어 작성해보는건 어떨까요 ? 
아마 JPA와 DDD의 개념이 부합하지 않는 부분들이 있을거에요. 그러한 부분들까지 경험해보세요 !

2022-04-03 10:31 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +	}
현시점에서 getter를 제공해야할 필요가 있을까요 ?

2022-04-03 10:31 UTC, sah3122 commented on src/test/java/kitchenpos/products/tobe/domain/ProductNameTest.java
> +class ProductNameTest {
깔끔한 테스트 코드 작성 👍

2022-04-16 02:14 UTC, bactoria commented on src/main/java/kitchenpos/products/tobe/domain/ForbiddenWordCheckPolicy.java
> +public interface ForbiddenWordCheckPolicy {
'상품 이름에는 금칙어가 포함될 수 없다' 라고 하는 요구사항은 도메인레이어에서 표현되어야한다고 생각하였는데요.

만들고 보니 값을 포함하지 않아서 `엔티티`/`VO` 는 아니라고 생각하였는데요.

상태를 가지지도 않는 오퍼레이션만을 가지고 있어서 도메인서비스 일 것이라는 생각이 들더라고요.

DDD 책을 살펴보아도 이것을 도메인서비스 라고 단정짓기가 어렵네요.. 😢

혹시 이견이 있으실까요?

2022-04-16 02:15 UTC, bactoria commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
Jpa 사용 시 `ProductJpaEntity` 라고 하는 클래스를 별도로 만들 예정이에요.
도메인 엔티티인 `Product` 를 JPA문법에 맞추어 작성해야 할 이유가 있을까요?

2022-04-16 02:22 UTC, bactoria commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +	}
제거하였습니다. 👍 [dc5ac21](https://github.com/next-step/ddd-tactical-design/pull/78/commits/dc5ac21f92aa3763c0006fd7e3c9be588e36f609)

`getPrice()` 는 테스트 편의를 위해 남겨두었어요.

2022-04-17 08:33 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
다음 미션을 진행해주세요 !

2022-04-17 08:33 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/domain/ForbiddenWordCheckPolicy.java
> +public interface ForbiddenWordCheckPolicy {
도메인에서 책임져야하는 정책들을 도메인 서비스로 표현하기도 합니다 :) 
도메인 서비스로 정의해주신 이유가 궁금해서 남겨드린 코멘트 였어요 😄

2022-04-17 08:33 UTC, sah3122 commented on src/main/java/kitchenpos/products/tobe/domain/Product.java
> +public class Product {
제가 코멘트를 잘못 이해했네요 😢 
이번 미션을 진행하면서 JpaEntity와 도메인을 분리하여 진행하는것은 좋은 방법이라고 생각해요 👍

2022-04-17 08:33 UTC, merged