[Step2 메뉴] 리팩터링 1차 PR
next-step/ddd-tactical-design pull request #85
Opened 2022-04-05 19:04 UTC by mynameisdaun

안녕하세요 시훈님,
PR 요청드립니다!

2022-04-09 15:11 UTC, sihoony requested changes
미션 수행 잘해주셨습니다.
몇가지 코멘트 남겼으니 확인해주세요.

좋은 하루 되세요~ 😄 😸

2022-04-09 15:11 UTC, sihoony commented on src/main/java/kitchenpos/menus/application/TobeMenuService.java
> +        return menu.changePrice(request.getPrice(), request.getPricingRule());
price는 룰을 이용하여 Price 체크하도록 되어있습니다.
pricingRule이 Menu에서 체크하기 보다는 Price에서 진행해 보는건 어떨가요?
조금더 명확해 질 것 같습니다.

2022-04-09 15:11 UTC, sihoony commented on src/main/java/kitchenpos/menus/dto/MenuPriceChangeRequest.java
> +    }
Request가 PricingRule를 제공하는 방식 보다는 service단에서 진행해 보는건 어떨까요?
레이어마다 책임이 명확해 질것 같습니다.

2022-04-13 03:19 UTC, mynameisdaun commented
안녕하세요 시훈님,
코멘트 반영하여 재 작성해보았습니다.

Request가 PricingRule를 포함하고 있는것은 인프라의 구성요소를 인지하고 있는 것과 같은것 같습니다.
Service단에서 포함하고 있다면 어떨까요~?
Request는 In 데이터의 데이터를 전달하면 좋을 것 같습니다.
->>서비스 영역으로 이동

price는 룰을 이용하여 Price 체크하도록 되어있습니다.
pricingRule이 Menu에서 체크하기 보다는 Price에서 진행해 보는건 어떨가요?
조금더 명확해 질 것 같습니다.
->> Validation로직 VO 로 이동

시훈님의 코멘트, 어제 수업을 듣고 코드의 골격이 많이 수정되었습니다.
1. Policy, Rule -> 삭제
과한 오버엔지니어링이라고 생각되어 삭제하였습니다. 그리고 Validation 로직을 전부 VO 내부로 이동하였습니다.

2. 도메인서비스의 구현
->> 중점적으로 피드백 받고싶은 부분입니다! 
올바르게 구현되었는지 궁금합니다 
해당부분에 추가로 코멘트 남겨놓겠습니다.

감사합니다!

2022-04-13 03:23 UTC, mynameisdaun commented on src/main/java/kitchenpos/products/domain/tobe/domain/ProductPriceChangeService.java
> +
@sihoony
시훈님!
도메인 서비스를 생각하고 구현한 코드인데 피드백 부탁드려도 될까요?
1. 패키지 위치
2. 의존관계
3. 구현 디테일

부족한 점이 없지 않은지 여쭙고 싶습니다

감사합니다!

2022-04-13 15:19 UTC, sihoony commented
안녕하세요. 다운님, 이전 리뷰때 커밋 메시지에 대한 피드백이 없었네요. 😢 
커밋은 작은 단위로 잘 작성해 주셨습니다. 팀마다, 회사마다 다를순 있을 것 같으나, 저희팀의 이야기를 공유해 드립니다.

- 하나의 기능 단위로 커밋을 진행한다.
- 기능 단위에는 테스트 코드를 포함한다.
- 메시지는 명확하게 작성하고 Jira티켓이 있다면 같이 포함하여 작성한다.

정도로 정리가 되겠네요~^^ 리뷰전에 코멘트 먼저 남깁니다. 리뷰는 내일 진행할께요.
좋은 하루 되세요 😄 😸

2022-04-15 15:32 UTC, sihoony requested changes
피드백 잘반영해 주셨습니다. 💯 
몇가지 코멘트를 남겼으니 확인 부탁드립니다.

좋은 하루 되세요~ 😄 😸

2022-04-15 15:32 UTC, sihoony commented on src/main/java/kitchenpos/menus/domain/tobe/domain/TobeMenu.java
> +    }
정적 메소드가 아니라도 동일 로직을 구현할 수 있을 것 같습니다.
`getSumOfMenuProductAmount`의 경우, `List<TobeMenuProduct> menuProducts`를 일급객체로 작성된다면 역할이 명확해질 것 같습니다. ( 일급객체에서 합산을 진행 )
`checkPriceIsGreaterThanSumOfMenuProductAmount`의 경우에도 static이 아니더라도 충분히 사용가능할 것 같습니다^^

정적 메소드에 대한 의견들을 첨부합니다. 생각해볼만한 내용입니다~^^
- https://mygumi.tistory.com/253
- https://tecoble.techcourse.co.kr/post/2020-07-16-static-method/

2022-04-15 15:32 UTC, sihoony commented on src/main/java/kitchenpos/menus/domain/tobe/domain/TobeMenu.java
> +    }
일급컬렉션
- https://johannes93.tistory.com/11?category=967356

2022-04-15 15:35 UTC, sihoony commented on src/main/java/kitchenpos/products/domain/tobe/domain/ProductPriceChangeService.java
> +
리뷰가 늦어져 죄송합니다.
조금더 디테일하게 확인해서 피드백 드렸습니다.
궁금하신 점은 DM으로 이야기해봐도 좋을 것 같습니다.

2022-04-21 02:46 UTC, mynameisdaun commented
안녕하세요 시훈님,
리뷰 요청드립니다.

1. MenuProducts 일급 컬렉션 사용
2. @Valid 어노테이션 사용
3. 한줄에 . 하나만 사용하기 반영하여 리팩토링해보았습니다.

다만, 
https://github.com/next-step/ddd-tactical-design/pull/85#discussion_r851315495
이부분을 수정하려고 여러가지 글을 찾아봤을때
https://galid1.tistory.com/608
이런 글들을 확인할 수 있었고,
IDE에서도, @Embedeed로 하면 에러가 나더라구요.. 혹시 제가 모르는 좋은 방법이 있으면 피드백 부탁드리겠습니다!

지난 피드백 너무 자세했고,
과제 제출에 너무 도움이 되었습니다. 
감사합니다!

2022-04-22 15:06 UTC, sihoony approved these changes
피드백 잘 반영해 주셨습니다. 💯 
다음 미션에서도 화이팅입니다. 

즐거운 주말 되세요~ 😄 😸

2022-04-22 15:06 UTC, sihoony commented on src/main/java/kitchenpos/menus/ui/TobeMenuGroupRestController.java
> +        }
TIP : 반복적인 로직들이 늘어난다면 RestControllerAdvice를 이용하여 처리를 할 수도 있습니다.

- https://gaemi606.tistory.com/entry/Spring-Boot-ControllerAdvice%EB%A1%9C-Exception-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0

2022-04-22 15:06 UTC, merged