<step3> 리펙토링(매장주문)
next-step/ddd-tactical-design pull request #90
Opened 2022-04-07 13:12 UTC by seok-2-o

안녕하세요 규남님
마지막 과제 제출합니다.

이번에도 마찬가지로 메뉴와 연관성을 끊으려 노력했습니다.

이번 미션을 진행하면서 몇가지 궁금한 것은 아래와 같습니다.
주문 - 메뉴 같은경우에는 상품 - 메뉴 관계와는 또 다르게 메뉴의 변경이 주문에 영향을 주면 안된다고 생각하는데
이럴때는 생성시에만 참조하면 되는걸까요?
그렇다면 가격 외에 메뉴의 이름(상품의이름) 등을 스냅샷할 필요성이 있을까요?

테이블은 매장주문과 라이프사이클이 같다고 생각하여 직접참조 하였는데 
해당부분에 대해서 규남님은 어떻게 생각하시는지 궁금합니다.

피드백 잘 부탁드리겠습니다.

2022-04-07 23:55 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2022-04-07 23:55 UTC, kyucumber commented on src/main/java/kitchenpos/eatinorders/tobe/domain/dto/CreatOrderLineItemCommand.java
> +package kitchenpos.eatinorders.tobe.domain.dto;
```
이번 미션을 진행하면서 몇가지 궁금한 것은 아래와 같습니다.
주문 - 메뉴 같은경우에는 상품 - 메뉴 관계와는 또 다르게 메뉴의 변경이 주문에 영향을 주면 안된다고 생각하는데
이럴때는 생성시에만 참조하면 되는걸까요?
그렇다면 가격 외에 메뉴의 이름(상품의이름) 등을 스냅샷할 필요성이 있을까요?
```

주문에 남는 메뉴 정보는 이후 메뉴가 수정되더라도 이때 당시 주문 기록에 영향을 주면 안되니, 생성 시 참조 역할만 수행하고
변경에 따라 영향을 받지 않기 위해 스냅샷을 별도로 남길 필요가 있냐는 말씀으로 이해했습니다.

사실 여러가지 방법이 있을 것 같네요, 뭐가 가장 좋은 방법인지는 저도 잘 모르겠네요 상황에 따라 다른 전략을 택해야 할 것 같아요 🤔 

제가 생각한 방법은 아래 정도가 될 것 같은데요, 첫번째는 말씀하신 부분과 동일한 방법인 것 같아요. 현재로선 이게 제일 무난한 방법이 아닐까 싶습니다.

1. OrderLineItem에서 MenuId만 참조하고 메뉴의 이름, 속한 메뉴 그룹, 상품 이름들을 별도로 스냅샷 형태로 남기고 활용한다.
2. Menu를 그대로 참조하고, Menu의 변경 이력을 별도로 저장한다.
3. 주문 생성은 현재 상태를 유지, 주문 이력 조회를 위한 모델을 분리하고 읽기 모델에는 메뉴 이름, 상품 이름 등을 포함시킨다.

```
테이블은 매장주문과 라이프사이클이 같다고 생각하여 직접참조 하였는데
해당부분에 대해서 규남님은 어떻게 생각하시는지 궁금합니다.
```

요건 사람마다 생각이 다르겠지만, 저는 테이블과 주문 생성의 라이프사이클이 같다고 생각하진 않아서 완전하게 라이프사이클이 일치한다고 보기는 어려운 것 같아요. 

> 테이블 생성과 주문의 생성은 별개로 이루어지기 때문에 요렇게 생각했습니다.

따라서 저는 직접 참조가 아니라 id로 약 참조를 하는 것을 선호할 것 같습니다. 다만 약 참조를 하는 경우 여러가지 번거로운 점이  많기 때문에 지금과 같은 상황이라면 직접 참조 하는것도 괜찮은 선택일 수 있습니다.

요건 참고만 하시고, 필요하다면 변경해주셔도 될 것 같아요. 반영하지 않으셔도 괜찮습니다!

2022-04-07 23:55 UTC, kyucumber commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/OrderLineItems.java
> +        if (items.size() != menus.size()) {
코드를 보다가 문득 사이즈가 같더라도 아래와 같이 들어있으면 제대로 검증이 되지 않겠다는 생각이 들었어요

```
items [menuId: "1234", menuId: "2345", menuId: "3456"]
```

```
menus [ "1111", Menu1, "2222", Menu2, "3333", Menu3]
```

위 경우 사이즈는 같지만 UUID가 달라 이 검증 부분에서 제대로 검증이 되지 않을 것 같아요

2022-04-07 23:55 UTC, kyucumber commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/OrderTable.java
> +        }
중요한 부분은 아니지만, 요 부분을 함수로 분리해보아도 좋을 것 같네요!

2022-04-07 23:55 UTC, kyucumber commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/TableOrder.java
> +public class TableOrder {
중요한 내용은 아니지만, 패키지 명과 이름이 많이 달라서

패키지 명을 변경하거나, 요걸 패키지 명과 맞추면 좋겠다는 생각이 들었어요

2022-04-07 23:58 UTC, seok-2-o commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/OrderLineItems.java
> +        if (items.size() != menus.size()) {
저도 고민을 많이 한 부분인데 
Map<UUID, MenuResponse> menus 를 조회하는 부분이 List<CreatOrderLineItemCommand> item를 통해 일어나는것을
추측할 수 있기때문에 많이 고민하면서 작성하였습니다.

```java
menus.get(id).orElseThrow(() -> ... )
```

을 한다면 말씀하시는 부분을 회피할 수 있는데 동일한 작업을 두번 반복한다는 생각도 드네요.

2022-04-08 00:02 UTC, seok-2-o commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/TableOrder.java
> +public class TableOrder {
패키지명 변경하였습니다.

모델명을 바꾸는게 가장 쉬운 방법이긴 하지면 요구사항을 한번 집착해보았습니다 🤔

2022-04-08 00:08 UTC, seok-2-o commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/OrderTable.java
> +        }
생성자에서 사용할땐 습관적으로 분리하곤 하는데 **하나의 메소드**에서만 사용할때는 
네이밍의 고통에 잘 분리하지 않는 것 같네요 😪 

규남님은 이럴때도 원칙적으로 분리를 하시는편이실까요?

2022-04-08 00:11 UTC, seok-2-o commented on src/main/java/kitchenpos/eatinorders/tobe/domain/dto/CreatOrderLineItemCommand.java
> +package kitchenpos.eatinorders.tobe.domain.dto;
도메인만 가지고 구현하다보니 약참조 구현이 어려워서 
그대로 사용하고 이후에 어플리케이션 레이어 리펙토링을 하게 된다면 깊게 고민해볼 수 있도록 하겠습니다 :)

2022-04-08 00:11 UTC, seok-2-o commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/OrderTable.java
> +        }
메소드로 분리하였습니다!

2022-04-08 10:27 UTC, kyucumber commented on src/main/java/kitchenpos/eatinorders/tobe/domain/model/OrderTable.java
> +        }
```
규남님은 이럴때도 원칙적으로 분리를 하시는편이실까요?
```

저는 요정도 레벨이라면 굳이 분리하지 않는 경우도 많은 것 같네요 ㅎㅎ
학습을 위한 미션이기도 하고, 객체지향 생활 체조 원칙 중 if, else를 쓰지 말자는 구문이 있어서 코멘트 남겨보았어요 😄

2022-04-08 10:28 UTC, kyucumber approved these changes
마지막인 매장 식사 주문 도메인 리팩토링까지 다 완료해주셨네요~ 👍 
고생하셨습니다.

2022-04-08 10:28 UTC, merged