🚀 2단계 - 리팩터링(메뉴)
next-step/ddd-tactical-design pull request #98
Opened 2022-04-11 10:31 UTC by Kaeum

이번에도 잘 부탁드립니다 👍🏻

2022-04-12 15:14 UTC, kyucumber requested changes
안녕하세요, 개인적인 사정으로 리뷰가 조금 늦어 죄송합니다. 😭 

몇가지 코멘트 남겨두었으니 확인 부탁드릴게요~

2022-04-12 15:14 UTC, kyucumber commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +        validatePriceNotBiggerThanSumOfProducts(menuProducts, price);
도메인의 정합성을 잘 지켜주셨네요 👍

2022-04-12 15:14 UTC, kyucumber commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    private List<MenuProduct> menuProducts;
MenuProducts와 같은 일급 컬렉션 형태로 추출하는건 어떨까요?

일급 컬렉션 형태로 추출하면 menuProducts에 대한 로직 일부를 MenuProducts로 옮길 수 있을 것 같아요.

2022-04-12 15:14 UTC, kyucumber commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    protected void changeProduct(Product product) {
menuProducts의 첫번째 요소의 상품을 변경하는 부분은 요구사항에는 없었던 것 같아요.

`List<MenuProduct>`가 임의로 변경될 수 있어 위험하다고 생각해요.

테스트의 편의를 위한 메소드라면 고민이 필요할 것 같습니다.

2022-04-15 10:50 UTC, Kaeum commented on src/main/java/kitchenpos/common/domain/Quantity.java
> +        if(ObjectUtils.isEmpty(quantity) || isNegative(quantity)) {
그렇군요 감사합니다. 혹시 인텔리제이의 경우는 뭐라고 검색하면 나올까요..?ㅎㅎ 못찾겠어서 여쭈어봅니다..!

2022-04-15 10:52 UTC, Kaeum commented on src/main/java/kitchenpos/menus/tobe/domain/Menu.java
> +    protected void changeProduct(Product product) {
테스트를 편의를 위한 메서드여서 protected로 구현하긴 했는데요..
흠 이부분은 조금 더 고민해보겠습니다.

2022-04-20 13:59 UTC, kyucumber commented on src/main/java/kitchenpos/common/domain/Quantity.java
> +        if(ObjectUtils.isEmpty(quantity) || isNegative(quantity)) {
reformat code로 검색해보시면 나올 것 같아요!

린트 등을 이용해 자동으로 맞추면 더 좋겠지만, 일회성 미션에 그런걸 적용하긴 번거로우니 reformat을 습관적으로 해주시면 좋을 것 같아요~

https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2022-04-20 14:00 UTC, merged